### ISSUE TITLE
Optional secondary files

### ISSUE THREAD

**Issue by StarvingMarvin** [common-workflow-language/common-workflow-language#100]
Currently, reference implementation fails when it cant find declared secondary files. What is supposed to be the way to declare optional secondary file (e.g. Picard sort only outputs bai file when given a certain parameter).

**Comment by tetron** [comment]
Currently there is no way to declare optional secondary files.  That's an oversight in the specification.  How do you think we should fix it?

**Comment by ntijanic** [comment]
Perhaps failing to find the secondary file should yield a warning rather than error?

**Comment by portah** [comment]
I have not declared an optional SecondaryFile but lets put it in the other way I declared when a secondary file is required.

```
inputs:
  - id: "#input"
    type: File
    description: |
      The input file can be in BAM format
          (Note: BAM _must_ be sorted by position)
      or <bed/gff/vcf>
    inputBinding:
      position: 1
      secondaryFiles:
        - engine: node-engine.cwl
          script: |
           {
            if ((/.*\.bam$/i).test($job['input'].path))
               return {"path": $job['input'].path+".bai", "class": "File"};
            return [];
           }
      valueFrom:
        engine: node-engine.cwl
        script: |
          {
            var prefix = ((/.*\.bam$/i).test($job['input'].path))?'-ibam':'-i';
            return [prefix,$job['input'].path];
          }

```

**Comment by mr-c** [comment]
Peter agrees with "Perhaps failing to find the secondary file should yield a warning rather than error".

**Comment by ntijanic** [comment]
Bump. Hoping to treat missing `outputBinding.secondaryFiles` as warnings rather than errors. For cases where error is needed, one can add a `${if ($self.secondaryFiles) return $self else raise Exception();}` expression to `outputBinding.valueFrom`.

**Comment by mr-c** [comment]
@ntijanic Can you propose a better syntax than that long javascript line?

**Comment by mr-c** [comment]
@tetron proposed adding a question mark to indicate optionality.

**Comment by kaushik-work** [comment]
#717

**Comment by kaushik-work** [comment]
#658

**Comment by mr-c** [comment]
secondaryFiles are can be optional in v1.1: https://www.commonwl.org/v1.1/CommandLineTool.html#SecondaryFileSchema
