### ISSUE TITLE
proposal: standard cwl:Javascript engine

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#106]
In draft-1 we specified Javascript as the only scripting engine.  In draft-2 we have pluggable scripting engines, but only cwl:JsonPointer is specified as a built-in engine.

Through implementation experience we are learning that requiring all script engine be pluggable is proving to be a bit troublesome, as running a scripting engine in a Docker container brings with it a significant amount of overhead (in the worst case, cluster job dispatch...) even for trivial computations.

For draft-3, I would like to propose that we introduce "cwl:Javascript" as a standard symbolic name for an implementation-provided Javascript/ECMAScript 5.1 engine.  This would make Javascript the preferred but not exclusive scripting engine for CWL, and enable implementations to provide efficient execution of Javascript code fragments for workflow logic.

**Comment by dleehr** [comment]
:+1: for a standard JavaScript engine. I'm using the node engine docker container right now for a [simple concatenation of a directory and a file prefix](https://github.com/Duke-GCB/MMAP-cwl/blob/8bb8f865a3bd04b01c2173c402a6fc851ab78ca7/go-blast/go-blasttool.cwl#L23), and I agree it's a lot of overhead for a trivial computation.

**Comment by ntijanic** [comment]
+1. We are already "cheating" in the SBG implementation by evaluating expressions outside docker if the linked DockerRequirement is something we know is vanilla JS.

**Comment by mr-c** [comment]
+1

**Comment by mr-c** [comment]
This was implemented for Draft-3.
