### ISSUE TITLE
intermediate files from one subworkflow are unavailable to another when using boot2docker

### ISSUE THREAD

**Issue by dleehr** [common-workflow-language/common-workflow-language#108]
When using subworkflows, cwltool leaves intermediate files from one subworkflow in the host's temp directory (and not one with a CLI-specified `tmpdir-prefix`). The next subworkflow in the workflow is not  able to read this file if the host is running boot2docker, and the workflow fails.

This is not an issue with intermediate files from tools within a workflow, only subworkflows within a workflow.

See https://github.com/dleehr/cwl-volumebug for example.

**Comment by tetron** [comment]
I haven't had a chance to dig into this, but perhaps this is just an issues of tmpdir-prefix not getting propagated to the subworkflows?

**Comment by dleehr** [comment]
Could be. I tried to debug a little bit but couldn't trace exactly how subworkflows were instantiated, and also couldn't determine if tmpdir-prefix and outdir-prefix should always be used.

There are a couple areas where tmpdir/outdir are assigned without respecting the prefix:

https://github.com/common-workflow-language/common-workflow-language/blob/aba86ed4dc46e15e85198bfe267c1a8e3c491074/reference/cwltool/draft2tool.py#L215
https://github.com/common-workflow-language/common-workflow-language/blob/aba86ed4dc46e15e85198bfe267c1a8e3c491074/reference/cwltool/workflow.py#L133

I'll tweak those and see if that fixes it.
