### ISSUE TITLE
Add requirements.txt and .python-version to root

### ISSUE THREAD

**Issue by slnovak** [common-workflow-language/common-workflow-language#112]
Hi,

It'd be nice to have the following in the CWL codebase:

* A `requirements.txt` file at project root to list Python dependencies needed to run test-suite.

* A `.python-version` to the root to specify the preferred Python version for development. (see [pyenv](https://github.com/yyuu/pyenv).

**Comment by mr-c** [comment]
Moved to https://github.com/common-workflow-language/cwltool/issues/5
