### ISSUE TITLE
CreateFileRequirement spec clarification

### ISSUE THREAD

**Issue by StarvingMarvin** [common-workflow-language/common-workflow-language#126]
What should be behavior when CreateFileRequirement expression resolves to the File object that has secondaryFiles? Secondary file names are usually related to its parent file, and there is possibility that linking/renaming input file breaks that relation. Also it is not specified if all the secondary files should be linked together with main file, but I think it's safe to assume that answer to that one is yes.

**Comment by tetron** [comment]
Perhaps CreateFileRequirement should be able to come with its own secondaryFiles spec, which could use the substitution rules or a expression to match & rename the secondaryFiles?  Needs further design.

**Comment by StarvingMarvin** [comment]
Actually, I think we shouldn't use CreateFileRequirement for this use case at all. Reason when this is needed is with tools that add secondary files to their inputs. It would be nice if we come up with a way to declare "My output is this input + this additional secondaryFile". This would simultaneously solve #127 . Runtime environment should than make file + secondary files available in tools working dir under the same name.

**Comment by mr-c** [comment]
@StarvingMarvin Are your concerns satisfied with v1.0?

**Comment by mr-c** [comment]
@StarvingMarvin I'm going to close this for now; please reopen if needed.
