### ISSUE TITLE
Workflow output file from step1 did not copy to input of step 2

### ISSUE THREAD

**Issue by portah** [common-workflow-language/common-workflow-language#128]
Here is a 2 steps workflow:
https://github.com/SciDAP/workflows/blob/master/workflows/scidap/bam-genomecov-bigwig.cwl
During execution no errors or what ever but output file from step1 -id "#genomecov" did not go to input of step2 - id "#sort"
File from step1 exists /tmp/tmpIqYrqq/genomecov.bed

root@vagrant-ubuntu-vivid-64:/workflows/workflows/scidap# ./bam-genomecov-bigwig.cwl ./bam-genomecov-bigwig-job.json 
/usr/local/bin/cwl-runner 1.0.20150915034626
[job 139981736496528] /tmp/tmpIqYrqq$ docker run -i --volume=/workflows/workflows/scidap/test-files/rna.SRR948778.bam.bai:/tmp/job685954931_test-files/rna.SRR948778.bam.bai:ro --volume=/workflows/workflows/scidap/test-files/mm10-chrNameLength.txt:/tmp/job685954931_test-files/mm10-chrNameLength.txt:ro --volume=/workflows/workflows/scidap/test-files/rna.SRR948778.bam:/tmp/job685954931_test-files/rna.SRR948778.bam:ro --volume=/tmp/tmpIqYrqq:/tmp/job_output:rw --volume=/tmp/tmpQDf6j9:/tmp/job_tmp:rw --workdir=/tmp/job_output --user=0 --rm --env=TMPDIR=/tmp/job_tmp --env=PATH=/usr/local/bin/:/usr/bin:/bin scidap/bedtools2:v2.25.0 bedtools genomecov -ibam /tmp/job685954931_test-files/rna.SRR948778.bam -g /tmp/job685954931_test-files/mm10-chrNameLength.txt -bg -scale 1 > /tmp/tmpIqYrqq/genomecov.bed
[job 139981737411984] /tmp/tmp0sr1d5$ sort -k1,1 -k2,2n > /tmp/tmp0sr1d5/sorted.bed
[workflow 139981741370064] outdir is /workflows/workflows/scidap
Final process status is success
{
    "outfile": {
        "path": "/workflows/workflows/scidap/sorted.bed", 
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709", 
        "class": "File", 
        "size": 0
    }
}

**Comment by tetron** [comment]
Try updating cwltool and merge my changes in b3ce0b8 

It works for me now:

```
$ cwltool ./bam-genomecov-bigwig.cwl ./bam-genomecov-bigwig-job.json 
/home/peter/work/cwl-venv/bin/cwltool 1.0.20150918080732
[job 140041594914576] /tmp/tmpvBrOn7$ docker run -i --volume=/home/peter/work/workflows/workflows/scidap/test-files/rna.SRR948778.bam.bai:/tmp/job762961655_test-files/rna.SRR948778.bam.bai:ro --volume=/home/peter/work/workflows/workflows/scidap/test-files/mm10-chrNameLength.txt:/tmp/job762961655_test-files/mm10-chrNameLength.txt:ro --volume=/home/peter/work/workflows/workflows/scidap/test-files/rna.SRR948778.bam:/tmp/job762961655_test-files/rna.SRR948778.bam:ro --volume=/tmp/tmpvBrOn7:/tmp/job_output:rw --volume=/tmp/tmp1_qK6y:/tmp/job_tmp:rw --workdir=/tmp/job_output --user=1001 --rm --env=TMPDIR=/tmp/job_tmp --env=PATH=/usr/local/bin/:/usr/bin:/bin scidap/bedtools2:v2.25.0 bedtools genomecov -ibam /tmp/job762961655_test-files/rna.SRR948778.bam -g /tmp/job762961655_test-files/mm10-chrNameLength.txt -bg -scale 1 > /tmp/tmpvBrOn7/genomecov.bed
[job 140041594990160] /tmp/tmpSi2jvJ$ sort -k1,1 -k2,2n /tmp/tmpvBrOn7/genomecov.bed > /tmp/tmpSi2jvJ/sorted.bed
[workflow 140041592982224] outdir is /home/peter/work/workflows/workflows/scidap
Final process status is success
{
    "outfile": {
        "path": "/home/peter/work/workflows/workflows/scidap/sorted.bed", 
        "checksum": "sha1$3d8ba8ae446580b84689148efc4542d4bc4b7f22", 
        "class": "File", 
        "size": 19856977
    }
}
```

**Comment by portah** [comment]
Looks like fixed, 
Thanks

**Comment by portah** [comment]
Can't check because now Import does not work
```
root@vagrant-ubuntu-vivid-64:/workflows/workflows/scidap# ./bam-genomecov-bigwig.cwl ./bam-genomecov-bigwig-job.json 
/usr/local/bin/cwl-runner 1.0.20150918080732
Tool definition failed validation:
While checking field `steps`
  While checking object `file:///workflows/workflows/scidap/bam-genomecov-bigwig.cwl#genomecov`
    While checking field `inputs`
      While checking object `file:///workflows/tools/bedtools-genomecov.cwl#dept`
        Field `type` contains undefined reference to `file:///workflows/tools/bedtools-genomecov.cwl#depts`
    While checking field `inputs`
      While checking object `file:///workflows/workflows/scidap/bam-genomecov-bigwig.cwl#genomecov.dept`
        Field `type` contains undefined reference to `file:///workflows/workflows/scidap/bam-genomecov-bigwig.cwl#depts`
    While checking object `file:///workflows/tools/bedtools-genomecov.cwl`
      While checking field `inputs`
        While checking object `file:///workflows/tools/bedtools-genomecov.cwl#dept`
          Field `type` contains undefined reference to `file:///workflows/tools/bedtools-genomecov.cwl#depts`
root@vagrant-ubuntu-vivid-64:/workflows/workflows/scidap# 
```

**Comment by tetron** [comment]
Try 5783f59ff49731b6eabdb004e10a24daf0ffde7b in the scidap-master branch in the workflows repository.
