### ISSUE TITLE
Add testing protocol to specification

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#133]
The conformance tests use cwltest.py to run a series of tests.  This should be formally specified in draft-3, and it should also be possible to include test cases directly in a Tool or Workflow document.

**Comment by mr-c** [comment]
Will be separate guidance document

**Comment by mr-c** [comment]
See https://github.com/common-workflow-language/common-workflow-language/blob/master/CONFORMANCE_TESTS.md
