### ISSUE TITLE
Additional options for output file collection

### ISSUE THREAD

**Issue by StarvingMarvin** [common-workflow-language/common-workflow-language#134]
Right now the only way to specify which files goes to which output are globs, but we had issues with tools where ordinary globs weren't enough to distinguish between different outputs (e.g filenames without "_something_"). We kinda solved our problem with bash extended globs, but it's  not the cleanest solution (we have to run it inside a docker container), and it is not really expected that other implementations will handle them. Adding another option in CommandOutputBinding like `"regexp": "<something>"` would probably suffice. Finally we could go "full Turing-complete" and add an option like `"filter": {expression}` that could get list of all files from working dir and return whatever files appropriate for that output.

**Comment by tetron** [comment]
@StarvingMarvin how about this?

We add a special case `glob: **` that captures the entire contents of the output directory (including subdirectories), then use an expression to do arbitrary filtering.

```yaml
outputBinding:
  glob: **
  outputEval: |
   ${
     var ret = [];
     for (var i = 0; i < self.length; i++) {
       // only capture .txt files
       if (self[i].path.match(/\.txt$/) { ret.push(self[i]); }
     }
     return ret;
   }
```

**Comment by ntijanic** [comment]
+1

**Comment by mr-c** [comment]
We should get the major changes in Draft 3 finished first; I am moving this to the Draft 4 milestone.

**Comment by mr-c** [comment]
According to @tetron this will be obsoleted by DirectoryType
