### ISSUE TITLE
Be able to run a workflow by only specifying path to the job document

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#148]
Either by referencing the file name of the workflow description or deducing it.

**Comment by tetron** [comment]
Having a reference to the workflow file seems reasonable.  Something like:

```
{
  "input": { "path": "input.txt", "class": "File" },
  "cwl:tool": "dostuff.cwl"
}
```

I'm not so keen on deducing the workflow name from the file, it only works there is only one or small number of naming conventions, which may not work for everyone.

**Comment by tetron** [comment]
One way to achieve this functionality is to write a 1-step workflows that has default values for all the inputs.  What do you think?

**Comment by mr-c** [comment]
I think the `"cwl:tool"` approach above would be better. Can point to a local path or global URI.

**Comment by tetron** [comment]
Merged

**Comment by mr-c** [comment]
What was merged?

**Comment by mr-c** [comment]
Ah, 678eb5ee

Great, thanks!
