### ISSUE TITLE
Unable to install reference implimentation

### ISSUE THREAD

**Issue by skanwal** [common-workflow-language/common-workflow-language#149]
I am not able to install python reference implementation using the guidelines provided on github.

After cloning the github repository, when I try to "cd common-workflow-language/reference && python setup.py install", it throws an error:
No such fie or directory.

The reference implementation actually does not come with any directory named "reference"
Any help will be much appreciated.
Thanks.

**Comment by mr-c** [comment]
Hello @skanwal, thank you for your report. You are correct, our instructions are out of date. I will fix that now.

**Comment by mr-c** [comment]
Does `pip install cwl-runner` work for you?

**Comment by skanwal** [comment]
Thanks @mr-c 
It worked this time :)

**Comment by mr-c** [comment]
Great! I am going to close this issue now. Thanks again for reporting this.
