### ISSUE TITLE
Specify a collation order for files matched by the glob pattern (UTF-8?)

### ISSUE THREAD

**Issue by ntijanic** [common-workflow-language/common-workflow-language#15]

**Comment by mr-c** [comment]
Since there is an official unicode collation algorithm we should use that without any [tailoring](http://unicode.org/reports/tr10/#Tailoring).

http://unicode.org/reports/tr10/

http://unicode.org/faq/collation.html

**Comment by mr-c** [comment]
Turns out that POSIX specifies that glob is sorted (using the same locale)

**Comment by tetron** [comment]
See #440
