### ISSUE TITLE
allow negative numbers for reverse indexing on command line

### ISSUE THREAD

**Issue by satra** [common-workflow-language/common-workflow-language#151]
allow `position` field for command line bindings to take positive and negative numbers, with negative numbers indicating position from the end of the list (e.g., -1 would correspond to last field).

in many of our command line tools only some positions are fixed and they don't necessarily follow any specific patterns.

**Comment by mr-c** [comment]
Thank you @satra for writing this up. Can you give a concrete example?

**Comment by satra** [comment]
here are a couple:
`Usage: fslmaths [-dt <datatype>] <first_input> [operations and inputs] <output> [-odt <datatype>]`
and
```
Usage: flirt [options] -in <inputvol> -ref <refvol> -out <outputvol>
       flirt [options] -in <inputvol> -ref <refvol> -omat <outputmatrix>
       flirt [options] -in <inputvol> -ref <refvol> -applyxfm -init <matrix> -out <outputvol>
```

flirt has about 45 options.

**Comment by satra** [comment]
this is nipype's command line version of the above usage:

```
usage: nipype_cmd nipype.interfaces.fsl FLIRT [-h] [--angle_rep ANGLE_REP]
                                              [--apply_isoxfm APPLY_ISOXFM]
                                              [--apply_xfm] [--args ARGS]
                                              [--bbrslope BBRSLOPE]
                                              [--bbrtype BBRTYPE]
                                              [--bgvalue BGVALUE]
                                              [--bins BINS]
                                              [--coarse_search COARSE_SEARCH]
                                              [--cost COST]
                                              [--cost_func COST_FUNC]
                                              [--datatype DATATYPE]
                                              [--display_init] [--dof DOF]
                                              [--echospacing ECHOSPACING]
                                              [--environ ENVIRON]
                                              [--fieldmap FIELDMAP]
                                              [--fieldmapmask FIELDMAPMASK]
                                              [--fine_search FINE_SEARCH]
                                              [--force_scaling]
                                              [--ignore_exception]
                                              [--in_matrix_file IN_MATRIX_FILE]
                                              [--in_weight IN_WEIGHT]
                                              [--interp INTERP]
                                              [--min_sampling MIN_SAMPLING]
                                              [--no_clamp] [--no_resample]
                                              [--no_resample_blur]
                                              [--no_search]
                                              [--out_file OUT_FILE]
                                              [--out_log OUT_LOG]
                                              [--out_matrix_file OUT_MATRIX_FILE]
                                              [--output_type OUTPUT_TYPE]
                                              [--padding_size PADDING_SIZE]
                                              [--pedir PEDIR]
                                              [--ref_weight REF_WEIGHT]
                                              [--rigid2D] [--save_log]
                                              [--schedule SCHEDULE]
                                              [--searchr_x SEARCHR_X]
                                              [--searchr_y SEARCHR_Y]
                                              [--searchr_z SEARCHR_Z]
                                              [--sinc_width SINC_WIDTH]
                                              [--sinc_window SINC_WINDOW]
                                              [--terminal_output TERMINAL_OUTPUT]
                                              [--uses_qform]
                                              [--verbose VERBOSE]
                                              [--wm_seg WM_SEG]
                                              [--wmcoords WMCOORDS]
                                              [--wmnorms WMNORMS]
                                              in_file reference
```

**Comment by mr-c** [comment]
@tetron Are the position numbers required?

**Comment by tetron** [comment]
@satra "position" is a sorting key.  You can have multiple bindings with the same position, which means you don't care about the order within a given position (although in that case, within the set of parameters in the same position it will be sorted by the parameter name so that the ordering is still deterministic).  If "position" is not provided, the default value is 0.

However, because "position" is a sort key and not an absolute value, it makes is difficult to count from the end.  Currently, if you have something in position -1, that will be interpreted as having higher precedence (earlier in the ordering) than position 0.

**Comment by satra** [comment]
@tetron - thanks - actually i think based on your explanation, the second of my examples would not be hard at all, since position only would refer to two fixed items eliminating the need for -1. in general the problem arises when the number of positional things in the middle changes depending on some sub-component of the command. i went back and looked through many of the instances where we use negative numbers, and i think all of them could be redone with positive numbers. i'll close this issue for now till i have a more concrete example.

out of curiosity, how would you handle the following command in cwl?

```
Usage: fslstats [-t] <input> [options]

-t will give a separate output line for each 3D volume of a 4D timeseries
Note - options are applied in order, e.g. -M -l 10 -M will report the non-zero mean, apply a threshold and then report the new nonzero mean

-l <lthresh> : set lower threshold
-u <uthresh> : set upper threshold
-r           : output <robust min intensity> <robust max intensity>
-R           : output <min intensity> <max intensity>
-e           : output mean entropy ; mean(-i*ln(i))
-E           : output mean entropy (of nonzero voxels)
-v           : output <voxels> <volume>
-V           : output <voxels> <volume> (for nonzero voxels)
-m           : output mean
-M           : output mean (for nonzero voxels)
-s           : output standard deviation
-S           : output standard deviation (for nonzero voxels)
-w           : output smallest ROI <xmin> <xsize> <ymin> <ysize> <zmin> <zsize> <tmin> <tsize> containing nonzero voxels
-x           : output co-ordinates of maximum voxel
-X           : output co-ordinates of minimum voxel
-c           : output centre-of-gravity (cog) in mm coordinates
-C           : output centre-of-gravity (cog) in voxel coordinates
-p <n>       : output nth percentile (n between 0 and 100)
-P <n>       : output nth percentile (for nonzero voxels)
-a           : use absolute values of all image intensities
-n           : treat NaN or Inf as zero for subsequent stats
-k <mask>    : use the specified image (filename) for masking - overrides lower and upper thresholds
-d <image>   : take the difference between the base image and the image specified here
-h <nbins>   : output a histogram (for the thresholded/masked voxels only) with nbins
-H <nbins> <min> <max>   : output a histogram (for the thresholded/masked voxels only) with nbins and histogram limits of min and max
```

we handle it in nipype by simply asking the 3rd argument to be a string. we don't like it but there is no easy way to both allow optional arguments and user specified order. the ways to do it feel clunky.

https://github.com/nipy/nipype/blob/f9c98baa0a968451f4f8c78a74249c41e61d1966/nipype/interfaces/fsl/utils.py#L501

**Comment by tetron** [comment]
Hi @satra 

Take a look at this example:

Tool: https://github.com/common-workflow-language/common-workflow-language/blob/master/draft-2/draft-2/tmap-tool.cwl

Job: https://github.com/common-workflow-language/common-workflow-language/blob/master/draft-2/draft-2/tmap-job.json

Command line generated by job:
```
tmap mapall stage1 map1 --min-seq-length 20 map2 --min-seq-length 20 stage2 map1 --max-seq-length 20 --min-seq-length 10 --seed-length 16 map2 --max-seed-hits -1 --max-seq-length 20 --min-seq-length 10
```

The idea is to define a parameter which is an array of one or more user defined types (using SchemaDefRequirement) and each user defined type has an inputBinding for the specific command line option it represents.

**Comment by satra** [comment]
@tetron - thanks for the example, but if i understand this correctly, it is specifying a specific set of order of options. in the command  line tool i listed above, generating such a set of orders would be prohibitive.

also i don't see how the json specifies an order of fields. the following uses a dictionary, so no order.

https://github.com/common-workflow-language/common-workflow-language/blob/master/draft-2/draft-2/tmap-job.json#L23

perhaps i'm missing something here.

to make things concrete with the above example:

1. order matters
`fslstats data.nii.gz -m -l 10 -M` would be different from `fslstats data.nii.gz -M -l 10 -m`

2. lists are arbitrary
`fslstats data.nii.gz -m -l 10 -M -s`

**Comment by ntijanic** [comment]
I think the way to encode `[options]` in this case is either a non-quoted string or a list of strings (basically same as you said nipype handles it).

The alternative is a much more complicated `List<Union<Flag, LThresh, RThresh, ...>>` where e.g. `LThresh` is defined a number that gets a `-l` prefix and `Flag` is an enum of all boolean switches. 
In this case the input object would look something like `options: ['-m', {"class": "LThresh", "value": 5}, '-M', '-m']`, with the command line segment being `-m -l 5 -M -m`.
The reason to use the alternative might be possible validation or GUI generation where person submitting the job would get an enumeration of all options in e.g. a dropdown rather than a string with documentation.

Personally, I like the simpler option much more.
