### ISSUE TITLE
Undocummented spec feature: list at document top-level

### ISSUE THREAD

**Issue by StarvingMarvin** [common-workflow-language/common-workflow-language#155]
Conformance tests rely on executors handling document that is list at the top level, bu executing element with id "#main", but I can't find this mentioned in the spec.

**Comment by tetron** [comment]
You're right.  Sorry about that.  Will be fixed in draft-3.

**Comment by tetron** [comment]
Unless you think the behavior should be different.

**Comment by StarvingMarvin** [comment]
I feel that slightly cleaner solution is for implementation to handle fragment part on command line, so "what to run" would be `tool.cwl#main`. Also we might propose a new key for process object, say "parts" or "definitions" that would include list of stuff with ids, and main would just be what left as the document root.

**Comment by tetron** [comment]
This behavior has been removed from cwltool and the test cases no longer rely on it.
