### ISSUE TITLE
Move secondaryFiles on inputs.

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-language/common-workflow-language#161]
Needs to be with the input and not with the inputBinding.

**Comment by mr-c** [comment]
@jmchilton Can this wait for Draft 4?

**Comment by jmchilton** [comment]
I made this issue based on discussions others were having, I don't even really remember what it means :worried:.

**Comment by mr-c** [comment]
Heh.

Looks to be related to #127

**Comment by ntijanic** [comment]
Yes - if proposed design makes it to draft-3, we can close this as well.

The issue is that the `secondaryFiles` is currently nested under `inputBinding` and should just be a property of the input itself since non-bound inputs can have required secondary files.

**Comment by ntijanic** [comment]
Closing - can be considered duplicate of #127.
