### ISSUE TITLE
Tool definition failed validation

### ISSUE THREAD

**Issue by skanwal** [common-workflow-language/common-workflow-language#163]
![screen shot 2015-11-09 at 1 01 31 pm](https://cloud.githubusercontent.com/assets/9857259/11024445/8181da4a-86e2-11e5-9fd7-f5ad64835c3e.png)

Can someone please help me with this issue? (screenshot of error attached).

**Comment by tetron** [comment]
Could you post the file you are working on?  It appears that your "type" field has an error.  Just from looking at the error I am guessing it should say "type: File" instead of "type: #file".

**Comment by skanwal** [comment]
Thanks for the reply.
I couldn't find any thing like "type: File" in files I am working on.
I can't attach files as I don't have write permission to this repository. That is why I'll copy paste the code

CWL FILE:

#!/usr/bin/env cwl-runner

class: Workflow

inputs:
  - id: "#reference"
    type: File
    description: reference human genome file 

  - id: "#FwdReadFile"
    type: File
    description: file containing the first end of paired end reads in fastq format

  - id: "#RevReadFile"
    type: File
    description: file containing the second end of paired end reads in fastq format
    
  - id: "#dbSNP"
    type: File
    description: list of known variant files in vcf format

#parameters for bwa aln    
  - id: "#MaxEditDist"
    type: int
    description: max diff (int) or missing prob under 0.02 err rate (float) [0.04]
    
  - id: "#MaxGapOpens"
    type: int
    description: maximum number or fraction of gap opens [1]

  - id: "#MaxGapExtensions"
    type: int
    description: maximum number of gap extensions, -1 for disabling long gaps [-1] 
 
  - id: "#LongDeletion"
    type: int
    description: maximum occurrences for extending a long deletion [10]
 
  - id: "#LongIndel"
    type: int
    description: do not put an indel within INT bp towards the ends [5]
 
  - id: "#SeedSubseq"
    type: int
    description: seed length [32]
 
  - id: "#SeedMaxEditDist"
    type: int
    description: maximum differences in the seed [2]
 
  - id: "#MisMatchPenalty"
    type: int
    description: mismatch penalty [3]
 
  - id: "#GapOpenPenalty"
    type: int
    description: gap open penalty [11]
    
  - id: "#GapExtensionPenalty"
    type: int
    description: gap extension penalty [4]
     
  - id: "#BestHitsThreshold"
    type: int
    description: stop searching when there are >INT equally best hits [30]
    
  - id: "#DisableIterativeSearch"
    type: boolean
    decription: noniterative mode search for all ndifference hits (slooow)
      
#parameters for bwa sampe 
    
  - id: "#maxHitPaired"
    type: int
    description: Maximum number of alignments to output in the XA tag for reads paired properly. If a read has more than INT hits, the XA tag will not be written. [3]
     
  - id: "#maxHitDis"
    type: int
    description: Maximum number of alignments to output in the XA tag for disconcordant read pairs (excluding singletons). If a read has more than INT hits, the XA tag will not be written. [10]
    
  - id: "#maxInsSize"
    type: int
    description: Maximum insert size for a read pair to be considered being mapped properly. Since 0.4.5, this option is only used when there are not enough good alignment to infer the distribution of insert sizes. [500]
    
  - id: "#maxOcc"
    type: int
    description: Maximum occurrences of a read for pairing. A read with more occurrneces will be treated as a single-end read. Reducing this parameter helps faster pairing. [100000]
 
  - id: "#specifyReadGroup"
    type: boolean
    description: Specify the read group in a format like ‘@RG\tID:foo\tSM:bar’. [null]
    
#parameters for MarkDuplicates

  - id: "#outputName"
    type: string
    description: The output file to write marked records to Required
 
  - id: "#regularExpression"
    type: string
    description: Regular expression that can be used to parse read names in the incoming SAM file. Read names are parsed to extract three variables tile/region, x coordinate and y coordinate. These values are used to estimate the rate of optical duplication in order to give a more accurate estimated library size. Set this option to null to disable optical duplicate detection. The regular expression should contain three capture groups for the three variables, in order. It must match the entire read name. Note that if the default regex is specified, a regex match is not actually done, but instead the read name is split on colon character. For 5 element names, the 3rd, 4th and 5th elements are assumed to be tile, x and y values. For 7 element names (CASAVA 1.8), the 5th, 6th, and 7th elements are assumed to be tile, x and y values. Default value "[a-zA-Z0-9]+:[0-9]:([0-9]+):([0-9]+):([0-9]+).*." This option can be set to 'null' to clear the default value
 
  - id: "#offsetValue"
    type: int
    description: The maximum offset between two duplicte clusters in order to consider them optical duplicates. This should usually be set to some fairly small number (e.g. 5-10 pixels) unless using later versions of the Illumina pipeline that multiply pixel values by 10, in which case 50-100 is more normal. Default value 100. This option can be set to 'null' to clear the default value
 
  - id: "#removeDuplicates"
    type: boolean
    description: If true do not write duplicates to the output file instead of writing them with appropriate flags set.  Default value false. This option can be set to 'null' to clear the default value. Possible values {true, false}
 
  - id: "#readSorted"
    type: boolean
    description: If true, assume that the input file is coordinate sorted even if the header says otherwise.  Default value false. This option can be set to 'null' to clear the default value. Possible values {true, false}
  
#parameters for RealignerTargetCreator

  - id: "#tool"
    type: File
    description: jar file used for this step from GATK package
    
    
outputs:
  - id: "#readfileFwdSai_output"
    type: File
    source: "#bwa-aln1.readfileFwdSai_output"

  - id: "#readfileRevSai_output"
    type: File
    source: "#bwa-aln2.readfileRevSai_output"

  - id: "#bwaSampe_output"
    type: File
    source: "#bwa-sampe.output"


steps:

  - id: "#bwa-aln1"
    run: { import: bwa-aln.cwl }
    inputs:
      - { id: "bwa-aln1.MaxEditDist", source: "#MaxEditDist" }
      - { id: "#bwa-aln1.MaxGapOpens", source: "#MaxGapOpens" }
      - { id: "#bwa-aln1.MaxGapExtensions", source: "#MaxGapExtensions" }
      - { id: "#bwa-aln1.LongDeletion", source: "#LongDeletion" }
      - { id: "#bwa-aln1.LongIndel", source: "#LongIndel" }
      - { id: "#bwa-aln1.SeedSubseq", source: "#SeedSubseq" }
      - { id: "#bwa-aln1.SeedMaxEditDist", source: "#SeedMaxEditDist" }
      - { id: "#bwa-aln1.MisMatchPenalty", source: "#MisMatchPenalty" }
      - { id: "#bwa-aln1.GapOpenPenalty", source: "#GapOpenPenalty" }
      - { id: "#bwa-aln1.GapExtensionPenalty", source: "#GapExtensionPenalty" }
      - { id: "#bwa-aln1.BestHitsThreshold", source: "#BestHitsThreshold" }
      - { id: "#bwa-aln1.DisableIterativeSearch", source: "#DisableIterativeSearch" }
      - { id: "#bwa-aln1.reference", source: "#reference" }
      - { id: "#bwa-aln1.FwdReads", source: "#FwdReadFile" }
      
    outputs:
      - { id: "#bwa-aln1.readfileFwdSai_output" }
      
  - id: "#bwa-aln2"
    run: { import: bwa-aln.cwl }
    inputs:
      - { id: "#bwa-aln2.reference", source: "#reference" }
      - { id: "#bwa-aln2.FwdReads", source: "#RevReadFile" }
      - { id: "bwa-aln2.MaxEditDist", source: "#MaxEditDist" }
      - { id: "#bwa-aln2.MaxGapOpens", source: "#MaxGapOpens" }
      - { id: "#bwa-aln2.MaxGapExtensions", source: "#MaxGapExtensions" }
      - { id: "#bwa-aln2.LongDeletion", source: "#LongDeletion" }
      - { id: "#bwa-aln2.LongIndel", source: "#LongIndel" }
      - { id: "#bwa-aln2.SeedSubseq", source: "#SeedSubseq" }
      - { id: "#bwa-aln2.SeedMaxEditDist", source: "#SeedMaxEditDist" }
      - { id: "#bwa-aln2.MisMatchPenalty", source: "#MisMatchPenalty" }
      - { id: "#bwa-aln2.GapOpenPenalty", source: "#GapOpenPenalty" }
      - { id: "#bwa-aln2.GapExtensionPenalty", source: "#GapExtensionPenalty" }
      - { id: "#bwa-aln2.BestHitsThreshold", source: "#BestHitsThreshold" }
      - { id: "#bwa-aln2.DisableIterativeSearch", source: "#DisableIterativeSearch" }
      
    outputs:
      - { id: "#bwa-aln2.readfileRevSai_output" }

  - id: "#bwa-sampe"
    run: { import: bwa-sampe.cwl }
    inputs:
      - { id: "#bwa-sampe.maxHitPaired", source: "#maxHitPaired" }
      - { id: "#bwa-sampe.maxHitDis", source: "#maxHitDis" }
      - { id: "#bwa-sampe.maxInsSize", source: "#maxInsSize" }
      - { id: "#bwa-sampe.maxOcc", source: "#maxOcc" }
      - { id: "#bwa-sampe.specifyReadGroup", source: "#specifyReadGroup" }
      - { id: "#bwa-sampe.reference", source: "#reference" }
      - { id: "#bwa-sampe.readfileFwdSai_output", source: "#bwa-aln1.readfileFwdSai_output" }
      - { id: "#bwa-sampe.readfileRevSai_output", source: "#bwa-aln2.readfileRevSai_output" }
      - { id: "#bwa-sampe.FwdReadFile", source: "#FwdReadFile" }
      - { id: "#bwa-sampe.RevReadFile", source: "#RevReadFile" }
    outputs:
      - { id: "#bwa-sampe.output" }

JSON FILE:

{  
     "reference": {
        "class": "File",
        "path": "../data/GATK-complete-workflow/Ref_datasets/hg19.fa"
    }, 
     "FwdReadFile": {
        "class": "File",
        "path": "../data/GATK-complete-workflow/Fastq-files/510000101_CTP_010_HAYJ6ADXX_GTAGAGGA-GTAAGGAG_L001_R1.fastq"
    }, 
     "RevReadFile": {
        "class": "File",
        "path": "../data/GATK-complete-workflow/Fastq-files/510000101_CTP_010_HAYJ6ADXX_GTAGAGGA-GTAAGGAG_L001_R2.fastq"
    },
	"MaxEditDistance": {
        "class": "int",
        "value": 0
    },
    "MaxGapOpen": {
        "class": "int",
        "value": 1
    }, 
	"MaxGapExtensions": {
        "class": "int",
        "value": -1
    },  
    "LongDeletion": {
        "class": "int",
        "value": 16
    },   
    "LongIndel": {
        "class": "int",
        "value": 5
    }, 
    "SeedSubseq": {
        "class": "int",
        "value": -1
    },
    "SeedMaxEditDist": {
        "class": "int",
        "value": 2
    },
    "MisMatchPenalty": {
        "class": "int",
        "value": 3
    },
    "GapOpenPenalty": {
        "class": "int",
        "value": 11
    }, 
    "#GapExtensionPenalty": {
        "class": "int",
        "value": 4
    }, 
    "BestHitsThreshold": {
        "class": "int",
        "value": null
    }, 
    "DisableIterativeSearch": {
        "class": "boolean",
        "value": "False"
    }, 
    "maxHitPaired": {
        "class": "int",
        "value": 3
    },
    "maxHitDis": {
        "class": "int",
        "value": 10,
    }, 
	"maxIntSize": {
        "class": "int",
        "value": 500
    },  
    "maxOcc": {
        "class": "int",
        "path": 100000
    },   
    "specifyReadGroup": {
        "class": "boolean",
        "value": true
    }
}


Any help will be much appreciated.

**Comment by skanwal** [comment]
We managed to solve this error :)
Thanks.

**Comment by mr-c** [comment]
Thank you @skanwal for your report. I am going to close this issue; cheers!
