### ISSUE TITLE
$outdir not defined when using nodejs-engine expressions

### ISSUE THREAD

**Issue by vardaofthevalier** [common-workflow-language/common-workflow-language#168]
I've been trying to reference $outdir using commonworkflowlanguage/nodejs-engine, but I keep getting the following error:

```
/Users/ahahn/devtools/cgc/cwl-python/bin/cwl-runner 1.0.20151110030107

/usr/local/bin/cwlNodeEngine.js:40
    process.stdout.write(JSON.stringify(require("vm").runInNewContext(fn, {}))
                                                      ^
ReferenceError: $outdir is not defined
    at evalmachine.<anonymous>:4:20
    at evalmachine.<anonymous>:4:88
    at Socket.<anonymous> (/usr/local/bin/cwlNodeEngine.js:40:55)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)
Workflow error:
  Expression engine returned non-zero exit code on evaluation of
{
    "script": "$outdir.join($job['fasta_sequence'].path.split('/').slice(-1)[0])", 
    "job": {
        "fasta_sequence": {
            "path": "/tmp/job616674167_cwl-workspace/Homo_sapiens.GRCh38.dna.primary_assembly.fa", 
            "class": "File"
        }, 
        "id": "file:///Users/ahahn/devtools/cgc/bioinformatics-pipelines/cwl-examples/samtools/samtools-faidx.json"
    }, 
    "context": null, 
    "engineConfig": [], 
    "tmpdir": "/tmp/job_tmp", 
    "outdir": "/tmp/job_output"
}
```

It looks like $outdir is defined in the output object based on the error output, but I notice on lines 35 and 36 of the entrypoint script for the nodejs-engine container that the only variables being set are $job and $self.  I was wondering if this might have something to do with the error that I'm getting, and if so, is this the intended behavior?  The reason I need to be able to access $outdir is because the tool that I'm working on requires that the input file be in the working directory, so I'm trying to use CreateFileRequirement to copy the file to $outdir using an expression to create the file name.

**Comment by ntijanic** [comment]
The node expression engine doesn't seem to bind $outdir at all. But this is always the current directory for the job. So, for this case, you can put just the file name (no path - just the `$job['fasta_sequence'].path.split('/').slice(-1)[0]` part) in the CreateFileRequirement and it should be "copied" to cwd (which is also the $outdir).

**Comment by vardaofthevalier** [comment]
Thanks, that worked for me!  I'll close the issue now.
