### ISSUE TITLE
Create CWL wrappers automatically from Python Argparse using programs

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#175]
@brainstorm and I are kicking this off by refactoring @erasche 's gxargparse project

https://github.com/common-workflow-language/gxargparse/tree/cwl-refactor

Others are welcome to join in!

Plan:

1) Simplify the `parse_args` method so that it just picks between the Galaxy tool wrapper generation, CWL tool description generation or the pass through to standard `argparse`. Move existing `parse_args` method to `parse_args_galaxy` and create a `parse_args_cwl` companion

2) Flesh out support for every valid argparse use

3) review remaining CWL tool description concepts that aren't yet represented to make sure we didn't miss anything; document why they aren't used.

4) write many tests during 1-3; write more tests to achieve ~99% coverage of the CWL branch.

5) at some point announce the tool on a larger basis to get feedback from the community

**Comment by mr-c** [comment]
- [ ] py3+2 compat

**Comment by erasche** [comment]
@mr-c very exciting!! Please upstream all your work, I'm happy to merge it and help however I can :) I'm sorry I've let my repo languish for a while, other things have gotten in the way.

**Comment by mr-c** [comment]
- [ ] copy `argparse/argparse_translation.py` to `argparse/argparse_galaxy_translation.py` and `argparse/argparse_cwl_translation.py`.
- [ ] modify `argparse/argparse_cwl_translation.py` to work with @brainstorm 's jinja2 templates

**Comment by erasche** [comment]
:+1: for j2 templates, I'd much rather see those than that gosh-awful attempt at a galaxyXml library I built.

**Comment by satra** [comment]
@brainstorm - if you have time, you could take a look at nipype_cmd as an example to hack on. it makes all nipype interfaces accessible on the command line through argparse, so it may be a good place to even convert to cwl as an option and it may provide a whole range of test cases.

**Comment by brainstorm** [comment]
Today while @mr-c was visiting Stockholm we concluded that the best course of action to push this project forward would be to apply as a [GSoC project under the OBF umbrella](http://www.open-bio.org/wiki/Google_Summer_of_Code). 

So here comes some preliminar abstract to apply into the current 2016 edition (which deadline is in 19th February 2016):

https://docs.google.com/a/nopcode.org/document/d/121RsDUUlBSsMw4cAyKhjBRkgUOAT7qakBdJDK8zRw38/edit?usp=sharing

Feedback and edits are welcome!

**Comment by denis-yuen** [comment]
I look forward to seeing how this project goes. Java has a bunch of similar CLI libraries (e.g. commons-cli, jopt, jcommander, etc.) that could be addressed with a similar approach.

**Comment by mr-c** [comment]
@denis-yuen Thanks! If you want to start the Java equivalent version of this then please go ahead :-)

**Comment by mr-c** [comment]
See also https://github.com/stefanristeski/rabixator for a sketch of a docopt based approach.

**Comment by brainstorm** [comment]
@denis-yuen, thanks for your input! Do you know any attempt(s) to introspect/hijack those arguments as the `argparse`/`docopt` "hacks" do?

**Comment by mr-c** [comment]
https://github.com/common-workflow-language/gxargparse/tree/cwl-refactor but still needs publishing to PyPI and adverstising in the CWL docs

**Comment by mr-c** [comment]
This has been merged upstream to the recently renamed [argparse2tool](https://github.com/erasche/argparse2tool) repository.
