### ISSUE TITLE
Coordinating with Amazon and Google

### ISSUE THREAD

**Issue by jpellman** [common-workflow-language/common-workflow-language#177]
Are there any efforts underway to get other services such as [Google Cloud Platform](https://cloud.google.com/dataflow/model/pipelines) and [AWS Data Pipeline](http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/what-is-datapipeline.html) to adopt this standard?

**Comment by mr-c** [comment]
Great question.

It is my understaninding that The [Institute for Systems Biology](http://www.systemsbiology.org/) is building a CWL compliant system on top of Google's infrastructure as part of https://www.systemsbiology.org/research/cancer-genomics-cloud/

Historically Amazon isn't interested in implementing outside standards; however several CWL vendors can use AWS as a backend for executing CWL workflows and jobs.

**Comment by tetron** [comment]
As @mr-c notes, CWL implementations can already run on AWS and GCP using EC2 and GCE.

We have not reached out to the teams that are working on the data pipeline products, but would be interested in doing so if a connection can be made.

**Comment by mr-c** [comment]
Closing for lack of specific steps to take and/or people volunteering to do them.
