### ISSUE TITLE
glob and loadContents when type is non-file

### ISSUE THREAD

**Issue by ntijanic** [common-workflow-language/common-workflow-language#182]
The documentation says loadContents field is only applicable when output type is declared as File. Is this  an error due to inheriting from Binding? It seems that loadContent+outputEval main use is for non-file types.

For example, to output the output of `wc` as integer, one can set the glob to redirected stdout, enable loadContents and cast `$self.content` to integer (the output type would also be marked as integer).

This would assume glob is also available for non-file output types, but its behavior isn't fully defined in this case - do we expect it to match a single file or multiple? Would `$self` be bound to a list of captured files?

**Comment by tetron** [comment]
You're right, this is an error. I'll correct the text.

**Comment by tetron** [comment]
I've refactored the schema a little bit so that loadContents is defined/documented separately for inputBinding and outputBinding (since it does slightly different things).  Please review and close the issue if it's accepted.

**Comment by ntijanic** [comment]
Looks fine now, thanks! Closing.
