### ISSUE TITLE
HPC/Userspace container spec wish list

### ISSUE THREAD

**Issue by kdmurray91** [common-workflow-language/common-workflow-language#184]
This issue contains the wish list of those working on HPC and/or userspace container CWL interaction.

**Comment by kdmurray91** [comment]
-  [ ] Guarantees around network access of `ContainerRequirement`:
        - Disallowed?
        - Not guaranteed?
        - Off by default, specific requirement parameter to allow access?
        - Also options for proxy/auth/misc other network settings

**Comment by tetron** [comment]
Added the following text:

```
An implementation may forbid the tool from directly accessing network
resources.  Correct tools must not assume any network access.  Future versions
of the specification may incorporate optional process requirements that
describe the networking needs of a tool.
```

**Comment by mr-c** [comment]
:+1:

On Thu, Feb 4, 2016 at 4:01 PM Peter Amstutz <notifications@github.com>
wrote:

> Added the following text:
>
> An implementation may forbid the tool from directly accessing network
> resources.  Correct tools must not assume any network access.  Future versions
> of the specification may incorporate optional process requirements that
> describe the networking needs of a tool.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/common-workflow-language/common-workflow-language/issues/184#issuecomment-179852452>
> .
>
-- 
Michael R. Crusoe     CWL Community Engineer     crusoe@ucdavis.edu
<mcrusoe@msu.edu>
Common Workflow Language project    University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe

**Comment by tetron** [comment]
Added the following text:

```
An implementation may forbid the tool from directly accessing network
resources.  Correct tools must not assume any network access.  Future versions
of the specification may incorporate optional process requirements that
describe the networking needs of a tool.
```

**Comment by mr-c** [comment]
The output of this issue is at https://github.com/common-workflow-language/common-workflow-language/wiki/Userspace-Container-Review
