### ISSUE TITLE
move support to biostar, keep this repo for specific spec proposals

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#189]
- [ ] add link to https://www.biostars.org/t/cwl on commonwl.org header

Possibly borrow/adapt icon from http://gmt.genome.wustl.edu/packages/pindel/

![Supported on Biostar](http://gmt.genome.wustl.edu/res/images/btn_get_help.png)

**Comment by tetron** [comment]
Is there a way to subscribe to specific a biostar topic?  If we start sending people there we will need to keep an eye on it.

**Comment by mr-c** [comment]
Two ways: RSS via https://www.biostars.org/feeds/tag/cwl and by adding `cwl` to your 'watched tags' list in your profile

"Watched tags: each user profile now includes the option of listing tags that will trigger email notifications. The user will receive an email when a new post matching any of their watched tags is posted. Users may unsubscribe from these posts at any time."

**Comment by mr-c** [comment]
Closing for now, BioStar's RSS feed is broken (and has been for a while) so I don't want to push this harder
