### ISSUE TITLE
explain how to cite CWL

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#190]
Options:

1. Cite the [2015 BOSC talk](http://f1000research.com/slides/4-278):

 > Amstutz P, Tijanić N, Soiland-Reyes S et al. Portable workflow and tool descriptions with the CWL (Common Workflow Language) [v1; not peer reviewed]. F1000Research 2015, 4(ISCB Comm J):278 (slides) (doi: 10.7490/f1000research.1110021.1)
  ```
@data{de702af8-ea61-47af-aabb-286b2274e1be,
  doi = {10.7490/f1000research.1110021.1},
  url = {http://dx.doi.org/10.7490/f1000research.1110021.1},
  author = {Peter Amstutz; Nebojša Tijanić; Stian Soiland-Reyes; John Kern; Luka Stojanovic; Tim Pierce; John Chilton; Maxim Mikheev; Samuel Lampa; Hervé Ménager; Scott Frazer; Venkat Sai Malladi; Michael R. Crusoe; },
  publisher = {F1000Research},
  title = {Portable workflow and tool descriptions with the CWL (Common Workflow Language)},
  year = {2015}
}
  ```
2. Upload Draft-3 to Figshare & add use that DOI
3. Write quick paper and submit to F1000

**Comment by mr-c** [comment]
Thoughts, all?

Option 1 is easy and already available, but the author list is out of date.

**Comment by mr-c** [comment]
Option 2 has been done:

> Amstutz, Peter; Andeer, Robin; Chapman, Brad; Chilton, John; Crusoe, Michael R.; Valls Guimerà, Roman; Carrasco Hernandez, Guillermo; Ivkovic, Sinisa; Kartashov, Andrey; Kern, John; Leehr, Dan; Ménager, Hervé; Mikheev, Maxim; Pierce, Tim; Randall, Josh; Soiland-Reyes, Stian; Stojanovic, Luka; Tijanić, Nebojša (2016): Common Workflow Language, draft 3. figshare.
https://dx.doi.org/10.6084/m9.figshare.3115156.v1

**Comment by tetron** [comment]
Could you update README.md and/or the draft-3 index page with the DOI?

**Comment by mr-c** [comment]
@tetron https://github.com/common-workflow-language/common-workflow-language/pull/192

**Comment by mr-c** [comment]
@tetron Done.
