### ISSUE TITLE
Provide scattered inputs when using valueFrom on scattered workflow steps

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#193]
When scattering and using valueFrom on a workflow step, the user has access to "inputs" which is the inputs to the workflow step, and access to "self" which is the scattered value of a single parameter, but does not have access to the complete leaf object of the scatter operation.

Suggest adding "scattered_inputs" with this value.

**Comment by ntijanic** [comment]
I would expect `inputs` to be the value after scattering; do we need the pre-scatter values? Relying on those might make certain optimizations impossible.

They might be needed for a pre-scatter transformation (which should act on the whole inputs object), but that's a different use case.

**Comment by mr-c** [comment]
Agreement: `inputs` will be the value after scattering. If users want both they can make another input that isn't scattered.

**Comment by mr-c** [comment]
Fixed in #242
