### ISSUE TITLE
exploring CWL's optional type declarations

### ISSUE THREAD

**Issue by ntijanic** [common-workflow-language/common-workflow-language#197]
What would be the consequences of removing all `type` properties from CWL tool and workflow ports?

Since types of all CWL values can be dynamically inferred, removing `type` would:
- Lead to errors for tool outputs that output single files since they would be wrapped in a list.
- Lead to issues with `secondaryFiles` and other properties of `File` type declarations.
- Make certain runs not fail due to type checks (but likely fail elsewhere or give bad results).
- Disable UI tools for entering inputs.

Suppose we wanted to make type declarations optional. We could, for example:
- Introduce a `coerceTo` property to outputBindings (and elsewhere) where one could use e.g. `coerceTo: singleItem` to report a single file on an output port.
- Have the `secondaryFiles`, `streamable` and `fileFormat` be properties of inputs rather than `File` type declarations. I don't think there's a use case for having files with different values for these on the same port.
- Treat all type mismatches as warnings.
- Add fallbacks to UI generation tools in case no type is declared.

Why would we want to do this?

Well, take generics for example. There's currently no way to create a generic GroupBy tool that would take any list and a criteria (e.g. an expression) and produce a list of lists (or list of groups). This can be solved by introducing actual generics, but this seems like overkill.

Another reason is compatibility with dynamically typed systems. These don't need to be workflow systems - we could have automatic CWL descriptor generation from functions in languages like Python.

Also, it would make hello worlds slightly less verbose :)

What do you think?

**Comment by ntijanic** [comment]
Actually, my bad - type declarations **are** optional. It's just confusing me due to points 1) and 2) above (output type determining behaviour of glob matching and declaration of secondaryFiles and such on the type) and the `Any` type not including `null`.

**Comment by mr-c** [comment]
@ntijanic Is there more to explore with this issue or should it be closed?

**Comment by mr-c** [comment]
Closing for lack of follow up
