### ISSUE TITLE
Website & other documentation plan

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#203]
- [ ] teach schema_salad to generate ReStructuredText
- [ ] Move static content into plain RST
- [ ] Set up Sphinx to render the website
- [ ] Move hosting from GitHub pages to readthedocs.org
- [ ] Pay 3rd party to create a custom Sphinx theme to complement the logo

**Comment by jmchilton** [comment]
I'd like it if the were targets for individual ``Field``s in the following document - so I could link to them directly in a downstream "user guide"-style I am writing. The closest I can get I think is http://www.commonwl.org/draft-3/CommandLineTool.html#CommandLineTool currently. Is this the right place for that request?

**Comment by mr-c** [comment]
@jmchilton yes, thank you

**Comment by mr-c** [comment]
For @bede Currently documentation is generated using https://github.com/common-workflow-language/schema_salad/blob/master/schema_salad/makedoc.py

**Comment by agjohnson** [comment]
@mr-c Following up on what we talked about for the static site and theme, I put together an estimate for our hours converting the static site to a Sphinx project. Gist is here:

https://gist.github.com/agjohnson/1380b0056c5306ca1e852c77d3cc1d62

This work would address all but the first item in this ticket, "teach schema_salad to generate ReStructuredText". Also probably outside the scope of this work would be writing new content for the front page, if the static site should have a stronger marketing focus. That's something that can easily be dropped into rST afterwards however.

**Comment by tetron** [comment]
FWIW existing content is using Markdown, so automatic conversion of Markdown -> RST will be necessary.

**Comment by samuell** [comment]
Someone pointed me to [mkdocs](http://www.mkdocs.org/), which allows writing docs in markdown, and even has a readthedocs like theme. Might be too simple for CWL needs, but will probably use it myself for some projects and just wanted to let you know it exists.

**Comment by mr-c** [comment]
The plan holds for the main website and the specification. For the user guide we are trying out a Carpentry style approach at https://github.com/common-workflow-language/user_guide/

**Comment by mr-c** [comment]
Website development and issues have moved to https://github.com/common-workflow-language/cwl-website/
