### ISSUE TITLE
clarify $(..) vs ${...}

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#206]
It isn't obvious when to use one or the other in the current spec: http://www.commonwl.org/draft-3/CommandLineTool.html#Expressions

**Comment by mayacoda** [comment]
Just a sentence describe how each will be evaluated should be sufficient. The ECMAScript specification is pretty obtuse.

`${...}` will be translated to `(function() { ... })()`
`$(...)` will be evaluated as an expression.

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-language/cwl-v1.2/pull/123
