### ISSUE TITLE
Reduces constraints on platforms for conformance tests

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-language/common-workflow-language#208]
I would prefer if two things were eliminated from the conformance tests - these are both things I could lie about and produce faked results but I want to reduce what the spec implies platforms will do.

 - [ ] Certain tests just test command-line generation without actually real data being available it seems - Galaxy doesn't have the ability to say "this is what the command-line would be" - I could upload fake data, run a job, let it fail, and then collect the results but it doesn't seem worth adding that just to say I can pass a test. E.g. 

```
- args: [bwa, mem, -t, '4', -I, '1,2,3,4', -m, '3', draft-3/rabix/tests/test-files/chr20.fa,
    draft-3/rabix/tests/test-files/example_human_Illumina.pe_1.fastq, draft-3/rabix/tests/test-files/example_human_Illumina.pe_2.fastq]
  job: draft-3/bwa-mem-job.json
  stdout: output.sam
  tool: draft-3/bwa-mem-tool.cwl
  doc: General test of command line generation
```
 - [ ] Certain tests test exact command lines - I'd prefer if they allow the file paths to just check something about the inputs - such as a digest.

I guess it is on me to implement these changes - but I want to formalize a discussion on these points first. The way the conformance tests operate now - would seem to imply that platforms are going to operate on the data in-place - which I don't think was an intention of the spec.

**Comment by tetron** [comment]
I would like to get rid of the "--conformance-test" mode since it is an awkward special case.  The idea I was toying with was to replace them with trivial jobs which do something like this:

cmdline.py bwa mem -x -y -z

```
import json
import sys
sys.stdout.write(json.dumps(sys.argv))
```

The input files can be stubbed out as well to refer to valid files.

The reason for having these tests in the first place is that the input binding of parameters to command line options is a little bit complex but intended to have guaranteed deterministic order.

**Comment by tetron** [comment]
@jmchilton working on this one now -- the special magical tests of command line generation are now just regular tests which copy their command line to the output.  This should make it easier to deal with.

**Comment by jmchilton** [comment]
Closing - thanks a bunch of addressing these - I'll open a new issue with additional specifics in the future.
