### ISSUE TITLE
add `cwl:env` field to input documents

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#211]
Specific use case: setting the Java classpath to make an existing installation of a tool available:

```
"cwl:env":  {
    "CLASSPATH": "/usr/share/java/trimmomatic.jar"
}
```

This would eliminate the need to hard code paths in tool definitions for Java tools, as discussed in https://github.com/common-workflow-language/workflows/issues/78#issuecomment-217117284

**Comment by tetron** [comment]
I don't think this is necessary with #210:

```
"cwl:requirements": {
  "EnvVarRequirement": {
     "CLASSPATH": "/usr/share/java/trimmomatic.jar"
  }
}
```

Although with the requirement precidence rules, a more specific `EnvVarRequirement` will override it.

**Comment by mr-c** [comment]
Nevermind, @tetron pointed out that this can be specified using https://github.com/common-workflow-language/common-workflow-language/issues/210
```
"cwl:requirements": {
  "EnvVarRequirement": {
     "CLASSPATH": "/usr/share/java/trimmomatic.jar"
  }
}
```
