### ISSUE TITLE
SecondaryFiles, streamable and format should not be assignable to type record and enum

### ISSUE THREAD

**Issue by mayacoda** [common-workflow-language/common-workflow-language#215]
The draft-3 specification states that [CommandInputRecordSchema](http://www.commonwl.org/draft-3/CommandLineTool.html#CommandInputRecordSchema), [CommandInputEnumSchema](http://www.commonwl.org/draft-3/CommandLineTool.html#CommandInputEnumSchema), [InputRecordSchema](http://www.commonwl.org/draft-3/CommandLineTool.html#InputRecordSchema) and [InputEnumSchema](http://www.commonwl.org/draft-3/CommandLineTool.html#InputEnumSchema) have the fields `secondaryFiles`, `streamable` and `format`. These fields are only possible for `type: File` or `items: File` which types record and enum are not. They should be removed from the specification.

**Comment by mr-c** [comment]
Fixed in #232
