### ISSUE TITLE
Missing name field for SchemaDefRequirement types

### ISSUE THREAD

**Issue by mayacoda** [common-workflow-language/common-workflow-language#216]
SchemaDefRequirement types ([InputRecordSchema](http://www.commonwl.org/draft-3/CommandLineTool.html#InputRecordSchema), [InputArraySchema](http://www.commonwl.org/draft-3/CommandLineTool.html#InputArraySchema), and [InputEnumSchema](http://www.commonwl.org/draft-3/CommandLineTool.html#InputEnumSchema)) should have the `name` field. It exists in the [schema-def example](https://github.com/common-workflow-language/common-workflow-language/blob/master/draft-3/draft-3/schemadef-type.yml), but not in the documentation.

**Comment by tetron** [comment]
Will be fixed in #636

**Comment by wgerlach** [comment]
This seems related: I noticed that, according to the documentation, InputRecordSchema and InputEnumSchema have a "name" field, but InputArraySchema has not. Is this a bug in the documentation ?

**Comment by mr-c** [comment]
@wgerlach That is not a bug, in my opinion

**Comment by wgerlach** [comment]
ok, thanks!

**Comment by wgerlach** [comment]
And how about CommandOutputEnumSchema ? Why would that not have a name while CommandOutputRecordSchema has?

**Comment by mr-c** [comment]
@wgerlach That is an inconsistency that we are fixing in CWL v1.1, yep!

**Comment by mr-c** [comment]
Both https://www.commonwl.org/v1.1.0-dev1/Workflow.html#OutputRecordSchema and https://www.commonwl.org/v1.1.0-dev1/CommandLineTool.html#CommandOutputRecordSchema are still missing the `name` field.
