### ISSUE TITLE
Confusion between CWLType and PrimitiveType in CLT documentation

### ISSUE THREAD

**Issue by mayacoda** [common-workflow-language/common-workflow-language#217]
There are several places where `PrimitiveType` is used instead of `CWLType`. One example is the definition of `items` in [CommandInputArraySchema](http://www.commonwl.org/draft-3/CommandLineTool.html#CommandInputArraySchema), where the items type includes `PrimitiveType` instead of `CWLType`.

Is there any specific reason for this? What is the purpose of `CWLType` if not to include `File` in these cases?

**Comment by mr-c** [comment]
Good catch, `File` is allowed here and the spec is wrong.

Also `string` is redundant as it is a member of `PrimitiveType`.

`string` should be removed and `PrimitiveType` should be replaced with `CWLType`

**Comment by mr-c** [comment]
re: `string` redundancies; @tetron clarifies that these are for URIs or named SchemaDefs

https://gitter.im/common-workflow-language/common-workflow-language?at=5745a9adec10ddbb09da84f6

**Comment by mr-c** [comment]
@mayacoda I have a fix up at #233

you can preview it by checking out that branch and running:

`cwltool  --no-container --outdir=$PWD/common-workflow-language.github.io site/cwlsite.cwl site/cwlsite-job.json` using the latest cwltool
