### ISSUE TITLE
optional:true instead of null type

### ISSUE THREAD

**Issue by stain** [common-workflow-language/common-workflow-language#221]
It was [discussed on gitter](https://gitter.im/common-workflow-language/common-workflow-language?at=574785a0da3f93da6f20b04f) that the use of `null` as a type to indicate optionality is weird, e.g.

```yaml
  type : ["null" , File] 
```

@psaffrey-illumina points out that this means the GUI code first needs to go through the list to find if `null` is in there, in order to render an option under a _Required_ or _Optional_ section. Secondly the GUI needs to go through the list to find if it should be checkbox or textbox or similar - but this time skipping `null` - in most cases the `type` only contains `null` and the actual type.

There's also ambigiuity what this means within a record, where a field with `null` as its type would seem to have to be provided with a `null` value, while instead the field could be left out of the record all together.

So instead I propose a new `optional`:

```yaml
  type: File
  optional: true
```

The `optional` field itself is optional, default being `false` (e.g. required).

**Comment by tetron** [comment]
I think we previously tentatively agreed to this but I can't find an issue for it.  I have no objections to this proposal.

**Comment by tetron** [comment]
Implementation sketch:

* Add `optional` field to `draft-4/Process.yml#Parameter`
* In `cwltool.process.Process.__init__` change this block:
```
                if ("default" in c or c.get("optional")) and "null" not in aslist(c["type"]):
                    c["type"] = ["null"] + aslist(c["type"])
```

**Comment by tetron** [comment]
Also note, unless we eliminate the `null` type entirely we have to continue recognizing `["null", ...]`as meaning optional.

**Comment by pgrosu** [comment]
Even the great [Tony Hoare](https://en.wikipedia.org/wiki/Tony_Hoare) regrets introducing us to null :)  Optional would probably be more natural, but the evaluation rules I'm slowly stitching together have that intrinsically - so I'm fine either way:

```
// CommandLineBinding: arguments function
eval( arguments-fun, ListOf(arguments) )

arguments-fun -> prefix-fun

// CommandLineBinding: prefix function
eval( prefix-fun, ListOf(input) ) -> ListOf(input)

prefix-fun = ( ListOf(input) ) -> { 
                 for input in ListOf(input) {
                   match input.type
                     string? -> updateInput( input.prefix + eval(input) )
                     number? -> updateInput( input.prefix + eval(input) )
                     boolean? -> (true == eval(input)) -> updateInput( input.prefix )
                     array? -> itemSeparator? -> updateInput( map( itemSeparator, input.prefix + array )) : 
                                                 updateInput( input.prefix + map( itemSeparator, array )) 
                     object? -> updateInput( input.prefix + eval(object) )
                 }	
               }
```

**Comment by denis-yuen** [comment]
if the tooling continues to recognize null as meaning optional, it will probably need to define precedence clearly and/or die quickly on a mismatch
i.e. how should tooling treat 
```
type : ["null" , File] 
optional: false
```

**Comment by stain** [comment]
as `optional: false` is the default value for `optional`, that would be the same as

```yaml
type: ["null", File]
```

meaning that `null` is a permitted value - but the containing field is required.

**Comment by mr-c** [comment]
Fixed by the DSL; optional can now be represented by appending a question mark `type: string?` or the classic way `type: [ "null", string ]`
