### ISSUE TITLE
example in 2.3 of gentle intro fails w reference implementation

### ISSUE THREAD

**Issue by vjcitn** [common-workflow-language/common-workflow-language#225]
following

http://www.commonwl.org/draft-3/UserGuide.html#Returning_output_files

with text files

tar.cwl:
---------
cwlVersion: cwl:draft-3
class: CommandLineTool
baseCommand: [tar, xf]
inputs:
  - id: tarfile
    type: File
    inputBinding:
      position: 1
outputs:
  - id: example_out
    type: File
    outputBinding:
      glob: hello.txt

tar-job.yml:
---------------
tarfile:
  class: File
  path: hello.tar

%vjcair> cwl-runner tar.cwl tar-job.yml
/Users/stvjc/anaconda/bin/cwl-runner 1.0.20160531173804
[job tar.cwl] /Users/stvjc/Research/CWL$ tar \
    xf \
    /Users/stvjc/Research/CWL/hello.tar
Error while running job: Error validating output record, missing required field `example_out`
 in {}
[job tar.cwl] completed permanentFail
Final process status is permanentFail
Workflow error, try again with --debug for more information:
  Process status is ['permanentFail']

**Comment by pgrosu** [comment]
Hi Vince,

It's funny, we keep meeting each other in different places :)  Welcome to CWL!  Just out of curiosity, do your cwl and yaml files look exactly like the following, since yaml is nit-picky about that - you can ignore the dollar-signs as I copied it directly from PuTTY (also in Github you can keep exact formatting of pasted text between triple backtick, here's a [link to a guide](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)) :

```
$ cat tar.cwl
cwlVersion: cwl:draft-3
class: CommandLineTool
baseCommand: [tar, xf]
inputs:
  - id: tarfile
    type: File
    inputBinding:
      position: 1
outputs:
  - id: example_out
    type: File
    outputBinding:
      glob: hello.txt
$
$ cat tar-job.yml
tarfile:
  class: File
  path: hello.tar
$
```

The output should look something like this:

```
$ touch hello.txt && tar -cvf hello.tar hello.txt
$ ~/bin/cwltool tar.cwl tar-job.yml
/home/pgrosu/.local/lib/python2.7/site-packages/cwltool-1.0.20160505204700-py2.7.egg/cwltool/__main__.pyc 1.0.20160505204700
[job tar.cwl] /home/pgrosu/me/cwl/vince$ tar xf /home/pgrosu/me/cwl/vince/hello.tar
Final process status is success
{
    "example_out": {
        "size": 0,
        "path": "/home/pgrosu/me/cwl/vince/hello.txt",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "class": "File"
    }
}
$
```

~p

**Comment by vjcitn** [comment]
I recopied your text and also used cwltool instead of cwl-runner and it
fails in the same way.  Is this sort of error message likely to come from
formatting errors?  I notice that I am not using the same version of
cwltool as you.

%vjcair> cwltool tar.cwl tar-job.yml

/Users/stvjc/anaconda/bin/cwltool 1.0.20160531173804

[job tar.cwl] /Users/stvjc/Research/CWL$ tar \

    xf \

    /Users/stvjc/Research/CWL/hello.tar

Error while running job: Error validating output record, missing required
field `example_out`

 in {}

[job tar.cwl] completed permanentFail

Final process status is permanentFail

Workflow error, try again with --debug for more information:

  Process status is ['permanentFail']

%vjcair> cwltool --version

/Users/stvjc/anaconda/bin/cwltool 1.0.20160531173804

**Comment by pgrosu** [comment]
Hi Vince,

I created a gist location of the two files, and reinstalled and ran `cwltool` to show all the steps.  `cwlrunner` is basically a wrapper for `cwltool`.  The version updates through on the installation, thus this should be the latest-and-greatest :)  Below I will demonstrate by calling directly the `cwltool` package with the two input files - I am using Python 2.7.11:


```Bash

$ git clone https://github.com/common-workflow-language/cwltool.git
$ cd cwltool && python setup.py install --user
$ cd cwl-runner && python setup.py install --user
$ cd ../..

$ wget https://gist.githubusercontent.com/pgrosu/dfd36fba955210c86e6c940db5cf9b73/raw/564ab07f56673e2c2b4e1c491710a0c92d96d6e0/tar-job.yml

$ wget https://gist.githubusercontent.com/pgrosu/dfd36fba955210c86e6c940db5cf9b73/raw/564ab07f56673e2c2b4e1c491710a0c92d96d6e0/tar.cwl

$ touch hello.txt && tar -cvf hello.tar hello.txt
$ python -m cwltool tar.cwl tar-job.yml
/home/pgrosu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py:1246:
UserWarning: /home/pgrosu/.python-eggs is writable by group/others and vulnerabl
e to attack when used with get_resource_filename. Consider a more secure locatio
n (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
/home/pgrosu/.local/lib/python2.7/site-packages/cwltool-1.0.20160531112326-py2.7
.egg/cwltool/__main__.pyc 1.0.20160531112326
[job tar.cwl] /home/pgrosu/me/cwl/vince$ tar \
    xf \
    /home/pgrosu/me/cwl/vince/hello.tar
Final process status is success
{
    "example_out": {
        "size": 0,
        "path": "/home/pgrosu/me/cwl/vince/hello.txt",
        "checksum": "sha1$da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "class": "File"
    }
}
$
``` 

Let me know if it helps.

Thanks,
Paul

**Comment by vjcitn** [comment]
Thank you Paul, I now see what the problem was.  There was a file called

cwl.output.json

in the folder where I was using cwl-runner and that triggered the error.
When that file is removed, the job runs fine.

**Comment by pgrosu** [comment]
Ah yes, the full CWL specification has more information about this here:

http://www.commonwl.org/draft-3/CommandLineTool.html#Output_binding

Glad to hear it all worked out in the end :)

Thanks,
~p

**Comment by mr-c** [comment]
Hello @vjcitn and welcome to the CWL project and thank you for letting us know about your issue.

I see that @pgrosu provided some great peer support so I'm going to close this. Please don't hesitate to contact us again in the future and thanks for using the CWL standards and tools!
