### ISSUE TITLE
arvbox: Pipeline fails with pip/python errors?

### ISSUE THREAD

**Issue by mattdmem** [common-workflow-language/common-workflow-language#229]
I have arvados in a box running and when trying to run a really simple pipeline (which just echo's hello), the pipeline fails and I get the following messages in the log:

`09/06/2016 16:27:13	localhost	1	task-print	0	Command /tmp/crunch-job-work/.arvados.venv/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-y1Mkh1/pycurl/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Q4XQwT-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/crunch-job-work/.arvados.venv/include/site/python2.7 failed with error code 1 in /tmp/pip-build-y1Mkh1/pycurl
09/06/2016 16:27:13	localhost	1	task-print	0	Storing debug log for failure in /tmp/crunch-job-task-work/localhost.1/.pip/pip.log
09/06/2016 16:27:13	localhost	1	task-print	0	cat: /tmp/crunch1/src.log: No such file or directory
09/06/2016 16:27:13	localhost	1	task-print	0	/tmp/crunch-job-work/.arvados.venv/bin/pip --quiet install -I /tmp/crunch1/opt/python failed (): exit 1 signal 0 at - line 239.
09/06/2016 16:27:14	localhost	1	task-dispatch	0	child 15652 on localhost.1 exit 111 success=false
09/06/2016 16:27:14	localhost	1	task-dispatch	0	failure (#3, temporary) after 26 seconds
09/06/2016 16:27:14	localhost	1	task-dispatch	0	task output (0 bytes):
09/06/2016 16:27:14			crunch		status: 0 done, 0 running, 1 todo
09/06/2016 16:27:14			crunch		wait for last 0 children to finish
09/06/2016 16:27:14			crunch		Freeze not implemented
09/06/2016 16:27:15			crunch		collate
09/06/2016 16:27:15			crunch		collated output manifest text to send to API server is 0 bytes with access tokens
09/06/2016 16:27:17			crunch		job output d41d8cd98f00b204e9800998ecf8427e+0
09/06/2016 16:27:18			crunch		finish`

the pipeline looks like this:
`{
 "href":"/pipeline_templates/2m5b1-p5p6p-weimjgvp4hs1cnu",
 "kind":"arvados#pipelineTemplate",
 "etag":"qg8i3ofech9hnayal65u9c9u",
 "uuid":"2m5b1-p5p6p-weimjgvp4hs1cnu",
 "owner_uuid":"2m5b1-tpzed-hs81igix15z88ir",
 "created_at":"2016-06-09T14:59:55.320505000Z",
 "modified_by_client_uuid":"2m5b1-ozdt8-fs12c73l29f9auk",
 "modified_by_user_uuid":"2m5b1-tpzed-hs81igix15z88ir",
 "modified_at":"2016-06-09T15:25:32.051258000Z",
 "name":"1st coupel of pipleine steps",
 "components":{
  "bwa-aln-r1-l1":{
   "script":"run-command",
   "script_version":"master",
   "repository":"arvados",
   "script_parameters":{
    "command":[
     "echo",
     "hello"
    ],
    "task.stdout":"test"
   },
   "runtime_constraints":{
    "docker_image":"sdgs/pipelinev1",
    "arvados_sdk_version":"master"
   }
  }
 },
 "description":null
}`

**Comment by mr-c** [comment]
Hello @mattdmem. I'm sorry to hear that you're having issues with Arvados. This repository is just for the CWL standards themselves. The arvados issue tracker is at https://dev.arvados.org/projects/arvados/issues

I'm going to close this issue for now. Please feel free to file any issues you might find with the CWL specifications themselves in the future.

Cheers!
