### ISSUE TITLE
document list/map behaviour

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#237]

**Comment by ivanbatic** [comment]
Does this refer to an ability to define a hash map type for fields?

**Comment by mayacoda** [comment]
@ivanbatic, yes I think that what this is referring to. A list of "identifiable" items (each item has a unique id under the id field) can be written as a map of `{id: item}`.

Just a question, is the id field then removed from the item if the list is represented as a map?

For example, would the following array:
```
inputs: [
    {"id": "a", "prop": "value1"},
    {"id": "b", "prop": "value2"}
]
```
be represented as a map like this:
```
inputs: {
    "a": {"id": "a", "prop": "value1"},
    "b": {"id": "b", "prop": "value2"}
}
```
or like this?
```
inputs: {
    "a": {"prop": "value1"},
    "b": {"prop": "value2"}
}
```

**Comment by mr-c** [comment]
The second way
Pe 24 iun. 2016 8:36 a.m., "Maya Nedeljkovich" <notifications@github.com> a
scris:
