### ISSUE TITLE
Versioning issues

### ISSUE THREAD

**Issue by denis-yuen** [common-workflow-language/common-workflow-language#264]
Some issues that would probably aid in debugging later.

1. The 1.0 release seems to be missing a release/tag, see https://github.com/common-workflow-language/common-workflow-language/releases which lists draft-3 as the latest release
2. Unless I missed it, it isn't clear which versions of cwltool are compatible with draft-3 and which versions are compatible with v1. Same issue here https://github.com/common-workflow-language/cwltool/releases

**Comment by mr-c** [comment]
Thank you @denis-yuen for your report, I appreciate it!

1. I've made a proper GitHub release for v1.0 https://github.com/common-workflow-language/common-workflow-language/releases/tag/v1.0

2. You are correct, cwltool's compatibility with the CWL specifications could be better documented. However we are currently in a continuous deployment mode with retained backwards compatibility, so our current advice to is always use the most recent release; or pin a recent know-working release and only update as needed. This is likely to change over the next few months now that v1.0 has been released. I've moved this issue to the cwltool repository: https://github.com/common-workflow-language/cwltool/issues/141
