### ISSUE TITLE
InitialWorkDirRequirement instead of CreateFileRequirement in docs

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [common-workflow-language/common-workflow-language#269]
In this document: http://www.commonwl.org/v1.0/UserGuide.html
Code references to `InitialWorkDirRequirement` are preceded by descriptions of `CreateFileRequirement`. It's a bit confusing. Also, the examples for `InitialWorkDirRequirement` could be made a bit more clear.

**Comment by mr-c** [comment]
Thank you @SolomonShorser-OICR for your report. You are correct, this is an error.

**Comment by mr-c** [comment]
This appears to have been fixed.
