### ISSUE TITLE
CommandLineBinding separate vs join

### ISSUE THREAD

**Issue by mayacoda** [common-workflow-language/common-workflow-language#273]
This is a syntactical problem. I think this came up in discussion at some point, but I can't find the corresponding issue for it. 

The problem is that `separate` defaults to `true` if it is not included, and since it is not a required field, this gets very confusing.

```javascript
"inputBinding": {
    "prefix": "x"
}

// because the default for separate is true, falsy values and false are not the same
inputBinding.separate //evaluates to undefined, which is falsy

//instead one must explicitly check that field is NOT false
inputBinding.separate != false // evaluates to true
```

`separate` is an unnecessary idiosyncrasy that causes confusion for implementers and can be syntactically rectified.

It makes much more sense to call the field `join` and have it default to `false`. Default behavior is not including the field. Semantically there would be no change.

**Comment by mr-c** [comment]
Thank you @mayacoda for the report.

The other option would be to direct implementation to set the `separate` field explicitly to `true` or `false`. This would be a minor correction instead of renaming the field.

**Comment by mayacoda** [comment]
@mr-c, you're absolutely right. I realize my suggestion was probably too aggressive and would not be backwards compatible.

**Comment by mr-c** [comment]
@mayacoda In the spec the value of `separate` is `true` by default, so if that isn't set then that is an implementation error. Are you seeing it unset in `cwltool?

**Comment by mr-c** [comment]
I'm removing this from the `v1.1` milestone as I don't see any specification change needed; feel free to suggest otherwise.

**Comment by mayacoda** [comment]
@mr-c that's fine, I'll close this because there's nothing to change, really. Implementers should just be aware of it.
