### ISSUE TITLE
Expression tools can be run standalone

### ISSUE THREAD

**Issue by StarvingMarvin** [common-workflow-language/common-workflow-language#274]
Expressions tools are so under-documented, that I only figured out today that they exist in the spec.

>  Execute an expression as a Workflow step.

Does this mean that they are illegal outside of the workflow / as a standalone tool, or this is just a suggestion?

Also class is not defined, although from context I can assume it is `ExpressionTool`.

- [ ] One line change to the spec & changelog entry
- [x] no new conformance tests needed

**Comment by mr-c** [comment]
:-)

Yeah, they could use some more documentation.

They could be run by themselves, but you are right that the specification does not say that this is allowed or even required.

**Comment by tetron** [comment]
Expressions tools can be run standalone.  Should be clarified in the spec.
