### ISSUE TITLE
Considering allowing "inputs: Any" and "outputs: Any"

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#284]
In some cases we may want to wrap a tool for which the input or outputs are not easily knowable in advance.  For example, a tool wrapper of a generic tool runner, such as: https://github.com/common-workflow-language/common-workflow-language/pull/278

Without `outputs: Any`, the proposed wrapper describing cwltool is incompatible with the behavior described at https://github.com/common-workflow-language/common-workflow-language/issues/262 which states that output fields not listing in the `outputs` section are not returned.

**Comment by mr-c** [comment]
Since we have no use case I am going to close this issue for now. Happy to discuss it again once we have a user story!
