### ISSUE TITLE
Implement continuous integration and testing

### ISSUE THREAD

**Issue by seandavi** [common-workflow-language/common-workflow-language#29]
It would be a nice addition to include formal testing, test coverage metrics, and continuous integration (perhaps using Travis CI).

**Comment by tetron** [comment]
The package is already built and uploaded automatically on a Jenkins server, so I will have it run tests automatically as well.  I'll put links in the main README and on this issue when its ready.

**Comment by tetron** [comment]
We (Curoverse) are planning to do this, the Arvados project task is https://arvados.org/issues/5548

**Comment by tetron** [comment]
There is now a Jenkins job that runs tests, builds and uploads packages, and builds and uploads Docker images:

https://ci.curoverse.com/job/common-workflow-language/

**Comment by mr-c** [comment]
Huzzah, thanks!
