### ISSUE TITLE
/tmp/tmp2voCcb，what is this directory? can i denote to my work directory 

### ISSUE THREAD

**Issue by luozhhub** [common-workflow-language/common-workflow-language#298]
cwl-runner bwa.cwl bwa-job.yml 
/simm/home/luozhihui/program/python_2.7.7/bin/cwl-runner 1.0.20160829211335
[job bwa.cwl] /tmp/tmp2voCcb$ bwa \
    aln \
    /tmp/tmp7yxnhP/stgb2cf72ae-9dbe-4ef9-bfa6-7be4b16adc71/hs37d5.fa \
    -b0 \
    -t \
    8 \
    /tmp/tmp7yxnhP/stg8f095162-21d8-4300-ac76-6ecc5927dda9/TCGA-AA-A03J-01A_1.bam > /tmp/tmp2voCcb/3c13c8d7-f0dd-4cd2-97c1-65524fa41ccf
[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 38bp reads: max_diff = 3
[bwa_aln] 64bp reads: max_diff = 4
[bwa_aln] 93bp reads: max_diff = 5
[bwa_aln] 124bp reads: max_diff = 6
[bwa_aln] 157bp reads: max_diff = 7
[bwa_aln] 190bp reads: max_diff = 8
[bwa_aln] 225bp reads: max_diff = 9
[bwa_aln] fail to locate the index
[job bwa.cwl] completed permanentFail
Final process status is permanentFail
Workflow error, try again with --debug for more information:
  Process status is ['permanentFail']

**Comment by mr-c** [comment]
Hello @luozhhub, thank you for using CWL and its reference implementation!

We use the issue tracker of this GitHub repository for proposals about the CWL specifications itself. For general questions we recommend posting to https://www.biostars.org/t/cwl with the `cwl` tag.

The short answer to your question is that the CWL reference implementation run the tools in temporary directories to ensure that you've specified all the inputs. As you saw in this case the BWA index is missing. This can be worked around using the `secondaryFiles` feature. 

I'm going to close this issue; You are very welcome to re-post your question to BioStars along with either a link to where you got `bwa.cwl` from or the contents of `bwa.cwl` & `bwa-job.yml` themselves.

Cheers,
