### ISSUE TITLE
Tag releases in git

### ISSUE THREAD

**Issue by hannes-ucsc** [common-workflow-language/common-workflow-language#30]
Continued from #28 

I would be nice if CWL releases were tagged to give users a way to fall back easily to a previous, known-to-work release. Currently every build gets pushed to PyPi (correct me if I'm wrong), so in a way, every build is a release and tagging them does not make sense since every commit leads to a build (again, correct me if I am wrong). 

Here's what I do: To get stable releases, only selected builds are pushed to PyPi. On master, the package version number has the .devN suffix except when a release is prepared. Then the .devN suffix is removed (as the only change in a commit) and a release build is triggered on CI, the only difference to normal builds being that it pushes to PyPi. The commit that removed the dev suffix is tagged manually and another commit is made to bump the package version to the next dev release (the minor version in incremented and a .dev1 prefix is added).

Anyways, there are a thousand ways to skin this cat. 

BTW: pip supports installing a tagged release directly from Github via

```
pip install git+https://github.com/foo/project.git@1.2.3
```

**Comment by mr-c** [comment]
Thank you @hannes-ucsc for your issue; I agree that the release should be tagged! I've moved this over to the new reference implementation repository and assigned it to myself: https://github.com/common-workflow-language/cwltool/issues/10
