### ISSUE TITLE
Processes can declare they explicitly implement a certain input/output signature

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#31]
Various groups have expressed the desire to be able to define input/output signatures for abstract operations that may be implemented by multiple containers or workflows.  Possible implementation would be a field like "implementsInterface" on a process which references an external resource (by URI?) which defines the input and output signature.

**Comment by mr-c** [comment]
Closing this issue in favor of @tetron own proposed syntax issue #337
