### ISSUE TITLE
London meetup & coworking organization

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#313]
- [x] save the date
- [x] venue
- [x] accommodations
- [x] sponsors
- [x] catering
- [x] agenda
- [x] Invitation letters for those needing a visa

**Comment by StarvingMarvin** [comment]
Invitation letters for those needing a visa?

**Comment by mr-c** [comment]
@StarvingMarvin I think Seven Bridges is taking care of the 7B employee visa letters :-)

Anyone else needing one, please contact me!
