### ISSUE TITLE
Patch specification that steps could also be Map<WorkflowStep.id, WorkflowStep>

### ISSUE THREAD

**Issue by sivkovic** [common-workflow-language/common-workflow-language#322]
We have tests for this in conformance, but in specification steps could only be array<WorkflowStep>.

**Comment by tetron** [comment]
Duplicated in #729 and possibly others, documentation generator fix pending https://github.com/common-workflow-language/schema_salad/issues/167

**Comment by mr-c** [comment]
fixed in https://github.com/common-workflow-language/schema_salad/pull/193
