### ISSUE TITLE
Make explicit that user inputs need to staged/symlinked into an empty directory

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#331]
This is presumed by https://github.com/common-workflow-language/common-workflow-language/blob/b60125ba6c2bb97fbbe01f4dd99a9542c1801f66/v1.0/conformance_test_v1.0.yaml#L789

Should be explained in http://www.commonwl.org/v1.0/CommandLineTool.html#Runtime_environment

**Comment by bogdang989** [comment]
Looks like this is already done.
