### ISSUE TITLE
Directory LoadListing

### ISSUE THREAD

**Issue by ntijanic** [common-workflow-language/common-workflow-language#348]
As discussed on the CWL hangouts, file and directory literals are not quite clearly defined by the spec. I wrote up my understanding of how these should behave to get the conversation going, but I still owe a more formal and cleaner writeup.

### Files

- Files are encoded as objects with `class` property set to `File`. This distinguishes them from regular maps or records (records cannot have a property called `class`). Other properties depend on the context where they show up and whether they are literals or not.
- When specifying inputs to the "root" job (i.e. the workflow to run), it is a CWL recommendation that this be done via the `location` property, which should be a URL. This can also be done using the `path` property (convenient for local runs). It is up to the implementation to decide what to do with additional "derived" properties (size, checksum) - they can be ignored or used to issue an error in case of mismatch. If the `basename` property is specified, this means that file should be staged with that name. The `secondaryFiles` property is a list of file objects (same rules as above apply) that must exist in the same directory as the "master" file; conflict in file names here is a terminal error. If a file object in this context has a `contents` property (and no `path` property), it is a literal and not a reference. Again, this API is a recommendation and used for conformance tests, but implementations can have completely different interfaces.
- In context of CommandLineTool inputs, file values (along with secondary files) should always be staged to have required names on a local filesystem, with `path` properties accessible by the underlying process (e.g. they should be in-docker paths, if process runs in docker). All derived properties should be present in the javascript variables, as per spec. If a file literal was on the input, it should be staged and converted to a local reference first.
- In context of CommandLineTool outputs, glob matching returns file references (all with `path` property) and the derived properties. This can all be modified by `outputEval` or completely worked around with cwl.outputs.json. The end result is that file references on outputs should be specified with the `path` property (and `secondaryFiles` and such, but all derived properties should be ignored), while file literals are specified with the `contents` property and without `path` (if `basename` is not specified, a unique one should be created). If there is a name conflict in secondary files, it is a fatal error. Implementations do not need to serialise literals from these outputs.
- In context of root job outputs, conformance tests expect all literals to be turned to local references and all files to have the `location` property, but this should not be part of the general spec.
- In context of ExpressionTools, file references should be specified via `location` (they have no `path`) and literals only through the `contents` and `basename`. `loadContents` on ExpressionTool inputs behaves the same as on CommandLineTool inputs, though it is meaningless on the outputs.
- ExpressionTools can simply forward file references from inputs to outputs by using the same value for `location`.

### Directories

- Ideally, directories behave consistently with files.
- In context of root inputs, they are specified with `location` or `path` and literals are specified with `basename` and `listing`. References do not have `listing`s, unless `loadContents` is specified on CommandLineTool inputs/outputs or ExpressionTool inputs. If specified, contained file references likely should not have the `contents` preview since that would be huge in most cases.
- In context of CommandLineTool inputs, all directory literals should be recursively staged first and turned to local references, same as files.
- In context of CommandLineTool outputs, they should not be turned to references, same as files.
- In context of root/final outputs, the conformance tests can require them to be turned to local references, but implementations can have different interfaces, same as files.
- ExpressionTools can forward directory references from inputs to outputs, same as files.
- Any name conflicts are terminal error, same as files.

I think the above can be easily formalised in the spec by introducing partially specified files/directories (used in context of outputs by script or root job inputs) and making a clearer distinction between references (including local references through `path`) and literals. I'll try to do that over the next few days.

Thoughts?

- [x] implement in cwltool
- [x] add to spec
- [x] add new conformance tests that exercise this feature

**Comment by tetron** [comment]
`secondaryFiles` can contain subdirectories as well as files.

We might want to tweak `loadContents` to have a couple of listing behaviors, "single level" and "recursive" so it is possible to limit the expansion of directory subtrees.  Alternately we could have a "listing depth" parameter.

**Comment by mr-c** [comment]
From today's chat: we will use `loadListing`, value is an enum (`single`, `recursive`, `false`)

I believe we said that the default is `false`. @tetron @ntijanic ?

**Comment by StarvingMarvin** [comment]
If we want to be backward compatible, we would have to default to recursive.

**Comment by tetron** [comment]
These notes have been revised and added into #410, thanks!

**Comment by mr-c** [comment]
LoadListing needs de-prefixing for v1.1

**Comment by mr-c** [comment]
@tetron and I agree that if a CWL v1.1 executor implements `InlineJavascript` then they must implement `LoadListing` as well; therefore conformance tests for LoadListing will be tagged `inline_javascript`
