### ISSUE TITLE
view.commonwl.org

### ISSUE THREAD

**Issue by stain** [common-workflow-language/common-workflow-language#353]
Could we have a CNAME for `view.commonwl.org` to point to heater.cs.man.ac.uk ? 

Then we can deploy CWL Viewer on https://view.commonwl.org/ rather than http://heater.cs.man.ac.uk:8080/

I'll do the nginx/SSL config (letsencrypt?)

**Comment by mr-c** [comment]
Propagating through DNS now :-)
