### ISSUE TITLE
Question: CWL Release 1.0: Why having both default and valueFrom fields on WorkflowStepInput? 

### ISSUE THREAD

**Issue by BurkovBA** [common-workflow-language/common-workflow-language#358]
Hi, I am working on an implementation of CWL and I don't understand, why would WorkflowStepInput have 2 fields simultaneously: valueFrom and default: http://www.commonwl.org/v1.0/Workflow.html#WorkflowStepInput.

I understand that valueFromallows us to hard-code the value, supplied to a step input, or make it a dynamically evaluatable expression (if we don't want this step to take its input value from workflow input or output of another step). But why would I need default field then, except that it is a legacy field from the times of draft-2?

**Comment by mr-c** [comment]
Hello @BurkovBA, thank you for opening this issue. It is exciting to hear about another CWL implementation in the works!

Your hypothesis that this is left over from draft-2 makes the most sense. I'll let @tetron and @ntijanic chime in with their perspectives.

I support marking as deprecated the use of `valueFrom` with a constant string (which should have been `Any` or `CWLType`) and for removal in v2.0 of this usage altogether..

**Comment by boysha** [comment]
I agree `inputBinding.valueFrom` should not allow a literal in 2.0. If it's set to a literal, any actual input value is ignored for building that command line part which is not intuitive. If `default` is set, value for the command line will change only if actual input value is null.

**Comment by mr-c** [comment]
@boysha I think we are talking about `WorkflowStepInput.valueFrom` here, though `inputBinding.valueFrom` is also a candidate for the same simplification`

**Comment by boysha** [comment]
Oops. But yes - same problem in both cases.

**Comment by tetron** [comment]
The reasoning is that `default` is a literal value to be used when the supplied input parameter is null, while `valueFrom` is an expression to be evaluated after the initial value is determined (either from inputs or `default`).  Without this distinction, you would have to write out something like this every time you wanted default-like behavior:

```
valueFrom: |
${
  if (self == null) {
    return "default value";
  } else {
    return self;
  }
}
```

If you write it this way, "default value" will always override the input value:

```
valueFrom: "default value";
```

**Comment by tetron** [comment]
I would be fine with requiring that valueFrom must contain an expression.  That it permits literal strings is a side effect of the string interpolation behavior.

**Comment by mr-c** [comment]
Thank you @tetron for the clarification. We should add it to the spec or the user guide.

**Comment by BurkovBA** [comment]
@tetron @mr-c 

Thanks for your help!

I wonder, what's the correct implementation of currying of tool input in step (e.g. my tool has a parameter "p-value", which I want to hard-code to 5% for corresponding step of a workflow) - do I leave the corresponding step input `source` empty and let step input pass its `default` to the tool?

**Comment by mr-c** [comment]
@BurkovBA That could work, or you could connect it to a workflow level input that has a default value (and perhaps documentation explaining the reason)

**Comment by BurkovBA** [comment]
@mr-c @boysha @tetron 

Thank you, guys, for help and discussion.
