### ISSUE TITLE
Is there a way to use JavaScript for inputs?

### ISSUE THREAD

**Issue by wshands** [common-workflow-language/common-workflow-language#361]
I would like to use some JavaScript to format arguments to an input file switch. The input files for the switch should be formatted like this in a Docker run command:
--samples"space"foo_L0_R1.fastq.gz,foo_L0_R2.fastq.gz"space"foo_L1_R1.fastq.gz,foo_L1_R2.fastq.gz ...
I am using the following CWL with JavaScript which produces the correct format but incorrectly includes the incorrect array of filenames(see below)
```
...
inputs: 
  samples:                                                                                                                                                                            
    doc: "Absolute path(s) to sample tarballs or paired FASTQ files. FASTQ pairs are comma delimited and each pair is space delimited. Ex: sample1,sample2 sample3,sample4"                
    type: File[]
    inputBinding:
        valueFrom: |                                                                                                                                                                                
          ${   
               var r = [];
               var len = inputs.samples.length;
               for (var i = 0; i < len; i++) {
                 r.push(inputs.samples[i]);
                 if ((i % 2) == 0)
                    r.push(",");
                 else
                    r.push(" ");
               } 
               return r; 
          }
        prefix: --samples
        separate: false
```
CWLTool sets up the following Docker run command portion (tar files will be fastq.gz):
```
--samples \
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
, \
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
\
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
, \
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
\
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
, \
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
\
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
, \
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
\
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
/var/lib/cwl/stg8ff5cb49-62e1-48de-b6fd-409d0d644ef6/NA12878-NGv3-LAB1360-A.tar \
...
```
The JSON input has a list of only 8 files. How can I adjust the CWL to prevent repeating eight files after the JavaScript adds the 8 input files?

**Comment by StarvingMarvin** [comment]
The direct answer o your question is yes, and this is more or less the way you would do it. There are, however, several issues here: one is apparent bug in cwltool (repeated input files) that should be filed separately. The other is that even if input files aren't repeated, you still wouldn't get desired output: 
`separate` means should prefix be separated from argument, not if individual items are separated. That  is specified by `itemSeparator`.

So something like this works with rabix, but still has extra whitespaces with cwltool:

    inputBinding:
        prefix: --samples
        separate: true
        itemSeparator: ""
        valueFrom: |
          ${
               var r = [];
               var len = inputs.samples.length;
               for (var i = 0; i < len; i++) {
                 r.push(inputs.samples[i]);
                 if ((i % 2) == 0)
                    r.push(",");
                 else
                    r.push(" ");
               } 
               return r; 
          }

Having said all this, I would also add that this entire approach seems to me a bit too hacky. What is logically going on is that you have a nested array, and that items of inner arrays should be joined with "," and items of the outer array should be separated by whitespace. This can be expressed in cwl like this:

    inputs:
      samples:             
        type:
            type: array
            items:
                type: array
                items: File
                inputBinding:
                  itemSeparator: ","
        inputBinding:
            prefix: --samples
            separate: true

and the groupin logic can be separated to its own expression tool:

    expression: |
        ${
            var r = [];
            var len = inputs.list.length;
            for (var i = 0; i < len; i++) {
                if ((i % 2) == 0) {
                    var cur = [];
                    r.push(cur);
                }
                cur.push(inputs.list[i]);
            }
            return {out: r};
        }

Though honestly when tested with both cwltool and rabix, I just get whitespace separated list. At this point I'm not sure if I made a mistake crafting cwl, if I'm misunderstanding the spec, or if both implementations have issues with inputBindings in nested arrays.

Complete examples of the things I've tried are in the attachment.
[cwl361.zip](https://github.com/common-workflow-language/common-workflow-language/files/691757/cwl361.zip)

**Comment by mr-c** [comment]
Looks like a `cwltool` issue, so I'm moving this to https://github.com/common-workflow-language/cwltool/issues/612
