### ISSUE TITLE
error in CWLv1.0 Introduction section 2.12 Javascript expressions

### ISSUE THREAD

**Issue by bamuzesc** [common-workflow-language/common-workflow-language#369]
I tried to run the example presented in "A Gentle Introduction to the Common Workflow Language" section 2.12 Javascript expressions (~~http://www.commonwl.org/v1.0/UserGuide.html#Javascript_expressions~~ http://www.commonwl.org/user_guide/13-expressions/)
and I got a persistent error message:  `Syntax error expected '<document start>' but found '<scalar>'`

**Comment by StarvingMarvin** [comment]
I can't reproduce the error. I assume you copy/pasted that snippet to text file: did you check that copy/paste didn't mess with formatting, and that the result is still a valid yaml. If that wasn't the issue, how are you running this example? With what version of (I'll guess) cwltool? Do you have nodejs installed, and what version etc...

**Comment by mr-c** [comment]
I am able to reproduce with `cwltool` 1.0.20170112185927 (schema-salad 2.2.20170111180227
) & `nodejs` v4.6.1.

```
(env) michael@dan:~/debianmed$ cwl-runner --debug expression.cwl empty.yml
/home/michael/debianmed/env/bin/cwl-runner 1.0.20170112185927
Resolved 'expression.cwl' to 'file:///home/michael/debianmed/expression.cwl'
Syntax error expected '<document start>', but found '<scalar>'
  in "file:///home/michael/debianmed/empty.yml", line 2, column 1
Traceback (most recent call last):
  File "/home/michael/debianmed/env/local/lib/python2.7/site-packages/cwltool/main.py", line 415, in load_job_order
    job_order_object, _ = loader.resolve_ref(job_order_file, checklinks=False)
  File "/home/michael/debianmed/env/local/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 469, in resolve_ref
    doc = self.fetch(doc_url, inject_ids=(not mixin))
  File "/home/michael/debianmed/env/local/lib/python2.7/site-packages/schema_salad/sourceline.py", line 146, in __exit__
    raise self.makeError(unicode(exc_value))
RuntimeError: Syntax error expected '<document start>', but found '<scalar>'
  in "file:///home/michael/debianmed/empty.yml", line 2, column 1
```

**Comment by mr-c** [comment]
It looks like the `empty.yml` trick isn't required anymore, so that should be removed from the user guide

**Comment by StarvingMarvin** [comment]
@mr-c `empty.yml` trick *is* required by the cwlrunner interface, but isn't by the cwltool.

**Comment by mr-c** [comment]
@StarvingMarvin Oh! I learned something today -- should we add that to a future release of the spec?

**Comment by StarvingMarvin** [comment]
@mr-c what is "that"? If not requiring inputs file, than bunny already does something different: because it can accept app inputs after `--` on a command line, it won't run if either inputs file or `--` is present.

As for the original issue: the error is en extra `|` symbol on the second line, right?

**Comment by mr-c** [comment]
Seems to work as of `cwltool` v1.0.20180116032016
