### ISSUE TITLE
enable -h/--help to print description for each parameter

### ISSUE THREAD

**Issue by Shenglai** [common-workflow-language/common-workflow-language#370]
Hi!

I apologize if it's a duplicated issue.
I'm wondering if and how I can have each parameter to have a longer description printed by `--help`. Right now `description` or `doc` is only available in the yaml, and `cwltool --help` seems a little unhelpful in terms of using cwl tool/workflow by a person who has limited knowledge of cwl or is just not the owner.

Thanks
Shenglai

**Comment by mr-c** [comment]
Hello @Shenglai, thank you for sharing your request with us.

What sort of output do you want to see? The `doc` field is indeed exposed by `cwltool` when you run `cwltool cwl-description-URI --help`

For example:
```
$ cwltool https://raw.githubusercontent.com/common-workflow-language/workflows/master/workflows/lobSTR/lobSTR-workflow.cwl --help
cwltool 1.0.20170112083836
usage: https://raw.githubusercontent.com/common-workflow-language/workflows/master/workflows/lobSTR/lobSTR-workflow.cwl
       [-h] [--p1 P1] [--p2 P2] --output_prefix OUTPUT_PREFIX --reference
       REFERENCE --rg-sample RG_SAMPLE --rg-lib RG_LIB --strinfo STRINFO
       --noise_model NOISE_MODEL
       [job_order]

positional arguments:
  job_order             Job input json file

optional arguments:
  -h, --help            show this help message and exit
  --p1 P1               list of files containing the first end of paired end
                        reads in fasta or fastq format
  --p2 P2               list of files containing the second end of paired end
                        reads in fasta or fastq format
  --output_prefix OUTPUT_PREFIX
                        prefix for output files. will output
                        prefix.aligned.bam and prefix.aligned.stats
  --reference REFERENCE
                        lobSTR's bwa reference files
  --rg-sample RG_SAMPLE
                        Use this in the read group SM tag
  --rg-lib RG_LIB       Use this in the read group LB tag
  --strinfo STRINFO     File containing statistics for each STR.
  --noise_model NOISE_MODEL
                        File to read noise model parameters from (.stepmodel)
```

By the way, this repository is for the CWL specification itself. Since we are talking about `cwltool`, the reference implementation then we should use https://github.com/common-workflow-language/cwltool/issues

**Comment by Shenglai** [comment]
Oh, that's my bad. Sorry for the wrong place, but thank you for the information! It seems something goes wrong on my side for versioning. I'll close the issue, and thank you again!
