### ISSUE TITLE
GPU Requirement for running

### ISSUE THREAD

**Issue by bpmweel** [common-workflow-language/common-workflow-language#374]
For one of my workflows I need to run it on a GPU. Currently there is no way of expressing this requirement in the docker file.

As discussed with @mr-c

**Comment by StarvingMarvin** [comment]
@bpmweel I guess it's more than just "GPU". It's probably important if it's CUDA or OpenCL, and if adequate drivers are installed and set up. So one issue is requiring this sort of host capability, and the other issue is additional option in Docker requirement to pass host device to the container.

**Comment by bpmweel** [comment]
@StarvingMarvin You are correct the implications for GPU are quite far reaching, this was just a quick issue to remind ourselves that this needs some attention.

1. The host needs to have a gpu. On some platforms this means giving certain options to the scheduler
2. The flavor of the gpu matters in some cases. Do you want nvidia or ati
3. The flavor of the gpu language matters: Cuda libraries, OpenCL libraries etc.
4. Docker requires special attention
   * For nvidia/cuda you need to use nvidia-docker to use the cuda libraries. These cuda libraries in the container need to be the same version as the host system. But that may be just engineering your docker-container correctly.
   * I do not know if ati/opencl require a special docker version

**Comment by mr-c** [comment]
Somewhat related: an ontology that @tetron found for hardware description:
http://daselab.cs.wright.edu/pub2/wop2017-comp-env.pdf
https://raw.githubusercontent.com/mcheatham/computationalEnvironmentODP/master/docs/exampleCompEnv.owl
https://github.com/mcheatham/computationalEnvironmentODP

Not much on GPUs yet.

I know that @nielsdrost has advice on this topic from the grid computing standardization days.

**Comment by mr-c** [comment]
Closing in favor of the generic `HardwareRequirement` in  https://github.com/common-workflow-language/common-workflow-language/issues/587
