### ISSUE TITLE
Valid json generated from invalid cwl

### ISSUE THREAD

**Issue by k-cao** [common-workflow-language/common-workflow-language#387]
## Bug Report
Here is an issue that one of our users found: https://github.com/ga4gh/dockstore/issues/569
Basically, the cwl is invalid as `inputBinding` does not belong under `arguments`; however, it was treated as a valid cwl file and json was generated.

### Expected behaviour
```
...
I'm sorry, I couldn't load this CWL file, try again with --debug for more information.
...
```

### Actual behaviour 
Json generated

### Steps to reproduce the behaviour
cwltool --non-strict --print-pre [varscan.cwl]
Rename the following file to varscan.cwl
[varscan_cwl.txt](https://github.com/common-workflow-language/common-workflow-language/files/794733/varscan_cwl.txt)

### cwltool Version
1.0.20170217172322

**Comment by mr-c** [comment]
Hello @k-cao 

Thank you for sharing your issue. This repository is for the CWL standards themselves. For the CWL reference implementation (`cwltool`), please report issues at https://github.com/common-workflow-language/cwltool/issues/

Checking the documentation for `cwltool --print-pre` we see that:

> --print-pre           Print CWL document after preprocessing

Therefore I think it is reasonable that this use of the reference implementation does not catch the error.

Incidentally, one does get an error report with `cwltool varscan_cwl.txt --help`

```
(env) $ cwltool varscan_cwl.txt --help
/home/michael/cwltool/env/bin/cwltool 1.0.20170217172322
Resolved 'varscan_cwl.txt' to 'file:///home/michael/Documente/varscan_cwl.txt'
Tool definition failed validation:
varscan_cwl.txt:5:1: Object `varscan_cwl.txt` is not valid because
                       tried `CommandLineTool` but
varscan_cwl.txt:144:1:     the `arguments` field is not valid because
                             value is a CommentedMap, expected null or array of <string or
                             Expression or CommandLineBinding>
```

I hope this was helpful.

**Comment by denis-yuen** [comment]
@mr-c  Thanks, this is quite useful. I think we've been relying on `--print-pre` to return certain validation errors and it looks like this will allow us to pass along better error messages. 

@k-cao Please use `cwltool --non-strict --validate` to validate CWL files and pass along the error messages starting with "Tool definition failed validation" on non-zero exit codes (looks like 1). Work with @garyluu and his testing framework to see if there are any existing CWL files on Dockstore that fail this validation and correct them

**Comment by mr-c** [comment]
@denis-yuen Glad to hear it. I'm going to close this issue then :-)
