### ISSUE TITLE
should enums support the ? optionality syntax?

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#393]
Inspired by https://gitter.im/common-workflow-language/common-workflow-language?at=58b573fce961e53c7f7b6902

**Comment by StarvingMarvin** [comment]
I kinda lean against it. I think it's better to just officially support names and use `type: GivenName[]?`

**Comment by mr-c** [comment]
@StarvingMarvin Yes, I created this before I found the `enum` `name` error in the spec https://github.com/common-workflow-language/common-workflow-language/issues/394
