### ISSUE TITLE
name field missing from InputEnum & record

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#394]
Thus preventing use of the `?` shortcut for optionality, and reducing re-use

**Comment by mr-c** [comment]
@tetron points out that
> cwltool de facto allows you to have "name"
A single conformance test has enums with names, but those names aren't referenced elsewhere:
https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/tmap-tool.cwl#L56

Team Rabix, do you support a `name` field for an enum type, and referencing using that name?

**Comment by StarvingMarvin** [comment]
I'll need to test it, but I believe it handles enum names and references the same way it handles record names and other type schema references. Or if it doesn't, it would make sense to do. Can someone construct an example so we can all run it and report what happened?

**Comment by mr-c** [comment]
@StarvingMarvin I do this with the reference implementation succesfully: 
https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/blob/master/tools/InterProScan-apps.yaml
https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/blob/master/tools/InterProScan5.21-60.cwl#L35
And where we import the custom type into the workflow definition: https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/blob/master/workflows/emg-assembly.cwl#L11

**Comment by mr-c** [comment]
Duplicate of https://github.com/common-workflow-language/common-workflow-language/issues/216
