### ISSUE TITLE
Output file in between a running workflow

### ISSUE THREAD

**Issue by akashmdr90** [common-workflow-language/common-workflow-language#414]
```
java -Xmx4g -Djava.io.tmpdir=temp_dir -jar /usr/local/lib/picard/picard.jar ReorderSam INPUT=excapgene1normoutstp7.bam OUTPUT=excapgene1normoutstp8.bam R= ~/ref_genome/sorted/genome_sorted.fa 

``
samtools index excapgene1normoutstp8.bam excapgene1normoutstp8.bai



java -Xmx4g -Djava.io.tmpdir=temp_dir -jar  /usr/local/lib/gatk/GenomeAnalysisTK.jar -T RealignerTargetCreator -R ~/ref_genome/genome_sorted.fa -nt #_of_threads -I excapgene1normoutstp8.bam -o realignment_targets.list
```

Here the reorder sam is outputing excapgene1normoutstp8.bam to temp folder and that file is taken as input by samtools index and it outputs the .bai file which is required for the execution of RealignerTargetCreator which in turn need to take excapgene1normoutstp8.bam but when it is running in workflow it gives error that excapgene1normoutstp8.bam is not found in temp folder. I need some solution to fix this issue. I think if i could output a the excapgene1normoutstp8.bam to my main folder in which i have my CWL and yaml code and taking that as input for both samtool index(Which outputs the .bai file which is required for running the next step RealignerTargetCreator ) and  RealignerTargetCreator would be okay to not break my workflow chain .  So is there any way to output files in between a workflow execution ? or any other fix for this issue is there ?

**Comment by mr-c** [comment]
Hello @akashmdr90 

Thank you for sharing your experience. This repository is for fixing and improving the standard itself.

To best answer your question, can you re-post it to https://www.biostars.org/t/cwl using the `cwl` tag? That'll make it easier for everyone.

Thanks!
