### ISSUE TITLE
Question: generating static diagrams from CWL?

### ISSUE THREAD

**Issue by astewart-twist** [common-workflow-language/common-workflow-language#420]
Are there any standard ways for exporting CWL definitions as svg / png / dot / visio / gliffy / etc ?

**Comment by tetron** [comment]
You can use `cwltool --print-dot`

```
cwltool --print-dot myworkflow.cwl | dot -Tsvg > myworkflow.svg
```

There's also an online viewer:  https://view.commonwl.org/

**Comment by astewart-twist** [comment]
Thanks!!!
