### ISSUE TITLE
C++ Parser

### ISSUE THREAD

**Issue by sarthakpati** [common-workflow-language/common-workflow-language#423]
Hey, is there a library or parser which can be called from applications written in c++?

**Comment by tetron** [comment]
Not yet.  What are you trying to do?

**Comment by sarthakcbica** [comment]
I am thinking of including CWL support on a c++ app I am working on. The app in itself is a collection of difference algorithms connected by a graphical layer and I was wondering if it would be easier to define CWLs for the different apps to make integration (both externally to other applications or as pipelines and internally between the graphical layer) easier.

**Comment by mr-c** [comment]
Hello @sarthakcbica -- that's great to hear! If the applications already have command line interfaces then you can describe them manually using CWL. If they don't have command line interfaces yet then a C++ shim that reads and writes CWL compliant JSON would be useful.

**Comment by sarthakcbica** [comment]
Hi @mr-c thanks for the reply!

The apps have well defined CLIs (laconic/verbose parameter parsing, parameter's data type, parameter's data range, parameter's description) and I would rather prefer to generate the CWL specs automatically rather than to hand-code them. Do you have a library of some sort that I can use?

**Comment by mr-c** [comment]
+1 for well defined APIs :-)

Do you use a particular C++ command line parsing library?

For Python we have programs that generate 80% complete CWL descriptions automatically for scripts that use the Python standard library `argparse` or the popular `click` command line parser.

https://github.com/erasche/argparse2tool

I don't know of any C++ equivalent yet, though others have asked for this.

**Comment by sarthakcbica** [comment]
> +1 for well defined APIs :-)

Thanks!

> Do you use a particular C++ command line parsing library?

Yes, adapted & extended from getopt to be cross-platform. I think it would be nice to have a common command line parsing and CWL writing tool - I'd be more than happy to contribute. The parser I have written already has the capability of writing "config files" which I then use to populate basic UI dialogs. I am guessing this could be adapted to write CWL specs as well?

**Comment by mr-c** [comment]
A C++ library that emits CWL descriptions would be wonderful, yes!

Do you also model your outputs?

Paging @mabraham who also expressed interest in this

**Comment by sarthakcbica** [comment]
So this would be an example of the config file I am writing:

```
:secondParam: %FLOAT% *0.1 to 20* second parameter description line 2 description line 3 description line 4 description line 5
:firstParam: %INTEGER% *1 to 10* first parameter    
:thirdParam: %STRING% *max length = 1024* third parameter which is optional  
```  

**:** is used to delineate the verbose call for parameter, **%** is the parameter's data type (can be float, int, string, file, directory or none right now), **asterick** is used to define the parameter's data range (it is processed as a string for simplicity). After that it is the parameter description, which can be up to 5 lines in the console (all this is automatically formatted for echoHelp, echoUsage and echoVersion for the console output).

**Comment by tetron** [comment]
Another thing to consider would be a docopt-to-cwl converter.  Docopt is already available for a bunch of languages, including C++

https://github.com/docopt

**Comment by mr-c** [comment]
I believe this is fixed by https://github.com/CBICA/CmdParser
