### ISSUE TITLE
parameter references or full expressions should be allowed for inputBinding.position 

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#427]
For example, ordering the steps of [Trimmomatic](http://www.usadellab.org/cms/?page=trimmomatic)

**Comment by tetron** [comment]
That's probably a good idea.  One workaround you can do now is to use `valueFrom` and return an array.

**Comment by mr-c** [comment]
Nice, that + some JS would work.

Galaxy has an interesting solution:

Users specify the what operations and the order is implicit to the order they add them: https://github.com/fls-bioinformatics-core/galaxy-tools/blob/master/tools/trimmomatic/trimmomatic.xml#L121
