### ISSUE TITLE
add #!/usr/bin/env cwl-runner to User guide and its examples

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#436]

**Comment by tobyhodges** [comment]
I have a fix for this, once https://github.com/common-workflow-language/user_guide#7 is merged

**Comment by manu-chroma** [comment]
Since https://github.com/common-workflow-language/user_guide/pull/7 is merged. Can we close this one?

**Comment by tobyhodges** [comment]
I'm afraid that I submitted a separate PR (https://github.com/common-workflow-language/user_guide/pull/11) for this one. I tried to keep https://github.com/common-workflow-language/user_guide/pull/7 as a straight-up transfer of the existing material with very few changes/additions.

**Comment by tobyhodges** [comment]
https://github.com/common-workflow-language/user_guide/pull/11 was merged, so this can be closed now

**Comment by mr-c** [comment]
Great, thanks!
