### ISSUE TITLE
demonstrate use of scicrunch.org to find IRIs for SoftwareRequirement in the user guide

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#437]
Example: https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/blob/master/tools/trimmomatic.cwl#L11

**Comment by tobyhodges** [comment]
I could use the InterProScan example here, too

**Comment by mr-c** [comment]
moved to https://github.com/common-workflow-language/user_guide/issues/5
