### ISSUE TITLE
demonstrate re-usable custom types in the user guide

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#438]
example:
https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/blob/master/tools/InterProScan-apps.yaml
https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/blob/master/tools/InterProScan5.21-60.cwl#L35
And where we import the custom type into the workflow definition: https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/blob/master/workflows/emg-assembly.cwl#L11

**Comment by tobyhodges** [comment]
We need a less biology-specific example for this, ideally one that doesn't place too much of an installation burden on the reader. Perhaps a custom type carrying a list of files to be tarballed?

**Comment by mr-c** [comment]
@tobyhodges I don't mind the user guide being Bio* flavored for now. We can certainly simplify the examples, though. Putting Files inside custom records can get tricky, and that isn't possible with Enums.

**Comment by tobyhodges** [comment]
ok, but...

I'm writing the custom types lesson now, using the IPS example. For input, I'll use the `test_proteins.fasta` file that they use in their [HowToRun guide](https://github.com/ebi-pf-team/interproscan/wiki/HowToRun#interproscan-5-test-run). I notice that the software download is 6GB, which I think is an unfair burden to place on someone to follow the guide, regardless of their background. 

For now, having an example in the UG will be better than having none, but I'll make it a priority to create/find an easier example to follow. Do you know of any other, smaller, packages with similarly well-written CWL descriptions, which we could use to demonstrate custom types?

**Comment by mr-c** [comment]
Oh, we should pick nicer tools to work with, yes :-)

How about https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/blob/master/tools/esl-reformat.cwl & https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/blob/master/tools/esl-reformat-replace.yaml

**Comment by mr-c** [comment]
This has been done, yay!
