### ISSUE TITLE
Doc generator: mark inherited fields in records

### ISSUE THREAD

**Issue by StarvingMarvin** [common-workflow-language/common-workflow-language#44]
I've looked at the code and I have some ideas how it could be done, but didn't wont to complicate things further, so... issue raised :)

**Comment by tetron** [comment]
I had the same thought.  My idea is to state "The following fields are inherited from X..." and link to field in the parent record type.  That should not be too hard to implement.  What do you think?

**Comment by StarvingMarvin** [comment]
Yeah, that would be the idea. I guess at the time you have record type and its fields, you also have its parent so it's possible to query parent if it also has that field (and so on recursively, I guess).  I would have done it myself this morning but that piece of code is already nested couple of levels, so I figured it's better to ask here :) If you have other things to do, I can try doing it myself, but I'll probably also refactor it a bit along the way.

**Comment by tetron** [comment]
Committed, please review and reopen if you have any issues.
