### ISSUE TITLE
dockerPull field in DockerRequirement should pull image updates before running

### ISSUE THREAD

**Issue by adkinsrs** [common-workflow-language/common-workflow-language#457]
I have been running some CWL workflows that utilize the DockerRequirement "dockerPull" field, and when the Docker image in question is not present locally, the field works as intended, pulling the image first before running.  However, if the image is updated in the Docker registry sometime later, the "dockerPull" field will continue to run the local image with no actual attempt to do a "docker pull" for updates.  This requires me to have to do a manual "docker pull" on the command line before invoking the CWL.  Is it possible to have CWL perform an actual "docker pull" every time the workflow is invoked with the "dockerPull" field (to grab the latest image update if available), as opposed to simply doing a "docker run" if the image already exists locally?

**Comment by tetron** [comment]
Hi @adkinsrs, this repository is for the CWL specification.  What you are requesting is an implementation specific behavior.  If you are using the reference implementation `cwltool` could you open an issue on its repository?  https://github.com/common-workflow-language/cwltool

**Comment by adkinsrs** [comment]
Thanks!  Will copy and paste the issue there.  Apologies for putting this in the wrong place.
