### ISSUE TITLE
www.commonwl.org redesign + logo

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#46]
Top page should contain:
- One sentence description
- who is providing support ($/effort)
- use cases with snippets

A logo would be nice as well

**Comment by mr-c** [comment]
I made a logo, enhancements welcome :-)

http://logomakr.com/2xjnRU

**Comment by gaurav-kaushik** [comment]
I'm currently working on some logo designs that we can vote on as a group at a future date. I'll also look into the other items (use cases, support).

**Comment by mr-c** [comment]
For the logo I hired Ștefan Malacu, @stefanmalacu, a local designer at [RubyTribe](http://rubytribe.ro/), the anchor tenant at the co-working space I use here in Cluj. Here is his first iteration:

![cwl-logov1-1](https://cloud.githubusercontent.com/assets/1330696/11716306/8ce8dc6c-9f51-11e5-8bba-763fda2aee7d.jpg)

He explained that this is a combination of the letter shapes and the idea of a workflow. He made a small change to make that more obvious:

![cwl-logov1-2](https://cloud.githubusercontent.com/assets/1330696/11716332/adffcf28-9f51-11e5-94dd-d10ed019edd4.jpg)
(The 'C' and the 'W' are overlapped)

We discussed how this is an abstraction of a workflow, one of the things we describe with the CWL standards.

Another iteration (very quick sketch, just to give the idea) shows how there could be other inputs and outputs to each step:

![cwl-logov1-3](https://cloud.githubusercontent.com/assets/1330696/11716362/045022ce-9f52-11e5-827d-504773212449.jpg)

We further discuss how I conceive of the CWL; that it's main product is the community that has found a way to work together. The social norms and expectations of how to collaborate so that we can freely share, re-mix, fork, and up-stream our contributions. He is familiar with GitHub, forking and so on. We did some sketching together using the shapes that come from the collaboration process and we will meet again next Monday to see what he has come up with next.

**Comment by tetron** [comment]
This is cool!

**Comment by seandavi** [comment]
Who knew that all that thought could go into a logo!  Looks pretty nice.

**Comment by foreveremain** [comment]
<unlurk>

I like the path through the trellis angle - great to see you engaging local talent Mike !

</unlurk>

**Comment by portah** [comment]
:+1:

**Comment by denis-yuen** [comment]
:+1:

**Comment by pgrosu** [comment]
Trippy :)  Superb!

<img width="133" alt="cat" src="https://cloud.githubusercontent.com/assets/6555937/11723465/91f092c8-9f3c-11e5-9895-d8fb59323bd3.png">

**Comment by gaurav-kaushik** [comment]
:+1: He made the letters in the logo work! I really like the second one too.

**Comment by jmchilton** [comment]
:+1: Agreed with all above, this is fantastic.

**Comment by FarahZKhan** [comment]
(y) awesome

**Comment by stefanmalacu** [comment]
Hello everyone,
Great to hear the positive feedback! 

Had a chat with Michael about a second concept, so I'm going to put the result here
No more letter emphasis this time, the idea revolves around nodes, flow and the community.

After deciding on the direction, I will make an example of how the logo can be extended to possible future subprojects to keep the identity and message consistent. 

Happy critiquing! 
Stefan

![cwl-logov2](https://cloud.githubusercontent.com/assets/2734267/11781885/e6b79914-a275-11e5-85db-7ffefc73e16a.jpg)

**Comment by mr-c** [comment]
Thanks, @stefanmalacu ! For the rest of you, you have 22 hours to vote on which direction we should pursue,

[Option A](https://github.com/common-workflow-language/common-workflow-language/issues/46#issuecomment-163618419)
[Option B](https://github.com/common-workflow-language/common-workflow-language/issues/46#issuecomment-164435288)

Please leave a comment below with your vote and other feedback; cheers!

**Comment by satta** [comment]
I really like option A.

**Comment by avilella** [comment]
Albert Vilella - Option B

**Comment by agapow** [comment]
Option B (I can see how clever the first is, but think the second is better graphically)

**Comment by seandavi** [comment]
I agree with @agapow. Option B.

**Comment by bede** [comment]
Option B. Although A is clever and more developed, B seems more intuitive.

**Comment by jmchilton** [comment]
I like the compactness of B, it seems like it might be better on slides, etc... but A is too good. I vote A.

**Comment by hrhotz** [comment]
option B

**Comment by martenson** [comment]
A :+1: 
B feels neutral and I especially like the sharpness of A. Plus the proportions of it stand out (unlike the 'boxed' A)

**Comment by vsmalladi** [comment]
I like option B

**Comment by rvosa** [comment]
B

**Comment by darogan** [comment]
Option B

**Comment by robinandeer** [comment]
I really like the idea of extending the logo to subprojects bc they will be such a big part of CWL - would love to see how that would look! 

I agree with @bede, option B is more intuitive for hinting at what CWL is about, I like **option B** :)

**Comment by portah** [comment]
I think B is simple and obvious, but A requires more mind work. I'd like to have my mind busy - I vote A

**Comment by ewels** [comment]
I know we're meant to be voting and not contributing any more, but I couldn't resist having a super quick play..

![image](https://cloud.githubusercontent.com/assets/465550/11786416/ce8d7a78-a286-11e5-83a4-8b8ffabc0e87.png)

(I liked elements of both logos and couldn't choose).

**Comment by portah** [comment]
A thought about B why would't we get just London's metro/underground map :)

**Comment by jmchilton** [comment]
Lots of pro votes and positivity here - I like that - but in the absence of a clear consensus let me counter with negativity and making the case against B. I think the problem with B is what a lot of people think its strength is - it is obvious. I am fine with it being obvious in certain respects - but my fear with this particular kind of obvious is that it is very on the nose - by using something so clearly a workflow in the logo it is subtly encouraging a certain aesthetic on to implementers of CWL GUIs. Workflows should be represented as graphs, nodes should be circles, edges should be thin and curvy, etc... - I feel like that could stifle innovation (albeit subtly). I'd love to see some non-graph representations of workflows and/or some wildly different representations of graphs.

**Comment by portah** [comment]
:+1:

**Comment by mr-c** [comment]
But @jmchilton, option B isn't a workflow, it is a collaboration diagram! I would argue that the most important aspect of this project is the community that has agreed to work together; to innovate and to find consensus.

[At least it isn't UML :-) ]

**Comment by jmchilton** [comment]
@mr-c Agreed community and getting people to work together is the most important thing we are doing here - and by a wide margin. That said, based on the comments above I think people think it is a workflow not a collaboration diagram. If everyone thinks it is a workflow, it is defacto a workflow despite designer's intent IMO.

**Comment by mr-c** [comment]
@jmchilton, Agreed! Hence the open voting on which design to refine into the first official logo.

**Comment by hmenager** [comment]
Very nice proposals... My vote goes to A!

**Comment by chapmanb** [comment]
I vote for a complicated UML diagram with a giant red CWL flashing on top of it. If that is impossible due to ascetic concerns, then I vote for the graphic on A. I prefer the text on B, only because I'm not a fan of all capitals. Writing it "Common Workflow Language" would be my preference.

**Comment by mdmiller53** [comment]
I liked A better than B but thought @ewels was quite clever also (and certainly has the virtue of spelling it out!)

**Comment by satra** [comment]
i couldn't help but play as well (http://logomakr.com/2GoTz4).

between option A and B, i like the simplicity and sharpness of A, but i like the compactness of B, especially in places where we will simply have to reduce this down to a few pixels, or an icon on the top status bar of a phone!

Overall +1 for B

but i really like @ewels - the one change i would suggest is to put a node at the top of the C, and instead of connecting it from there, to connect it from the bottom node of the C to the top of the W. this also gives it a bit of a cursive look, which fits with the idea of a data flow as well.

**Comment by gaurav-kaushik** [comment]
+1 for A

**Comment by inutano** [comment]
I agree with @jmchilton , +1 for A

**Comment by cjfields** [comment]
+1 for A (both are great though)

**Comment by fjrmoreews** [comment]
+1 for B (I like A too...)

**Comment by stefanmalacu** [comment]
Thank you for the thoughts and contributions! 
I've made versions for black/white usage, and 16x16 favicon size. 

The request was to create a symbol to support the name of the product (which can't be always abbreviated until it's more widely known). The purpose of the symbol is not to imitate something specific 100% (like putting a certain UML diagram in there), but to communicate the underlying values like collaboration, flow, connectedness, and unifying different visions. 

The contributions made by @ewels and @satra are logotypes, or the name standing on its own without other supporting symbols. 
When creating a logotype, at most one letter (or the negative space between 2) should be affected - which would catch attention, and which is recognizable when taken out of context . Otherwise the impact is lost.

Look at FedEx, or these for example
http://netdna.webdesignerdepot.com/uploads/smart_logos/3.jpg
https://s-media-cache-ak0.pinimg.com/236x/b2/f6/78/b2f678a17c4b54d93c7baeb964f68818.jpg
http://www.1stwebdesigner.com/wp-content/uploads/2009/09/typographic-logo-inspiration/killed-typographic-logo-inspiration.jpg
 
If all letters are standing out with a styling of their own, there is no singular point of interest to define the identity, so you can isolate each letter and have a different symbol every time.
So you would have to use all 3 letters at all times (in a 16x16 favicon or mobile icon as well).


![cwl-logoa-versions](https://cloud.githubusercontent.com/assets/2734267/11809743/ac891c06-a331-11e5-8a16-6a4d677f140a.jpg)
![cwl-logob-versions](https://cloud.githubusercontent.com/assets/2734267/11809744/ac8a98ec-a331-11e5-8168-166f0315ad54.jpg)

**Comment by ewels** [comment]
Ace, very cool to see favicon previews. Agree that it's a logotype, disagree that is has to be a single letter _per se_. For me it's the aspect ratio that's important - logo A has about the same aspect ratio as my three letter logotype so also suffers when it's tiny.

I wasn't too keen on B before, but it's growing on me.. My vote goes to +1 for logo B.

**Comment by ewels** [comment]
Playing with a more compact version of my one:

![image](https://cloud.githubusercontent.com/assets/465550/11810314/5d8bc2d8-a32d-11e5-8d9f-663ced76dc66.png)
![cwl_logo_idea2-01](https://cloud.githubusercontent.com/assets/465550/11810321/7193c7e4-a32d-11e5-8950-c05d1f0c607d.png)

Think it looks a bit naff though. Still prefer @stefanmalacu's B.

**Comment by mr-c** [comment]
Thank you everyone for your votes, it is great to see the enthusiasm for the project!

A decision has been made and will be announced at the CWL call later today.

**Comment by mr-c** [comment]
By one vote, option A [red] has won!

Thanks again for the feedback. @stefanmalacu and I will be posting updates and renders as we refine the red cascade with and without the crosshatch shading.

**Comment by mr-c** [comment]
Logo is posted at https://github.com/common-workflow-language/logo and the website redesign will begin in a couple weeks.

**Comment by pgrosu** [comment]
Super-awesome - many thanks Michael and Stefan!

**Comment by stefanmalacu** [comment]
Glad to have contributed! How's the project going @mr-c ?

**Comment by mr-c** [comment]
Plan for the new website:

Static content written in ReStructuredText format. Translate the standards into ReST as well (either via `schema-salad` or teach `schema-salad` to read ReST (with embedded YAML?).

Entire site rendered via sphinx with a custom theme and hosted on a paid readthedocs.org account.

Waiting on funds for the redesign & custom sphinx theme, 2 030 EUR.

**Comment by martenson** [comment]
@mr-c I though Markdown is what cool kids use now (Galaxy is undergoing similar website upgrade using .md with [Metalsmith](http://www.metalsmith.io/))

**Comment by mr-c** [comment]
@martenson I've found the ReST format to be more extensible and it leverages the project's existing investment in the Python community. Those offering their labor are welcome to pitch alternative strategies :-)

**Comment by martenson** [comment]
@mr-c I am merely a commentator (and sometimes voter) :) Good luck and let us know how it goes.
