### ISSUE TITLE
Dealing with conflicting command line arguments

### ISSUE THREAD

**Issue by yejinyou** [common-workflow-language/common-workflow-language#466]
When creating a CommandLineTool with CWL, CWL raises an ArgumentError when the newly-created argument overlaps - has the same name or id - with cwl-runner's command line arguments. For example, the cwl-runner command line has the argument option of ```help [-h]```. When I try to generate another command line tool that takes in the argument ```help``` (so that its argument intakes are also readily visible), CWL raises an ArgumentError. More specifically, the error appears as follows: 
``` 
 File "/usr/lib/python2.7/argparse.py", line 1308, in add_argument
    return self._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1682, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1509, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1322, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python2.7/argparse.py", line 1460, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python2.7/argparse.py", line 1467, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -h/--help: conflicting option string(s): --help 
```

Following is a simple .cwl test file that highlights the error.
_input_arg.cwl_
```
cwlVersion: cwl:draft-3
class: CommandLineTool
baseCommand: []
inputs:
  - id: help
    type: boolean
arguments:
  - shellQuote: false
    valueFrom: -h $(inputs.help)
outputs:
  - id: taskout
    type: File
    outputBinding:
       glob: $(inputs.out)
```

Giving the ```help``` argument a more command-line-specific name (ie. ```input_arg_help ```) deals with the problem. However, it would be nicer if CWL can take in two ```help``` arguments as follows ```cwl-runner -help input_arg_job.cwl -help```  and understand that each argument refers to two different commands.

**Comment by mr-c** [comment]
Hello @yejinyou and thank you for your issue.

Have you tried `cwltool input_arg_job.cwl -- --help` ?

**Comment by mr-c** [comment]
As a reminder: you can always specify any input name using an input job object: http://www.commonwl.org/user_guide/03-input/

**Comment by mr-c** [comment]
@yejinyou If you have further issues I would be happy to continue this discussion on the `cwltool` repository as your issue isn't with the CWL standard itself: https://github.com/common-workflow-language/cwltool/issues
