### ISSUE TITLE
reference implementation install fails

### ISSUE THREAD

**Issue by hmenager** [common-workflow-language/common-workflow-language#47]
I tried a clean install of cwltool today, and it seems to fail because "sandboxjs" lib is missing:

<pre>
~/cwl$ cwltool
Traceback (most recent call last):
  File "/home/hmenager/cwl/bin/cwltool", line 9, in <module>
    load_entry_point('cwltool==1.0.20150525010411', 'console_scripts', 'cwltool')()
  File "/home/hmenager/cwl/local/lib/python2.7/site-packages/pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/hmenager/cwl/local/lib/python2.7/site-packages/pkg_resources.py", line 2321, in load_entry_point
    return ep.load()
  File "/home/hmenager/cwl/local/lib/python2.7/site-packages/pkg_resources.py", line 2048, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/hmenager/cwl/local/lib/python2.7/site-packages/cwltool/main.py", line 3, in <module>
    import draft1tool
  File "/home/hmenager/cwl/local/lib/python2.7/site-packages/cwltool/draft1tool.py", line 4, in <module>
    import sandboxjs
ImportError: No module named sandboxjs
</pre>

any pointers?

**Comment by pgrosu** [comment]
I don't think it's in `master`, but you can download it from this location:

https://github.com/common-workflow-language/common-workflow-language/tree/2d1cfedd66379990aa55ac1174ae7d034b04a450/reference/cwltool

Below is a direct link to the file itself:

https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/2d1cfedd66379990aa55ac1174ae7d034b04a450/reference/cwltool/sandboxjs.py

Hope it helps,
~p

**Comment by hmenager** [comment]
Thank you Paul, I'm just wondering wether it should still be on the master branch or not. it is called only from the draft1tool module, and I guess draft1tool is about draft 1, but the master should now only handle draft2 shouldn't it?

**Comment by hmenager** [comment]
Sorry, I just noticed draft2 also uses sandboxjs, so the problem actually is that sanboxjs module is not in the master branch.

**Comment by tetron** [comment]
Sorry about that, I removed it but had a stale sandboxjs pyc so I didn't realize it broke things.  I will fix it and look into setting up a testing server to catch these things in the future.

**Comment by tetron** [comment]
This should be resolved, can you confirm?

**Comment by hmenager** [comment]
fixed, thanks peter!

**Comment by pgrosu** [comment]
Thanks Peter :)
