### ISSUE TITLE
collect recommended CWL practices

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#470]
Present on a scale of usefulness, more is better, not all are required

- [ ] No `type: string` for names of input or reference files/directories
- [ ] license that allows for re-use by anyone. For example, Apache 2.0
- [ ] attribution for CWL description author(s)
- [ ] List dependencies using short name(s) under `SoftwareRequirement`
- [ ] [SciCrunch](scicrunch.org) identifiers for those dependencies in `https://identifiers.org/rrid/RRID:SCR_NNNNNN` format
- [ ] all `input` and `output` identifiers reflect the conceptual identity. No "foo_input`, `foo_file`, `result`, `input`, `output`, or other uninformative names
- [ ] List of version(s) known to work
- [ ] `format` specified for all input and output `File`s. Bioinformatics tools should use format identifiers from [EDAM](http://edamontology.org/format_1915). See also `iana:text/plain`, `iana:text/tab-separated-values` with `$namespaces: { iana: "https://www.iana.org/assignments/media-types/" }`. [Full IANA media type list](http://www.iana.org/assignments/media-types/media-types.xhtml) (also known as MIME types).
- [ ] for all `inputs` and `output` `File`s that are read or written to in a streaming compatible way (once, no random-access), mark them as `streamable: true`
- [ ] Each `CommandLineTool` description focuses on a single operation even if the (sub)command is capable of more
- [ ] Custom types are defined with one external YAML per type definition for re-use 
- [ ] Top level short `label`
- [ ] If useful, a longer `doc` as well
- [ ] For `type: string`, if there is a fixed list of valid values then use a `type: enum` instead
- [ ] all use of javascript is evaluated for possible elimination or replacement. Manipulating `File` names and paths? Consider using one of the [built in `File` properties](http://www.commonwl.org/v1.0/CommandLineTool.html#File) like `basename`, `nameroot`, `nameext`, …
- [ ] Give the tool description to a colleague at a different institution to test, provide feedback

**Comment by tobyhodges** [comment]
I can start working on this today. What is your preferred method of submission? Via email or a PR?

**Comment by MarkRobbo** [comment]
It would also be nice to have some sort of checker for "workflow quality" which evaluated the checklist and could provide suggestions for improvement. Perhaps this is something which could be integrated into CWLViewer or an idea for the BOSC codefest!

**Comment by mr-c** [comment]
@tobyhodges Yay!

I made a copy of the Software Carpentry repo at https://github.com/mr-c/user_guide (which I was going to move to the c-w-l GitHub organization when it was a bit more mature). So we could use that?

**Comment by tobyhodges** [comment]
Also, can you clarify the attribution point please? Are you referring to including attribution information for the author(s) of the tool description in question? Or citation [for the CWL standard](https://github.com/common-workflow-language/common-workflow-language/blob/master/CITATION)?

**Comment by tobyhodges** [comment]
Ok, I'll submit a Markdown doc as a PR to that repo then.

**Comment by mr-c** [comment]
@MarkRobbo agreed! Previously the plan was that planemo would be this opinionated checker https://planemo.readthedocs.io/en/latest/writing_standalone.html but I'm happy for that to occur in many places.

**Comment by mr-c** [comment]
@tobyhodges attribution for the CWL descriptions themselves. Example at https://github.com/ProteinsWebTeam/ebi-metagenomics-cwl/blob/master/workflows/emg-assembly.cwl#L200

**Comment by tobyhodges** [comment]
line 201 in that description too, right?

**Comment by mr-c** [comment]
@tobyhodges Yes. Also needed, referring to the individual and organizations using identifiers like ORCID

**Comment by mr-c** [comment]
Closing, implemented in https://github.com/common-workflow-language/user_guide/pull/1 and we will refine & expand it later
