### ISSUE TITLE
Format type array in CommandOutputParameter

### ISSUE THREAD

**Issue by sivkovic** [common-workflow-language/common-workflow-language#482]
For output parameters, this is the file format that will be assigned to the output parameter, but format can be an array of strings. Since format in File can be only string, what is the proper behaviour in this case?

**Comment by tetron** [comment]
I don't know.  Any suggestions?

**Comment by mr-c** [comment]
We can
1) Clarify that arrays are valid for the format field in the context of an Output
or
2) Say that the first format is the one assigned (weird, but simple)

**Comment by mr-c** [comment]
@tetron and I agree that we should implement option 1

**Comment by tetron** [comment]
I think that was supposed to be "Clarify that arrays are *not* valid for the format field in the context of an Output" ?  And then tweak the schema so that it is disallowed by validation.

**Comment by mr-c** [comment]
@tetron I fixed my text; agreed

**Comment by tetron** [comment]
Will be fixed in #636
