### ISSUE TITLE
SchemaDefRequirement clarification

### ISSUE THREAD

**Issue by AleksandrSl** [common-workflow-language/common-workflow-language#489]
I'm using http://www.commonwl.org/v1.0/Workflow.html specification and have following questions:

1. What is the meaning of `inputBinding` and `outputBinding` fields in parameters of Workflow?
And if they have no meaning why not remove them?
2. I think that such expressions 
```
map<InputParameter.id, InputParameter.type> | map<InputParameter.id, InputParameter>
```
may  be replaced with 

```
map<InputParameter.id, InputParameter.type | InputParameter>
```

since this is valid:
```
inputs: 
  first: File
  second: int[]?
  third:
    type: File
    label: string
    inputBinding:
      position: 12
``` 
?

3. Why SchemaDefRequirement has `types` - `array<InputRecordSchema | InputEnumSchema | InputArraySchema>` and not 
`array<InputRecordSchema | InputEnumSchema | InputArraySchema | OutputRecordSchema | OutputEnumSchema | OutputArraySchema>` since above it's written 
"This field consists of an array of type definitions which must be used when interpreting the inputs and **outputs** fields. " ?

4. Why current version redirects to draft-3?

5. Why `merge_nested` , `merge_flattened` and ScatterMethod values are written in snake case, while others are in camel case?

**Comment by manu-chroma** [comment]
> Why current version redirects to draft-3?

Can you provide the link for the same? Thanks.

**Comment by AleksandrSl** [comment]
@manu-chroma 
Here it is:
"Current version:

https://w3id.org/cwl/
"

**Comment by AleksandrSl** [comment]
@mr-c  Do you have comments on other points?

**Comment by mr-c** [comment]
re:
> 2. I think that such expressions 
> ```
map<InputParameter.id, InputParameter.type> | map<InputParameter.id, InputParameter>
```
> may  be replaced with 
>
```
map<InputParameter.id, InputParameter.type | InputParameter>
```
I agree, that would be a better way to express it.

**Comment by AleksandrSl** [comment]
@mr-c Is it deliberate that `format` field for ` InputParameter` in workflow has type: `string | array<string> | Expression`
and for `WorkflowOutputParameter` in workflow: `string | Expression`?

**Comment by AleksandrSl** [comment]
@mr-c And it also seems that 
`steps   array<WorkflowStep>`, is in fact `steps   array<WorkflowStep> | map<WorkflowStep.id, WorkflowStep>`

**Comment by AleksandrSl** [comment]
This seems to be valid,
```
arguments:
# Type of alignment_map file to be trimmed
  - id: am_type
    valueFrom: paired
    prefix: -t
    position: 1
```
 but in accordance with specification:
`arguments` -  `array<string | Expression | CommandLineBinding>`

so arguments' elements should not have `id`

**Comment by mr-c** [comment]
`string | expression` is a long standing bug of schema_salad. It should be displayed as just `expression`, yes.

**Comment by mr-c** [comment]
@AleksandrSl And you are correct,

> `steps array<WorkflowStep>`, is in fact `steps array<WorkflowStep> | map<WorkflowStep.id, WorkflowStep>`

**Comment by mr-c** [comment]
Moved to https://github.com/common-workflow-language/common-workflow-language/issues/655
