### ISSUE TITLE
expressionDefs should be more generic

### ISSUE THREAD

**Issue by ntijanic** [common-workflow-language/common-workflow-language#51]
Since we stopped using JS in the spec, it makes more sense for the `expressionDefs` property to be more generic and pass any information to expression engines.

Perhaps we can rename it to e.g. `expressionEngineConfig` or `expressionEngineContext` or such and allow any data to be passed.

**Comment by tetron** [comment]
how about just `engineConfig` ?

**Comment by ntijanic** [comment]
engineConfig sounds good.

**Comment by tetron** [comment]
Committed, please review and reopen ticket if you have any concerns.
