### ISSUE TITLE
loadContents limit too small

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#514]
The limit of 64KiB for loadContents is a bit too small for otherwise reasonable tasks.  Suggest raising the cap to 1 MiB.  Must also specify encoding is UTF-8 text, binary data and alternate encodings are not allowed (alternately, add loadContentsEncoding?)

**Comment by cjllanwarne** [comment]
(sorry that I'm late to the party...) 

Has a `LoadContentsMaxRequirement` been considered?

**Comment by tetron** [comment]
You're not too late!

The main reason this restriction exists is to prevent abuse.  If the workflow can specify its own limit then it can load an arbitrary amount of content.  But maybe that's okay, and the spec needs to say "if the workflow tries to load more data than the implementation / host can handle, it will fail."  Even in v1.0 if you were feeling really mean, you could specify loadContents on a directory containing 100,000 files and the "correct" behavior would be to try and load the first 64k of each file until running out of memory.

I'm open to suggestions.

**Comment by mr-c** [comment]
In CWL v1.2.0-dev5, CWL expressions can create larger `File`s, but the limit for reading remains. Users should create standalone tools/scripts if they need access to more than 64KiB.
