### ISSUE TITLE
Is baseCommand allowed to appear several times in one cwl file ?

### ISSUE THREAD

**Issue by manabuishii** [common-workflow-language/common-workflow-language#515]
https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/inline-js.cwl

This file has two `baseCommand` field in one file.
Is this allowed ?
I can't find much about `baseCommand` in specification .

**Comment by mr-c** [comment]
Hello @manabuishii 

That is not allowed, and that file should not parse correctly. I've opened an issue to fix `cwltool` at https://github.com/common-workflow-language/cwltool/issues/562 and a PR to fix this file at https://github.com/common-workflow-language/common-workflow-language/pull/542
