### ISSUE TITLE
multiple inbound link handling

### ISSUE THREAD

**Issue by ntijanic** [common-workflow-language/common-workflow-language#52]
The spec says we should handle multiple inbound links by making an array, unless all links have List<T> data (where T is the same for all links), in which case arrays should be concatenated.

It's hard to determine if data is of same type, since types can be defined in different places. Perhaps it would be better to always create arrays (so value of a port with N inbound links would be a list with N elements for N>1), and introduce an explicit "merge strategy" property to allow easy concatenation where needed.

**Comment by tetron** [comment]
Committed, please review and reopen ticket if you have any concerns.
