### ISSUE TITLE
Make ENTRYPOINT Handling Explicit

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-language/common-workflow-language#522]
I'd argue against allowing the paradigm discussed [here](https://github.com/common-workflow-language/galaxy/issues/66) of using an empty baseCommand and then passing arguments directly to a Docker image's entrypoint but if we are going to allow it we should be explicit and state that it is allowed and add a test case to implement that behavior. I'd also argue we should hide it behind a Requirement. A test case is included in #492 - though I'd be happy to strip it out if we are going to not allow this behavior.

**Comment by mr-c** [comment]
+1 for making our decision explicit, and I also agree that `ENTRYPOINT` is non portable.

However many existing containers use it as a convenience for command line users, so it would be nice to retain some compatibility with such containers. Could the reference CWL runner (and others) override with a `/bin/sh` and proceed as normal?

**Comment by mr-c** [comment]
Plan (supported by @tetron)
- [ ] Add `DockerRequirement.useEntrypoint` (default `true`) to v1.1 and explain current behaviour. If `DockerRequirement.useEntrypoint: true` is used, the `DockerRequirement` must under `requirements`.
- [ ] have `cwltool` print a warning if it detects a `ENTRYPOINT` without an explicit `DockerRequirement.useEntrypoint: true`
- [ ] Explain this deprecation in the CWL user guide. Explain reasons to use `DockerRequirement.useEntrypoint: false`
- [ ] Make explicit that `ENTRYPOINT`s will always be overridden in CWL v2.0

**Comment by tetron** [comment]
In the interests of making progress on v1.1, I'd like to document the existing de facto ENTRYPOINT behavior and put off introducing new options.

**Comment by mr-c** [comment]
Okay

**Comment by geoffjentry** [comment]
This has been merged into the 1.1 repo
