### ISSUE TITLE
be explicit about how to format an input object file via the optional cwl-runner CLI

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#525]
There are examples of cwl files (e.g. [basename-fields-test.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/basename-fields-test.cwl)) and files that specify their input parameters (e.g. [basename-fields-job.yml](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/basename-fields-job.yml)).

However, I did not find the specification of yml to specify the input parameters.
Where is the specification of how to specify the parameters or am I missing something?

**Comment by mr-c** [comment]
Here we just needed any file, so we re-used an existing CWL description. See https://github.com/common-workflow-language/common-workflow-language/pull/607 for a clarification.

**Comment by tom-tan** [comment]
I mean that there should be a description about how to specify the input parameters in external file.
Currently, [the specification of CommandLineTool](http://www.commonwl.org/v1.0/CommandLineTool.html) describes how to write the definition of the tools, but does not describe how to write the input parameters to be passed to the platform.

It would be nice if there is a description to clarify it. For example:
```
### Running a tool with a platform
The platform must accept a CommandLineTool definition file and a input parameter file that specifies input parameters for the tool.
A input parameter file must be in YAML or JSON format and must contain the object in which its field is an input parameter in the CommandLineTool definition file and its value is a value object for corresponding input parameter.
```

**Comment by mr-c** [comment]
@tom-tan we don't require implementations to expose a command line interface, though that obviously helps for CI and developer usage. For example, many systems are primarily GUI and/or API driven.

However we can add clarifying language around the formal introduction of the `cwl-runner` CLI explaining that the validity of an input object is defined by the `inputs` schema of the associated CWL description.

**Comment by mr-c** [comment]
Some quick notes. The `cwl-runner` interface expects an `input object` a JSON/YAML object that satisfies the input section of the given CWL document. That is, the inputs section of a CWL document can be treated as a schema about a valid form to present the inputs.

Arrays are YAML/JSON arrays.
Records are YAML/JSON maps (no `class: my_record_id`)

Inputs of `type: File` or `type: Directory` must be (in this context) specified in the JSON `{"class": "File", `...`}` or YAML form:

``` yaml
My_file: 
  class: File
  # enough other File fields here to locate or construct the File
  # like either `location` (a local or network available File)  or `path` (local file only)
  # or `basename` +`contents` for `File` literal
```

Arrays of records are arrays of YAML/JSON maps.

While the above is only required for implementors of the optional `cwl-runner` interface, it is the same fundamental format for specifying literal values elsewhere in CWL documents.

It is also the same fornat for the result of `cwl-runner` which should match the `outputs` section of the document. Likewise for the `cwl.output.json` format.

**Comment by mr-c** [comment]
In addition to documenting the above, in the same place we should mention [`cwl:requirements`, `cwl:hints`](https://www.commonwl.org/v1.2/CommandLineTool.html#Requirements_and_hints), and [`cwl:tool`](https://www.commonwl.org/v1.2/CommandLineTool.html#Executing_CWL_documents_as_scripts)

**Comment by GlassOfWhiskey** [comment]
This is somehow related to [this PR](https://github.com/common-workflow-language/common-workflow-language/pull/953).

**Comment by tom-tan** [comment]
Once #953 is merged, we can close this issue.

**Comment by tom-tan** [comment]
I close this issue because #953 was merged and the schema of the input objects is now defined! (Information for readers: it will be appear in CWL v1.3)
Thanks!
