### ISSUE TITLE
Migrate CWL conformance testing off of Rackspace

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#531]
Deadline: December 1st, 2017 (to be safe)

I've contacted http://osuosl.org/request-hosting/ based off of their offer on Twitter

https://support.osuosl.org/SelfService/Display.html?id=29802

Our needs:
2-3 systems the equivalent of Rackspace's "8 GB General Purpose v1"
```
CPU	8 vCPUs
RAM	8 GB
System Disk	160 GB
Network	1.6 Gb / s
Disk I/O	Better
Price	
$0.256 / hr server
$0.04 / hr service
$0.296 / hr total
```
1 system is @mr-c's development node, the others run ci.commonwl.org

Other options for ci.commonwl.org:
- access to a Jenkins-as-a-service like Cloudbees https://www.cloudbees.com/
- again try TravisCI or other CI providers (issue with Docker and run time?)

**Comment by mr-c** [comment]
Estimated Bandwidth Usage: Unknown, minimal

**Comment by mr-c** [comment]
Tagging @ctb as he is the billing contact for this account ­(but shouldn't affect him as long as we spin down and cancel by the deadline)

**Comment by tetron** [comment]
I created https://github.com/common-workflow-language/ci.commonwl.org to act as a backup for the jenkins configuration, but it hasn't been updated.
