### ISSUE TITLE
Compliance test null-expression1-tool.cwl and type Any

### ISSUE THREAD

**Issue by wgerlach** [common-workflow-language/common-workflow-language#540]
Hi,

the compliance test tool (v1.0) in file [null-expression1-tool.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/null-expression1-tool.cwl) expects "Any" type as input. 
In the CWL documentation [Any](http://www.commonwl.org/v1.0/CommandLineTool.html#Any) is defined as "The Any type validates for any non-null value.".
But the input variable for this CommandLineTool in file null-expression1-job.json has value "null".

The CWL-runner runs this example without an error message. Is the error now in the compliance test, in the cwl-runner reference implementation or in the Any specification ?

**Comment by mr-c** [comment]
Hello @wgerlach and thank you for this issue,

Looking at the documentation for three conformance tests we see that their purpose is to 
>  Test default usage of Any in expressions.
https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/conformance_test_v1.0.yaml#L124

> Test explicitly passing null to Any type inputs with default values.
https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/conformance_test_v1.0.yaml#L130

>Testing the string 'null' does not trip up an Any with a default value.
https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/conformance_test_v1.0.yaml#L136

The tool referenced does indeed have a `default` field, which gets applied when `null` is passed in.
https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/null-expression1-tool.cwl#L11

So as far as I can see this is not an error in the compliance test, the reference cwl-runner, nor the specification.

**Comment by mr-c** [comment]
More about `default` from the spec:

> When accepting an input object, all input parameters must have a value. If an input parameter is missing from the input object, it must be assigned a value of `null` (or the value of `default` for that parameter, if provided) for the purposes of validation and evaluation of expressions.

http://www.commonwl.org/v1.0/CommandLineTool.html#CommandLineTool

> field: `default`, type: `Any`, required: `False`, description: The default value to use for this parameter if the parameter is missing from the input object, or if the value of the parameter in the input object is `null`. Default values are applied before evaluating expressions (e.g. dependent `valueFrom` fields).

http://www.commonwl.org/v1.0/CommandLineTool.html#CommandInputParameter

**Comment by wgerlach** [comment]
ah, ok, this makes sense. Thanks!
