### ISSUE TITLE
WorkflowOutputParameter.outputBinding.glob is non-sensical

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#543]
While an argument for could be made for using `loadContents` and `outputEval` from the outputBinding in this context, it isn't part of the conformance suite.

Here, at the workflow output stage, a glob doesn't even make sense. I suggest we remove the glob and discuss if the rest of outputBinding should remain.

**Comment by esanzgar** [comment]
Personally, I have found difficult to deal with arrays of files. It is difficult to filter them between steps, and impossible in the workflow output.

I would suggest a review of the usefulness of filtering with 'glob' in the context or array of files.

For example, assuming output step `sss/cwl_out` is defined as `type: File[]`:
* Filter at step level is done using a `valueFrom` expression:

**Comment by tetron** [comment]
I see what happened.  OutputBinding is marked as abstract, so everywhere OutputBinding appeared schema salad substituted the only concrete class which is CommandOutputBinding.

One of:

1. Push CommandOutputBinding down so it only appears in CommandOutputParameter, get rid of the abstract OutputBinding, no change in Workflow functionality
2. Move loadListing, outputEval up into OutputBinding, make it non-abstract, specialize it in CommandOutputParameter.  Add conformance tests for Workflow output to support loadListing, outputEval
3. Specialize OutputBinding in workflows with a concrete WorkflowOutputBinding, which either does nothing, or supports loadListing, outputEval.

The loadListing, outputEval fields do make sense for output of Workflows and ExpressionTools, so option 2 seems best.

**Comment by mr-c** [comment]
yes, please make `outputEval` and `loadListing` apart of this fix

**Comment by tetron** [comment]
Will be fixed in #660

**Comment by tetron** [comment]
I believe this has been fixed in v1.1, closing issue.
