### ISSUE TITLE
Add the ability to configure step input value without exposing it as workflow port

### ISSUE THREAD

**Issue by ntijanic** [common-workflow-language/common-workflow-language#55]
It would be really useful to be able to "hardcode" some step inputs without exposing them as workflow ports. If they are exposed as inputs with default value, there is no way to distinguish between ports meant to be configured by the "workflow user" and values that are not meant to change.

Having a `default` property on `WorkflowInputParameter` and `WorkflowStepInput` should handle this nicely - if no value is supplied in JobOrder or through data links, input value should be content of `default` or `null`.

**Comment by tetron** [comment]
Committed, please review and reopen ticket if you have any concerns.
