### ISSUE TITLE
No explicit reason to put json contents to Stdout, with `v1.0/bwa-mem-tool.cwl`

### ISSUE THREAD

**Issue by otiai10** [common-workflow-language/common-workflow-language#550]
# Introduction

Hi, I'm now developing my own cwl engine, just to learn how cwl works. It means I need to pass the test command below ↓, right?

```
% ./run_test.sh RUNNER=/bin/path/to/myengine
```

and I have a question about specs of CWL and behavior of `cwltool`

# Question

When I kick

```
% basename `pwd`
common-workflow-language
% git rev-parse HEAD
a83ab96df2bf6036f20ea71f498a60cb7f1db13c
% cd v1.0
% cwltool --quiet v1.0/bwa-mem-tool.cwl v1.0/bwa-mem-job.json
{
    "args": [
        "bwa",
        "mem",
        "-t",
        "2",
        "-I",
        "1,2,3,4",
        "-m",
        "3",
        "chr20.fa",
        "example_human_Illumina.pe_1.fastq",
        "example_human_Illumina.pe_2.fastq"
    ]
}
%
```

It puts out the contents of `cwl.output.json` which is generated by `args.py`, the second argument of command line.

But as checking CWL file, [bwa-mem-tool.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/bwa-mem-tool.cwl), I couldn't guess it's gonna be shown up on stdout (rather than `output.sam`).

How can I expect and implement my engine to put the `cwl.output.json` onto stdout? Is there implicit rule for that?

**Comment by otiai10** [comment]
Ah... sorry, I missed this section of [**Output binding**](https://github.com/common-workflow-language/cwltool/blob/master/cwltool/schemas/draft-3/invocation.md#output-binding)

> If the output directory contains a file named "cwl.output.json", that file must be loaded and used as the output object. 

This issue can be closed 😂

**Comment by mr-c** [comment]
Glad you found the information you need. You should be able to self-close issues you open :-)
