### ISSUE TITLE
Alternative way to encode wiring (dataLinks array)

### ISSUE THREAD

**Issue by ntijanic** [common-workflow-language/common-workflow-language#56]
While I prefer the `connect` property, many people I talked with said that it feels more natural to encode data links as a separate list of source+destination pairs (exactly as wf4ever originally does). Perhaps it is worth introducing this as an alternative? In any case, duplicate links should be ignored.

**Comment by tetron** [comment]
I would prefer not to do this to avoid having multiple ways to represent the same thing.

**Comment by tetron** [comment]
Discussed and rejected at the last hangout
