### ISSUE TITLE
Why should "reads.fastq" be removed from cli arguments, with running v1.0/tmap-tool.cwl

### ISSUE THREAD

**Issue by otiai10** [common-workflow-language/common-workflow-language#561]
# Question

As running [v1.0/tmap-tool.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/tmap-tool.cwl) with cwltool, I've got "reads.fastq" **not shown** on command line arguments.

in cwl

```js
    "inputs": [
        {
            "id": "reads",
            "type": "File"
        },
```

and provided job parameter

```js
{
    "reads": {
        "class": "File",
        "location": "reads.fastq"
    },
```

I had expected that "reads.fastq" **should be shown** on command line arguments, because it's valid and provided, and even existing!

What is the reason why it should be removed from command line arguments, and where is the official documentation for this behavior?

# Note

```zsh
% ./run_test.sh -n3 RUNNER=cwltool
--- Running conformance test v1.0 on /Users/otiai10/.pyenv/shims/cwltool ---
/Users/otiai10/.pyenv/versions/2.7.10/bin/cwltool 1.0.20171122141040
Test [3/111]
All tests passed

All tool tests succeeded
%
```

this is equivalent to

```zsh
% cwltool --outdir=~/tmp --quiet v1.0/tmap-tool.cwl v1.0/tmap-job.json
{
    "args": [
        "tmap",
        "mapall",
        "stage1",
        "map1",
        "--min-seq-length",
        "20",
        "map2",
        "--min-seq-length",
        "20",
        "stage2",
        "map1",
        "--max-seq-length",
        "20",
        "--min-seq-length",
        "10",
        "--seed-length",
        "16",
        "map2",
        "--max-seed-hits",
        "-1",
        "--max-seq-length",
        "20",
        "--min-seq-length",
        "10"
    ]
}
%
```

**Comment by tom-tan** [comment]
It is because `reads` does not have `inputBinding` field.

The [corresponding spec](http://www.commonwl.org/v1.0/CommandLineTool.html#Input_binding) says:
```
The tool command line is built by applying command line bindings to the input object. Bindings are listed either as part of an input parameter using the inputBinding field, or separately using the arguments field of the CommandLineTool.
```

That is, input objects without `inputBinding` do not occur in the command line arguments.
They are usually referred from `arguments` or expressions.

**Comment by mr-c** [comment]
@otiai10 I agree with @tom-tan 's explanation. Does that make sense to you?

**Comment by otiai10** [comment]
Thanks! I should have read it more carefully

**Comment by mr-c** [comment]
@otiai10 You are welcome and no worries; we are open to suggestions for making the spec and user guide more clear
