### ISSUE TITLE
Move streamable flag from bindings to ports?

### ISSUE THREAD

**Issue by ntijanic** [common-workflow-language/common-workflow-language#57]
If `streamable` property remains on input/output bindings, we cannot handle a very common case: input files bound to stdin should be streamable. Since the flag is in the binding, it means the binding exists (hehe) and therefore file should be passed through the command line (rather than e.g. stdin).

It is highly unlikely there will be cases where a port has complex type which contains files, and some of these files are streamable while others are not. Because of this, I think it makes sense to simply have `streamable` be the property of ports rather than bindings.

**Comment by tetron** [comment]
Good point.  I'll move `streamable` back to the `Parameter` definition.

**Comment by tetron** [comment]
Committed, please review and reopen ticket if you have any concerns.
