### ISSUE TITLE
input objects inherit the $namespaces of the CWL description

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#575]
Inspired by https://github.com/common-workflow-language/cwltool/issues/584

- [ ] update the spec
- [x] add an explicit conformance test

**Comment by tetron** [comment]
I think that's the current behavior of cwltool, agree it should be formalized.

**Comment by mr-c** [comment]
Already covered by test 64: https://github.com/common-workflow-language/common-workflow-language/blob/f24c797ea017a467185b516ea4862c9c494c9d33/v1.0/conformance_test_v1.0.yaml#L876

https://github.com/common-workflow-language/common-workflow-language/blob/f24c797ea017a467185b516ea4862c9c494c9d33/v1.0/v1.0/formattest.cwl#L1

https://github.com/common-workflow-language/common-workflow-language/blob/f24c797ea017a467185b516ea4862c9c494c9d33/v1.0/v1.0/formattest-job.json#L5
