### ISSUE TITLE
Be explicit that the designated output directory / initial current working directory is empty unless InitialWorkDirRequirement is specified

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#579]
Should go in the http://www.commonwl.org/v1.0/CommandLineTool.html#Runtime_environment section

**Comment by bogdang989** [comment]
Looks like this is also covered with https://github.com/common-workflow-language/common-workflow-language/commit/53b626aa7496320fb79d60be242f487593d42002
