### ISSUE TITLE
proposal: NetworkAccess

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#582]
NetworkAccess

Workflows should not assume internet access by default.

Indicate whether the workflow requires Internet access.

Field | Type 
-- | --
networkAccess | boolean

- [ ] implement in cwltool
- [x] spec changes

**Comment by denis-yuen** [comment]
While reasonable, this should probably be documented right up front in the equivalent of http://www.commonwl.org/v1.0/Workflow.html#Introduction_to_CWL_Workflow_standard_v1.0.2 or http://www.commonwl.org/v1.0/CommandLineTool.html#Introduction_to_CWL_Command_Line_Tool_standard_v1.0.2 for CWL 1.1 as a potentially breaking change for workflows migrating from CWL 1.0 to 1.1.

**Comment by tetron** [comment]
See #661

**Comment by tetron** [comment]
This is complicated by the fact that default behavior really needs to assume "no network access" but that's not currently the situation.  Discussion at https://groups.google.com/forum/#!topic/common-workflow-language/WsaREndia_M

**Comment by mr-c** [comment]
I thought we were no longer including `Requirement` in the names of new reqs?

Also, shouldn't the presence be sufficient?

``` yaml
requirements:
  Internet: {}
```
instead of
``` yaml
requirements:
  InternetRequirement:
    internetAccess: true
```

**Comment by tetron** [comment]
No, because then you can't explicitly turn it off.

I'm working on a schema salad branch that will let you write this:

```
requirements:
  NetworkAccess: true
```

As a shorthand for the fully expanded version:

```
requirements:
  - class: NetworkAccess
    networkAccess: true
```

https://github.com/common-workflow-language/schema_salad/tree/v1.1

**Comment by tetron** [comment]
merged
