### ISSUE TITLE
proposal: WorkReuse

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#583]
ReuseRequirement

If the platform supports job reuse / call caching, indicate whether a step is a candidate for reuse or not.

Field | Type | Description
-- | -- | --
enableReuse | boolean | Enable/disable work reuse for current process.  Default true (work reuse enabled).

- [x] implement in cwltool
- [x] mandatory conformance test to ensure that engines don't choke on the new syntax

**Comment by tetron** [comment]
See #661

**Comment by mr-c** [comment]
Does the default value for `enableReuse` differ if [`networkAccess: True`](https://github.com/common-workflow-language/common-workflow-language/issues/582)?

**Comment by tetron** [comment]
Some jobs that access the network such as a downloader job might be a valid candidate for reuse.  I think it is up to implementation to decide if previous work exists that can be reused based on its own policy, this could include network access true or false, but I don't think we should specify.

**Comment by mr-c** [comment]
> I think it is up to implementation to decide if previous work exists that can be reused based on its own policy, this could include network access true or false, but I don't think we should specify.

Sounds messy to me. There is a default value except when there isn't?

**Comment by tetron** [comment]
The original description says "default true" but I don't think we should be to specifying what the reuse policy actually is, because then we need to write conformance tests for it and require everyone to do it the same way, I don't think that's realistic.  The intended use of the feature is to indicate jobs that are definitely impure and shouldn't be reused.

**Comment by tetron** [comment]
merged
