### ISSUE TITLE
Have scatter and scatterMethod be properties of WorkflowStep

### ISSUE THREAD

**Issue by ntijanic** [common-workflow-language/common-workflow-language#59]
If requirements of the workflow step are interpreted as mixing with or overriding requirements of the step implementation, it doesn't feel consistent to have the scatter configuration in the requirement.

I'd suggest we revert to having `scatter` and `scatterMethod` be properties of steps and, if we want to keep scattering an optional feature, require that a `class: ScatterFeatureRequirement` (or equivalent) be listed in workflow requirements if workflow uses scatter.

**Comment by tetron** [comment]
Committed, please review and reopen ticket if you have any concerns.
