### ISSUE TITLE
proposal: TimeLimit

### ISSUE THREAD

**Issue by LourensVeen** [common-workflow-language/common-workflow-language#590]
I'm running CWL workflows on traditional HPC resources, which require an estimate of how long the job will take. ResourceRequirement lets you specify a number of cores, RAM, and disk space, but not time.

The time you specify on HPC resources is the length of the reservation, so after that amount of time the job is cancelled. Typically, you overestimate by a bit (or by a lot) to make sure that you can finish. I guess that makes this more of a minimum than a maximum, since you're saying that you want to have at least x seconds available, otherwise don't bother starting the job in the first place.

So perhaps a `minTime` field could be added to ResourceRequirement?

For symmetry, you'd expect a `maxTime` then as well, but I'm not sure what it would mean. You could imagine a workflow that runs in `maxTime` time if you give it `minCores` cores, and in `minTime` time if you give it `maxCores` cores, but if you're going to do performance modelling, then you should do a better job than that anyway. A simple `minTime` would cover my needs at least, so I propose to keep it simple and just add the one field.

- [x] spec changes
- [ ] reference implementations

**Comment by tetron** [comment]
This is a good idea.  However it should be added as a new requirement, not part of ResourceRequirement.

Maybe "DurationRequirement" to avoid overloading the term "runtime" (which is already used in the spec in the term "runtime environment" which is a slightly different concept.)

Some schedulers have a concept of "soft" and "hard" limits, but usually the user only can set the "soft" limit.  So for example, expect a job will take T amount of time, the job can go over T by some grace period S after which it hits the hard limit and is killed.  But the grace period is usually a system configuration and not under the user's control (if a user needs more time the user should request more time).

**Comment by mr-c** [comment]
@tetron Why a new requirement? Some schedulers have vary hard limits so run time does indeed become part of the resource matchmaking.

`maxTime` could be interpreted as an invitation to kill a running job/workflow that is simply running too long (due to bug, error, or user mis-configuration).

**Comment by tetron** [comment]
I think it should be a new requirement because it is somewhat input data/site specific in a way that ResourceRequirement isn't (as much).

If we have two values, I just want to be clear on the distinction.  Are you suggesting `minTime` is the time that should be used by a backfill scheduler, and `maxTime` is the time when the job actually gets killed?

**Comment by mr-c** [comment]
> I think it should be a new requirement because it is somewhat input data/site specific in a way that ResourceRequirement isn't (as much).

But any of the `ResourceRequirement` values can be driven by properties of the inputs.

Perhaps the question here is: would an overriding `ResourceRequirement` mask or replace values from an existing `ResourceRequirement`? If I override `minTime` only and there is an existing `minCores` does that get dropped?

>If we have two values, I just want to be clear on the distinction. Are you suggesting minTime is the time that should be used by a backfill scheduler, and maxTime is the time when the job actually gets 
killed?

Yes. And `maxTime` is what is sent to schedulers that have a unified soft & hard limit (many HPC sites).

**Comment by tetron** [comment]
Current semantics is that an override completely replaces a requirement, no merge (same as how a tool level requirement replaces a workflow level requirement, for example).

**Comment by LourensVeen** [comment]
If time is site-specific, then so is the number of cores. ARM-based cores are much slower than Intel ones, support for SSE/AVX/AVX-512 can make a big difference, clock speeds vary, etc.

I'm doing molecular dynamics simulations, and the number of cores and runtime requirements depend heavily on the input and on what I'm trying to achieve. For a standard protein-ligand production run where you want an answer quickly, 8 nodes (128 cores) for two hours seems to be the sweet spot, but only if you have a fast interconnect. If you have GPUs, then you need fewer nodes. If you're doing them in bulk and are willing to wait a bit, then one node (16 cores) for a day per job is overall more efficient. If you want to study some slower process, then maybe you need the simulation to run for much longer. And if you're doing protein-protein or ever larger structures, then the simulation may well to dozens of nodes.

Rather than trying to figure out all the details for each run, I'm planning to just offer a couple of general categories, e.g. small/medium/large/long. For each of those, a CWL step will be available, and they'll come with a scenario so people know which one to pick. The step is configured into the runner (Cerise), and will have a resource requirement that makes sense for that scenario on whichever machine Cerise is configured for.

So that's my use case. I'll do some benchmarking on each machine and figure out how long a run of a particular kind takes, add some safety margin, and then I'd like to be able to put that into my step. If it's not enough, the user can use the step for the next bigger scenario instead, and the whole machine-specific issue has been taken care of already by the way Cerise is designed and used.

**Comment by tetron** [comment]
See #661

**Comment by tetron** [comment]
Merged
