### ISSUE TITLE
Byte for CWLType

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#592]
Is there a plan to introduce `byte` type to represent byte sequence or string types other than Unicode?

Some tools may output byte sequences or strings other than Unicode.
We will use byte type for these purposes.

**Comment by mr-c** [comment]
No plans for now. In CWL v1.0 you can store any byte stream (of any encoding) in a `File`. Is that good enough for you?

**Comment by tom-tan** [comment]
Thank you for the comment.
We use the `File` objects when we want to handle some texts other than Unicode.
