### ISSUE TITLE
There are no descriptions about optional types

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#605]
[Section 2.4](http://www.commonwl.org/v1.0/CommandLineTool.html#Document_preprocessing) describes how to transform optional types such as `string?` and `boolean?` into primitive types (I mean the types in [Section 5.1.4](http://www.commonwl.org/v1.0/CommandLineTool.html#Document_preprocessing)) but there are no descriptions how these optional types behave.

It should be clarified in the specification.

**Comment by tom-tan** [comment]
There is another issue related to the optional types.

I understand `[<T>, "null"]` is valid because Section 2.4 mentions to it.
However I am not sure whether other array notations such as `[<T>, <T>]` or `[<T>]` are valid or not.

If there are other purpose for array notation of the types, it should be clarified.
Otherwise it should be clarified that other array notation should be rejected.

Such clarifications makes us easier to write valid CWL files and to develop CWL platforms.

**Comment by tetron** [comment]
Hi @tom-tan the validation is based on Avro validation.  I meant to add a section describing validation to the schema salad specification but never got around to it.  I apologize.

To answer your question, array notations are "union" or "sum" types.  So any of the types listed are valid for the field.  By convention, optional fields are "null" if not provided so they have the "null" type.

**Comment by tom-tan** [comment]
Thank you for the explanation!

I'm curious about the union type of `int` and `long` (also `float` and `double`).

Let us consider the following CWL file  and a job file for it.
How the platforms must behave for such cases?

```cwl
# sample.cwl
...
inputs:
  param: [int, long] # `param` can be `int` or `long`
...
```

```yaml
# job.yml
param: 10 # `int` or `long` or it causes platform dependent behavior?
```

**Comment by mr-c** [comment]
> `param: 10 # `int` or `long` or it causes platform dependent behavior?`

With regards to https://www.commonwl.org/v1.0/CommandLineTool.html#CWLType 
> int | 32-bit signed integer
> long | 64-bit signed integer

Use that to determine the type, so an 'int' or `long` in this case.

Incidentally, YAML only has `long`s though they call them `int`s :crying_cat_face:
