### ISSUE TITLE
CommandOutputParameter secondaryFiles should set the secondaryFiles property of the output object

### ISSUE THREAD

**Issue by ThomasHickman** [common-workflow-language/common-workflow-language#622]
Currently specifying secondaryFiles in a CommandOutputParameter means that an implementation only needs to verify that these secondaryFiles are present (see http://www.commonwl.org/v1.0/CommandLineTool.html#CommandOutputParameter). It would be great if all the output file's JSON (described here: http://www.commonwl.org/v1.1.0-dev1/CommandLineTool.html#File) had the property `secondaryFiles` appended to with the files found due to the CommandOutputParameter's secondaryFiles field

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-language/cwl-v1.1/pull/6 ; thanks!
