### ISSUE TITLE
lightweight java reference implementation

### ISSUE THREAD

**Issue by foreveremain** [common-workflow-language/common-workflow-language#64]
A lightweight CWL java stack along lines of existing python tools without any support for complex execution environments.

It should have an API providing:
  * methods for processing tool descriptions (_phase 0_)
  * constructing command lines based on tool descriptions and file locations/parameter values (_phase 1_)
  * ability to discover tool descriptions matching specific input/output/functional criteria (_phase 2_)
  * facilitate connection with heavyweight CWL enabled systems to allow workflow discovery, data staging and execution of complex workflows (_phase 3_)

Proposed for topic during BOSC Codefest 2015 (g+hangout 23rd June https://docs.google.com/document/d/1Ye8I35EHbyFXJD7h_M-5FMu21FsEXvE4DrxHiB3WIOE/edit?usp=sharing )

*Initial use case*
_Java UI auto-generation for a CWL tool available as binary on local file system which has specific input / output data requirements._

*Demonstration*
integrate with Jalview MSA workbench to provide autogenerated UI from tool descriptions for:
  a. MSA tool (input unaligned sequences, output is aligned sequences and optionally phylogenetic tree, similarity matrix, alignment quality file)
  b. sequence database search tool (input sequence + search parameters, output search report, profiles, other data)
 c. phylogeny command line tools (input alignment + tree building parameters, output tree(s), similarity matrices).

*Goal*
Lightweight component library with OSGi descriptors suitable for use in Cytoscape, Jalview, and ultimately included in BioJava.

**Comment by mr-c** [comment]
+1

**Comment by heuermh** [comment]
Willing to help with this

**Comment by foreveremain** [comment]
hey Mike - @stain and I had a chat about a possible way to go here for stage 0 via JAX/POJO bindings.
-> @stain also suggested we verify this against cwltool.py using RDF
 I don't think much more will happen at the codefest, at least not on my side, but we should pick it up again after ISMB.

**Comment by tetron** [comment]
Any progress on this?  Any way we can help?

**Comment by mr-c** [comment]
Ping :-)

**Comment by mr-c** [comment]
@pgrosu contributed a Java SDK for CWL that can be used as a starting point for this: https://github.com/common-workflow-language/cwljava/tree/master/WIP/paul

**Comment by mr-c** [comment]
Closing this issue so that development and discussion can occur at https://github.com/common-workflow-language/cwljava
