### ISSUE TITLE
spec/v1.0: clarify whether secondaryFiles on outputs are optional

### ISSUE THREAD

**Issue by buchanae** [common-workflow-language/common-workflow-language#658]
I think this test implies that secondary files are always optional for output files: https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/conformance_test_v1.0.yaml#L769

My understanding of the spec is that missing secondary files are required. I think the spec needs more clarity here, or the conformance test needs to be changed.

**Comment by cjllanwarne** [comment]
Am I misreading the test? That `cat-job.cwl` you linked to seems to be saying "get everything matching the glob: `output`", not "there must be at least one file matching `output`", so I think an empty list is a valid result.

**However** if there's a literal list of secondary files (eg a bring-along bam index) then that for sure should not be optional IMO

**Comment by buchanae** [comment]
http://www.commonwl.org/v1.0/CommandLineTool.html#CommandInputParameter
http://www.commonwl.org/v1.0/CommandLineTool.html#CommandOutputParameter

From the spec:
` An implementation may fail workflow execution if an expected secondary file does not exist.`

`output_file` [defines a secondary file `.idx`](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/optional-output.cwl#L20) which (as far as I can tell) doesn't exist. I'm confused about whether secondary files on outputs are considered optional, when they are required for inputs.

**Comment by kaushik-work** [comment]
#717

**Comment by mr-c** [comment]
From V1.1:

> When not explicitly specified, secondary files specified for inputs are required and outputs are optional.
