### ISSUE TITLE
document wf4ever heritage & how to convert CWL to wfdesc

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#67]

**Comment by ntijanic** [comment]
A CWL workflow parsed as json-ld should automatically also be a valid wfdesc workflow. We should mention this in the docs, but not sure how much more we can say :)

**Comment by tetron** [comment]
That's no longer true.  Fitting CWL into wfdesc was causing too many design compromises with no clear upside that for now the json-ld context does not use any wfdesc predicates.  Converting CWL to wfdesc should be relatively straightforward, but some ambiguities remain, like whether a wfdesc "process" is properly a WorkflowStep or a Tool.

We could probably iterate on it a few more times but the consensus was to get draft 2 done and not spend forever trying to perfect it.

**Comment by mr-c** [comment]
Thanks for the update Peter. Perhaps we can work with the wfdesc people to
align the standard and our use of it for future releases from both groups?

On Tue, Jun 30, 2015 at 4:59 AM Peter Amstutz <notifications@github.com>
wrote:

> That's no longer true. Fitting CWL into wfdesc was causing too many design
> compromises with no clear upside that for now the json-ld context does not
> use any wfdesc predicates. Converting CWL to wfdesc should be relatively
> straightforward, but some ambiguities remain, like whether a wfdesc
> "process" is properly a WorkflowStep or a Tool.
>
> We could probably iterate on it a few more times but the consensus was to
> get draft 2 done and not spend forever trying to perfect it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/common-workflow-language/common-workflow-language/issues/67#issuecomment-117150067>
> .
>
-- 
Michael R. Crusoe: Programmer & Bioinformatician crusoe@ucdavis.edu
The lab for Data Intensive Biology; University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe

**Comment by ntijanic** [comment]
I thought our properties/entities inherit from wfdesc where appropriate. The ambiguity can be resolved by declaring cwl:Workflow to be both wfdesc:Workflow and wfdesc:ProcessImplementation, I think.

> Perhaps we can work with the wfdesc people to align the standard and our use of it for future releases from both groups?

IIRC, @stain is coming to Dublin, we can sync there.

**Comment by tetron** [comment]
Will be documented in the upcoming Bioinformatics CWL paper
