### ISSUE TITLE
can scatter work with `Null` in a workflow

### ISSUE THREAD

**Issue by byb121** [common-workflow-language/common-workflow-language#677]
Current scatter requires input arrays to be in the same length, but in some workflows we want some of the arrays to be optional. The expected behaviour of such a step will be that `Null` arrays are left out from scatter.

An array of `Null` in this case can be a workaround, but certainly not an ideal solution. I feel it makes more sense that a workflow step is able to handle an optional input like a tool, even with scatter.

If conditionals are available, we certainly can skip `Null`s before they get to scatter, but there's nothing wrong to have a "smarter" scatter.

**Comment by mr-c** [comment]
Hello @byb121 and my apologies for the late response. We do have conditionals in CWL v1.2+ now, along with `pickValue` to cope with `null`s.

https://www.commonwl.org/v1.2/Workflow.html#Picking_non-null_values_among_inbound_data_links
https://www.commonwl.org/v1.2/Workflow.html#PickValueMethod
