### ISSUE TITLE
Must runtime.tmpdir != runtime.outdir ?

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#685]
I think so, but https://www.commonwl.org/v1.0/CommandLineTool.html#Runtime_environment isn't explicit about that.

- [x] decide
- [x] write a conformance test if so (test both the value of the paths and by placing files in each in case of symlinks)

**Comment by tetron** [comment]
I agree they must be distinct.  Otherwise it opens the door to confusion and nonportable behavior.

**Comment by jmchilton** [comment]
I'll try to get to this, this afternoon - somehow the loadContents and file literal stuff came along quicker than I thought.

**Comment by mr-c** [comment]
Thank you @jmchilton !
