### ISSUE TITLE
CWL User Guide doesn't mention 'scatter'

### ISSUE THREAD

**Issue by Gibbsdavidl** [common-workflow-language/common-workflow-language#699]
It appears there's no mention of scatter or gather in the user guide, even though it seems like a pretty important part of CWL.

Thanks!
-dave

**Comment by mr-c** [comment]
Thank you @Gibbsdavidl for your issue. I think https://github.com/common-workflow-language/user_guide/issues/104 already covers that need. Are you available to help us write a simple introduction to `scatter`?

**Comment by Gibbsdavidl** [comment]
Hello, after pondering the universe for a few days, I think I can say: yes.

I'm going to be writing a blog post next week, and I think it could be worked into a 'scatter draft' following the user docs already written.  I've already worked through doing a scatter and sending the files through a few steps, culminating with a 'gather'.

**Comment by mr-c** [comment]
@Gibbsdavidl Thank you! I've invited you to the CWL `People` team; once you accept I can assign the issue to you.

**Comment by MatthewRalston** [comment]
Does this need closing

**Comment by mr-c** [comment]
Fixed by https://github.com/common-workflow-language/user_guide/pull/114
@Gibbsdavidl You are welcome to suggestion enhancements!
