### ISSUE TITLE
Directory full of files as input

### ISSUE THREAD

**Issue by drkennetz** [common-workflow-language/common-workflow-language#700]
Can cwl take a path to a directory (full of say, fastq files) and use the directory as input and stage all of the files in the directory as an array of files for the next step in a workflow?
Currently, my workaround for this is to use a shell script to wrap a python script which generates a yml file, in the first step, and then uses the .yml file in the second step to run the code:
```
#!/usr/bin/env python
  
  import os

  yml_file = "qc.yml"
  f = open(yml_file, 'w')
  f.write("allFastqFile:" + '\n')
  for filename in os.listdir(os.getcwd()):
      if ".fastq" in filename:
          f.write(" - " + "{class: File, path: " + os.path.abspath(filename) + "}" + '\n')
```

This kind of seems like a hack. For completeness, the shell script is:
```
#!/bin/bash

FASTQ_FOLDER=$1; shift
cd $FASTQ_FOLDER

$(python3.5 /path/to/yml.py)
$(cwltool preprocess.cwl qc.yml)
```
Which then runs the workflow on all the fastq files and outputs them locally.
Thanks,
Dennis

**Comment by mr-c** [comment]
Hello @drkennetz 
Does the following approach work for you?

``` cwl
cwlVersion: v1.0
class: Workflow
inputs:
  my_dir: Directory

outputs: []

steps:
  first_step:
    run: tool_needing_array.cwl
    in:
       tool_input_that_is_an_array_of_files:
         source: my_dir
         valueFrom: $(self.listing)
    out: []
```

**Comment by drkennetz** [comment]
No, the error is:
`[dkennetz@hpc02  fastqc]$ cwltool fastqcInDir.cwl --workdir /path/to/fastqs/
/bin/cwltool 1.0.20170828135420
Resolved 'fastqcInDir.cwl' to 'file:///users/dkennetz/fastqc/fastqcInDir.cwl'
[workflow fastqcInDir.cwl] start
Unhandled exception
Traceback (most recent call last):
  File "/hpcf/apps/python/install/3.5.2/lib/python3.5/site-packages/cwltool/work                                   flow.py", line 400, in try_make_job
    Callable[[Any], Any], callback), **kwargs)
  File "/hpcf/apps/python/install/3.5.2/lib/python3.5/site-packages/cwltool/work                                   flow.py", line 891, in dotproduct_scatter
    jo[s] = joborder[s][n]
KeyError: 0
[workflow fastqcInDir.cwl] completed permanentFail
{
    "fastqcOut": null
}
Final process status is permanentFail
`
with the code adjusted to:
`cwlVersion: v1.0
class: Workflow
requirements:
 - class: StepInputExpressionRequirement
 - class: InlineJavascriptRequirement
 - class: MultipleInputFeatureRequirement
 - class: ScatterFeatureRequirement

inputs:
  workdir: Directory

outputs:
  fastqcOut:
    type: File[]
    outputSource: fastqcRunner/htmlFile
  fastqcOut:
    type: File[]
    outputSource: fastqcRunner/zippedFile
  fastqcOut:
    type: Directory[]
    outputSource: fastqcRunner/report

steps:
  fastqcRunner:
    run: fastqc.cwl
    scatter: fastqFile
    in:
      fastqFile:
        source: workdir
        valueFrom: $(self.listing)
    out:
      [htmlFile, zippedFile, report]
`
in the tool, fastqc.cwl I have tried using both a single file and a file array as the expected input, both give the same error.

**Comment by mr-c** [comment]
Hey @drkennetz 

(BTW, to get the source code to show correctly I edited your posts to use triple backticks \`\`\` instead of single backticks)

Here's a fully tested example, sorry for not double checking earlier:

``` cwl
cwlVersion: v1.0
class: Workflow
inputs:
  my_dir: Directory

outputs: []

requirements:
  StepInputExpressionRequirement: {}

steps:
  first_step:
    run:
      class: CommandLineTool
      inputs:
        array_of_files:
          type: File[]
          inputBinding: {}
      baseCommand: echo
      outputs: []
    in:
      array_of_files:
         source: my_dir
         valueFrom: $(self.listing)
    out: []
```

Reviewing your code it looks like you want to combine a `scatter` with and input that uses a `valueFrom` operation; however `valueFrom` is applied after scattering, not before: https://www.commonwl.org/v1.0/Workflow.html#WorkflowStepInput

So you'll need a separate step to transform your Directory into an array of Files, that can then be scattered over. Here's the same example re-worked to do that with an `ExpressionTool`

``` cwl
cwlVersion: v1.0
class: Workflow
inputs:
  my_dir: Directory

outputs: []

requirements:
  StepInputExpressionRequirement: {}
  ScatterFeatureRequirement: {}

steps:
  zeroth_step:
    run:
      class: ExpressionTool
      requirements: { InlineJavascriptRequirement: {} }
      inputs:
        dir: Directory
      expression: '${return {"files": inputs.dir.listing};}'
      outputs:
        files: File[]
    in:
      dir: my_dir
    out: [files]
  first_step:
    run:
      class: CommandLineTool
      inputs:
        my_file:
          type: File
          inputBinding: {}
      baseCommand: echo
      outputs: []
    in:
      my_file: zeroth_step/files
    scatter: my_file
    out: []
```

So it is your choice of hack. 1) generate a verbose input object outside the workflow, or 2) convert the Directory to an array of `File`s

**Comment by drkennetz** [comment]
Fair enough! I really appreciate the promptness of your responses. I am doing some learning and have both versions of the workflow functional. Thanks for the valueFrom clarification.

**Comment by mr-c** [comment]
You are welcome :-) I'm going to close this issue for now. Feel free to ask future questions in https://gitter.im/common-workflow-language/common-workflow-language or at BioStars as explained at http://www.commonwl.org/#Support
