### ISSUE TITLE
Hash/checksum for docker image as hint

### ISSUE THREAD

**Issue by kghosesbg** [common-workflow-language/common-workflow-language#709]
(Forgive me if this is already in the docs/discussion, I couldn't find it)

### Problem
The docker image a CWL commandline tool links to originally can be changed without any changes visible to the user. This may lead to issues with reproducibility.
 
### Desired behavior

1. A CWL tool 2.0 may carry an `image_checksum` field that will allow a user (via an executor or tool editor) to cross-check the actual docker image that is fetched by the tool against what the tool designer intended.
2. This will also encourage tool builders to create a new version of the tool when they change the docker image, which is safe practice in the pursuit of reproducible workflows.

Thanks!

**Comment by mr-c** [comment]
Hey @kghosesbg, looks like we need to improve the user guide on this topic. `dockerImageId` https://www.commonwl.org/v1.0/CommandLineTool.html#DockerRequirement already accepts a Docker container hash/checksum.

**Comment by kghosesbg** [comment]
Sweet! Ok, I can make myself useful and edit that part of the user guide 😃
