### ISSUE TITLE
index fasta freebayes

### ISSUE THREAD

**Issue by ralonso-igenomix** [common-workflow-language/common-workflow-language#716]
Hello,
I've created this cwl
<pre>
#!/usr/bin/env cwltool

cwlVersion: v1.0

class: CommandLineTool

requirements:
  - class: DockerRequirement
    dockerImageId: maxulysse/freebayes
  - class: InlineJavascriptRequirement
  - class: ResourceRequirement
    coresMin: 1
    ramMin: 8000

baseCommand: [freebayes]

inputs:

  input_bam_file:
    type: File
    inputBinding:
       prefix: -b
    doc: "input bam file"
  input_fasta_file:
    type: File
    inputBinding:
       prefix: -f
    doc: "input fasta file"
  output_vcf_file:
    type: string?
    inputBinding:
       prefix: -v
       valueFrom: $(inputs.input_bam_file.nameroot.replace(".bam",".vcf"))
  min-base-quality:
    type: int
    default: 3
    inputBinding:
      prefix: --min-base-quality
  F:
    type: double
    default: 0.15
    inputBinding:
      prefix: -F

outputs:
    output_vcf_file_obj:
       type: File
       outputBinding:
         glob: $(inputs.input_bam_file.nameroot.replace(".bam",".vcf"))

</pre>

But freebayes needs a hs37d5.fasta.fai that you can't pass as argument, or when cwl tries to generate it, cwl doesn't have permission. 
This is my yaml file:
<pre>

input_bam_file:
        class: File
        path: /home/ralonso/projects/Arvados/igx_arvados/Sample_ZFZ7KDA.RG.rmDup.bam
input_fasta_file:
        class: File
        path: /home/ralonso/projects/Arvados/igx_arvados/hs37d5.fasta
</pre>

And this is my command line:
<pre>
cwltool freebayes.cwl freebayes.yaml
</pre>

How could I do, please? 

Thanks a lot

**Comment by bogdang989** [comment]
This is a perfect case to use `secondaryFiles` - https://www.commonwl.org/v1.0/CommandLineTool.html#CommandInputParameter:
Try something like this
```
  input_fasta_file:
    type: File
    secondaryFiles:
      - .fai
    inputBinding:
       prefix: -f
    doc: "input fasta file"
```

**Comment by ralonso-igenomix** [comment]
Works like a charm! shouldn't be more examples in general?
thanks!
