### ISSUE TITLE
Document says `steps` should be an array of `WorkflowStep` but examples use `steps` as a dictionary type

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#729]
The [Spec for workflows](https://www.commonwl.org/v1.0/Workflow.html#Workflow) says that the type of `steps` field should be an array of `WorkflowStep`.
However, some examples in the repository represent `steps` field as a dictionary type.
For instance, [basename-fields-test.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/basename-fields-test.cwl) uses the following form for `steps`:

```
...
steps:
  root:
    ...
  ext:
    ...
```

I confirmed that the [schema for Workflow](https://github.com/common-workflow-language/common-workflow-language/blob/2cf94032669f1ed5933b4bb58755af2031d25137/v1.0/Workflow.yml#L557) specifies `jsonldPredicate` field to make `steps` usable as a dictionary type.
Therefore I guess that it is a problem of the HTML generator for the schema rather than the problem of examples in the repository.

**Comment by tetron** [comment]
Yes, that's correct, could you file an issue on https://github.com/common-workflow-language/schema_salad about this?  That's where HTML generator is implemented.

**Comment by tetron** [comment]
You can leave this one open, it is still a problem (once the schema salad issue is fixed the web site will still need to be updated).

**Comment by tom-tan** [comment]
OK, I will leave it until common-workflow-language/schema_salad#167 is closed.

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-language/schema_salad/pull/193
