### ISSUE TITLE
[Question] What does "$" mean, in outputEval?

### ISSUE THREAD

**Issue by otiai10** [common-workflow-language/common-workflow-language#741]
I'm looking through [`wc2-tool.cwl`](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/wc2-tool.cwl) and trying to implement an engine for that.

I couldn't figure out the meaning of `$` at all. What does `$` mean?

OK, if it is ES2015, it can be described as 

```js
`${foobar}` // string
```

but there are many `$(foobar)` (as they are evaluated as `"$(foobar)"`), and also there are mixed expressions under `./v1.0/v1.0` with `$(foobar)`, `${foobar}` and `$(foo)/$(bar)`.

If there is any documentation of the `$` which you CWL guys are using, please let met know that docs.

Thank you in advance.

**Comment by otiai10** [comment]
OK, I understand it is **NOT** pure JavaScript as a whole!
https://www.commonwl.org/v1.0/CommandLineTool.html#Expressions

I have to evaluate each fragment which is wrapped with `$()` and `${}`.

Thank you anyway.

**Comment by tetron** [comment]
@otiai10 correct, it is a cwl-specific syntax, not javascript ES6 syntax.  We made a mistake.  #609 has  discussion about using ES6 syntax in the future.
