### ISSUE TITLE
 Why conformance test 63 expect empty result ? 

### ISSUE THREAD

**Issue by manabuishii** [common-workflow-language/common-workflow-language#743]
In conformance_test_v1.0.yaml
test id 63 expected empty output.
(metadata.cwl, cat-job.json)

```
- output: {}
  job: v1.0/cat-job.json
  tool: v1.0/metadata.cwl
  label: metadata
  id: 63
  doc: Test metadata
  tags: [ required ]
```

In `metadata.cwl` , following lines are written.

```
outputs: []
baseCommand: cat
```

Name of file is `metadata.cwl`
and the file have metadata information.
I think`doc` field is different expected result.

```
doc: "Print the contents of a file to stdout using 'cat' running in a docker container."

dct:creator:
  id: "http://orcid.org/0000-0003-3566-7705"
  class: foaf:Person
  foaf:name: Peter Amstutz
  foaf:mbox: "mailto:peter.amstutz@curoverse.com"
```

I think because of filename , this test MUST be test about metadata.
And `doc` field MUST be updated.
Or change filename and `doc` field.

**Comment by GlassOfWhiskey** [comment]
@mr-c and @kinow: this one has probably been solved by [184](https://github.com/common-workflow-language/common-workflow-language/) in version 1.2.1. Do you want to leave it open for backporting or we can close it?
