### ISSUE TITLE
Enable customizing temp-dir from command line (docker)

### ISSUE THREAD

**Issue by robinandeer** [common-workflow-language/common-workflow-language#75]
This is an issue on Mac where you can't mount folders (like ``/var``) outside of ``/Users``

**Comment by brainstorm** [comment]
Talking with @tetron and @sinisa88 in the BOSC2015 hackathon, it seems that a reasonable way to fix this is to have a common `tmp` prefix for all the `mkdtmp()` calls so that all steps in the CWL workflow are seen by the boot2docker VM.

**Comment by guillermo-carrasco** [comment]
@robinandeer you can close this :-)
