### ISSUE TITLE
need conformance test for multiple entries in a WorkflowOutputParameter.outputSource

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#754]
For example, toil-cwl-runner can't handle this as of 3.17.0

**Comment by GlassOfWhiskey** [comment]
@mr-c I see conformance tests with multiple entries in the `outputSource` field now, e.g., [this one](https://github.com/common-workflow-language/cwl-v1.2/blob/63d47845604a83b9ef3ae5a6324b9b9931df8160/tests/conditionals/cond-wf-007.cwl#L27). Can we close the issue or there is still something to do?

**Comment by mr-c** [comment]
@GlassOfWhiskey good catch! Thanks
