### ISSUE TITLE
According to the spec, the workflows that uses workflow-specific requirements must always fail.

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#757]
The [spec of Workflow](https://www.commonwl.org/v1.0/Workflow.html#Requirements_and_hints) says:
```
Requirements are inherited. A requirement specified in a Workflow applies to all workflow steps; ...
```

On the other hand, the [spec of CommandLineTool](https://www.commonwl.org/v1.0/CommandLineTool.html#Requirements_and_hints) says:
```
If an implementation cannot satisfy all requirements, or a requirement is listed which is not recognized by the implementation, it is a fatal error...
```

As the result of them, if we develop a workflow engine that support this specification, 
it always returns `permanentFailure` when it executes the workflows that use workflow-specific requirements such as `SubworkflowFeatureRequirement`.

Obviously it is not an intended behavior and we have to fix the spec.

**Comment by mr-c** [comment]
@tom-tan We agree, thanks for catching this.

In short, requirements that are part of the `Workflow` CWL v1.0 standard but not the `CommandLineTool` standard do not flow to `CommandLineTool`s under `steps`, but they do flow to `ExpressionTool`'s and sub-`Workflow`s, though that won't change their behavior.

Therefore implementors can choose to only propagate the requirements listed in the `CommandLineTool` standard: InlineJavascriptRequirement | SchemaDefRequirement | DockerRequirement | SoftwareRequirement | InitialWorkDirRequirement | EnvVarRequirement | ShellCommandRequirement | ResourceRequirement.

**Comment by tom-tan** [comment]
Thank you for the explanation!

IMO it is better to specify the requirements that are propagated to the steps by fixing the section 3.3.
For instance,

> ...
> The following requirements are inherited: `InlineJavascriptRequirement`, `SchemaDefRequirement`, `DockerRequirement`, `SoftwareRequirement`, `InitialWorkDirRequirement`, `EnvVarRequirement`, `ShellCommandRequirement`, and `ResourceRequirement`. 
> These requirements specified in a Workflow apply to all workflow steps; ...

**Comment by tom-tan** [comment]
Is it OK to fix this repository, or better to change v1.1 and leave v1.0 as is?

**Comment by mr-c** [comment]
Better to change v1.1

**Comment by tom-tan** [comment]
I see.
I will send a request to v1.1 repository.

**Comment by mr-c** [comment]
Fixed by https://github.com/common-workflow-language/cwl-v1.1/pull/21 !
