### ISSUE TITLE
Is there any Reserved Words in CWL ?

### ISSUE THREAD

**Issue by manabuishii** [common-workflow-language/common-workflow-language#759]
I can not find about Reserved Words in CWL specification.
(I search with "reserved" in CommandLineTool.html, Workflow.html, and SchemaSalad.html)
CWL has no reserved words?

**Comment by mr-c** [comment]
CWL v1.0 has no reserved keywords. We currently have no plans for reserved keywords in future versions.

YAML itself has some reserved syntax and characters, but nothing that impacts CWL or user specified identifiers.

**Comment by manabuishii** [comment]
@mr-c Thanks.
I understand.
