### ISSUE TITLE
Unclear specification of `run` field in the workflow description

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#760]
In the [spec](https://www.commonwl.org/v1.0/Workflow.html#WorkflowStep), `run` field can be a `string`, a `CommandLineTool`, a `ExpressionTool`,  or a `Workflow`.

IMO it is obvious what happens in the cases of a `CommandLineTool`, a `ExpressionTool`,  or a `Workflow`.
However, in the case of a `string`, it seems to be unclear how the platforms behave for it.

What are the acceptable values for this field?
- Some conformance tests specify the file names for the steps (e.g. `echo-tool.cwl`) but it is not clear how the platforms find them.
- Are relative paths acceptable? How about absolute paths, URIs (`file://`, `http://` and `https://`, `gs://`, `s3://` and others)?
  - If URIs and relative paths are acceptable, what happens when they are combined?

It would be nice if there exists a description for it.

**Comment by mr-c** [comment]
Thank you @tom-tan, you are correct, this is under specified.

The string form accepts relative or absolute paths and URI identifiers. For maximum portability the URIs should use the HTTP or HTTPS protocols and be publicly accessible.

Relative paths are resolved according to the Schema Salad link resolution rules: in short: relative to the directory or base URI of the parent document, as specified in https://www.commonwl.org/v1.0/SchemaSalad.html#Implied_context and https://www.commonwl.org/v1.0/SchemaSalad.html#Link_resolution

The standard does define how to discover local CWL tool descriptions: https://www.commonwl.org/v1.0/Workflow.html#Discovering_CWL_documents_on_a_local_filesystem

As a technology example, the reference runner supports references to external CWL descriptions downloaded via the GA4GH Tool Registry Schema (defaulting to the registry at dockstore.org): https://github.com/common-workflow-language/cwltool#use-with-ga4gh-tool-registry-api

**Comment by tom-tan** [comment]
Thank you for the explanation!

I have several questions that are related to them.

- The value of `run` field (whose type is `string`) is resolved by the rules defined in Schema Salad. I am curious about other `string` fields. In the current spec, it is hard to know whether a certain field whose type is `string` is resolved or not. It would be better to clarify it (I prefer introducing a new type for it).

- In my understanding, the [section 3.7 in the spec](https://www.commonwl.org/v1.0/Workflow.html#Discovering_CWL_documents_on_a_local_filesystem) is for discovering local documents. If so, is there a plan to extend it to the remote documents? It would be nice If a platform can execute workflows, in which CWL documents for the workflow and the steps are located in different remote paths (e.g. workflows in [pitagora-galaxy/cwl](https://github.com/pitagora-galaxy/cwl)), by configuring user-defined search paths.

**Comment by tom-tan** [comment]
> In the current spec, it is hard to know whether a certain field whose type is string is resolved or not.

Now I understand Schema Salad a little. It is clear in the schema level because strings that are declared with `{ "_type": "@id" }` in the `jsonldPredicate` field are resolved to an absolute URIs with [link resolution rules](https://www.commonwl.org/v1.2/SchemaSalad.html#Link_resolution).

On the other hand, it is not clear in the document level because such rules are not described in the `run` field.
How about adding the following description to the `run` field, for example?
```
If `run` is a string, it must be an absolute IRI or a relative path from the primary document.
```

**Comment by mr-c** [comment]
> On the other hand, it is not clear in the document level because such rules are not described in the `run` field. How about adding the following description to the `run` field, for example?
> 
> ```
> If `run` is a string, it must be an absolute IRI or a relative path from the primary document.
> ```

I would accept this addition, thanks!

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-language/cwl-v1.2/pull/175
