### ISSUE TITLE
Conflict between the conformance test 61 and the spec for parameter references (3.4)

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#761]
The conformance test 61 using [params.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/params.cwl), [params_inc.yml](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/params_inc.yml) and [empty.json](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/empty.json) is a test for parameter references without `InlineJavascriptRequirement` and seems to be designed to be passed.

However, it includes two expressions that should be Javascript expressions.

## Problems

- There is a reference [`$(null)`](https://github.com/common-workflow-language/common-workflow-language/blob/22490926651174c6cbe01c76c2ded3c9e8d0ee6f/v1.0/v1.0/params_inc.yml#L115) but it is not documented as an acceptable expression in the [spec for parameter references](https://www.commonwl.org/v1.0/CommandLineTool.html#Parameter_references).
  The spec says:
> Use the following algorithm to resolve a parameter reference:
> 1. Match the leading symbol as the key
> 2. Look up the key in the parameter context (described below) to get the current value. It is an error if the key is not found in the parameter context.

But in the spec, there are only three parameter contexts (`inputs`, `self`, and `runtime`) and therefore `$(null)` should be rejected according to the current spec.

- There is a reference [`$(inputs.bar.buz.length)`](https://github.com/common-workflow-language/common-workflow-language/blob/22490926651174c6cbe01c76c2ded3c9e8d0ee6f/v1.0/v1.0/params_inc.yml#L120) to get the size of the array [`inputs.bar.buz`](https://github.com/common-workflow-language/common-workflow-language/blob/22490926651174c6cbe01c76c2ded3c9e8d0ee6f/v1.0/v1.0/params.cwl#L11). But the [spec](https://www.commonwl.org/v1.0/CommandLineTool.html#Parameter_references) says:
> Use the following algorithm to resolve a parameter reference:
> ...
> 6. ... If the key is a symbol or string, the current value must be an object. If the key is an index, the current value must be an array or string. It is an error if the key does not match the required type, or the key is not found or out of range.

And therefore it should be rejected according to the current spec because the expression `$(inputs.bar.buz.lengtth)` has a key `length` for the array `inputs.bar.buz` .

## Two ways to solve them
There are two ways to solve the above problems:
- Fix the test 61 so that it should be rejected (i.e. `should_fail: true`). In this scenario, we do not have to fix the  spec but have to fix the conformance test 61 (and we have to add more test cases for it). In addition to that, it will break existing platforms that passes the test 61.

- Fix the spec to accept `$(null)` and a `length` property for array type without `InlineJavascriptRequirement`. It will not break existing platforms. However, it will bring complexities for existing and future developers of the platforms to implement it.

IMO the former is better for long term schedule even if it breaks existing platforms. How about fixing this issue in v1.1?

---
- [ ] make a copy of  https://github.com/common-workflow-language/common-workflow-language/blob/26c8b9ca0ffd37c5f76a46a36315f6fd944833fe/v1.0/v1.0/params_inc.yml#L112 without the last two scenarios ( `$(null)` and `$(inputs.somearray.length)`) for use in test 61 in v1.0 & v1.1
- [ ] add a v1.2.1 conformance test that `should_fail: true` for the removed cases (in progress at https://github.com/common-workflow-language/cwl-v1.2/pull/64)
- [ ] update cwltool to reject these parameter references in v1.2
- [ ] update cwl-upgrader to detect this pattern and to add `InlinesJavascriptRequirement` for v1.1 → v1.2

**Comment by tom-tan** [comment]
Ping!
Any comments or am I missing something?

**Comment by mr-c** [comment]
I agree that in a CWL document without `InlineJavascriptExpression` that a `$(null)` in an Expression capable field should not be evaluated as all CWL Parameter references must begin with `inputs`, `self`, or `runtime`.

**Comment by mr-c** [comment]
Likewise I concur that CWL v1.0 does not provide for a `length` parameter on arrays. This had been propsed in https://github.com/common-workflow-language/common-workflow-language/issues/350 but not agreed (and not in the spec as far as I can see). Therefore it should be removed from this conformance test and a contrary `should_fail` conformance test using the `length` property should be added.

**Comment by mr-c** [comment]
@tetron This conformance test does not use `InlineJavascriptRequirement` but does use `$(null)` and `$(inputs.somearray.length)` which is not permitted in v1.0. I've added a checklist to this issue and we should fix this for v1.1; do you agree?

**Comment by mr-c** [comment]
For CWL v1.2.1, we have to allow `$(null)` and `$(inputs.somearray.length)` as conformance tests has relied upon this since CWL v1.0

**Comment by mr-c** [comment]
https://www.commonwl.org/v1.2/CommandLineTool.html#Parameter_references needs updating

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-language/cwl-v1.2/pull/64
