### ISSUE TITLE
Add exit code value

### ISSUE THREAD

**Issue by kmhernan** [common-workflow-language/common-workflow-language#768]
I have a case where I would like to allow different exit codes, but I also want to be able to extract which exit code was actually given so I can use it to make decisions in the next steps. Providing the exit code in the v1.x series seems like a useful feature.

**Comment by tetron** [comment]
Yes, I agree, I'd like to add this as well.

**Comment by mr-c** [comment]
This was implemented in CWL v1.2.0-dev5! https://www.commonwl.org/v1.2.0-dev5/CommandLineTool.html#Execution

**Comment by mr-c** [comment]
> The exit code of the process is available to expressions in `outputEval` as `runtime.exitCode`.
