### ISSUE TITLE
There are no descriptions how `runtime.outdir` behaves with `DockerRequirement`

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#774]
According to the [spec](https://www.commonwl.org/v1.0/CommandLineTool.html#Runtime_environment), `runtime.outdir` is an absolute path to the designated output directory.

For example, let us consider the following command to execute CommandLineTool (See [envvar2.cwl](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/envvar2.cwl) and [empty.json](https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/empty.json) that are used in the conformance test 96).
```console
$ cwltool --outdir=/foo/bar/buzz --debug v1.0/envvar2.cwl v1.0/empty.json
```
In that case, I expect that `runtime.outdir` is always same as `/foo/bar/buzz`.
However, in the above example, `runtime.outdir` returns `/var/spool/cwl` instead of `/foo/bar/buzz`.

The reason why it returns different path is that `envvar2.cwl` uses `DockerRequirement` and it modifies values of the fields in `runtime`.
However there are no descriptions of such a behavior in the spec.
It should be clarified.

**Comment by mr-c** [comment]
Hello @tom-tan , a PR to clarify this would we welcome.

`runtime` refers to the execution of a specific job (a specific running of a CommandLineTool) so the definition is fine within that context.

**Comment by tom-tan** [comment]
Thank you for the explanation!

The reason why I got confused with it is the difference of the point of view for `runtime`.
I expect `runtime.outdir` returns `/foo/bar/buzz` from the point of view of users who execute the platforms.
But the spec describes about the designated output directory from the point of view of commands (`echo` and `test` commands in `envvar2.cwl` in the example).

I will send a PR for it later. Once it is clarified, I will close this issue.

**Comment by tom-tan** [comment]
I close this issue because it is clarified by #774. Thanks!
