### ISSUE TITLE
Building arguments for command line application ?

### ISSUE THREAD

**Issue by nyue** [common-workflow-language/common-workflow-language#776]
Hi,

  I have a command line application that takes for following commands

  $myprog --parallel -type "abc" -culture "xyz" -threads 4

  I am struggling to build up the commands required via CWL. Currently, I have the following but it does not seems to build the arguments correctly.

cwlVersion: v1.0
class: CommandLineTool
baseCommand: myprog
inputs:
  type:
    type: string
    inputBinding:
      position: 1
  culture:
    type: string
    inputBinding:
      position: 2
  threads:
    type: int
    inputBinding:
      position: 3
  arguments: ["--parallel", "-type", $(inputs.type), "-culture", $(inputs.culture), "-threads", $(inputs.threads)]
  outputs: []

Cheers

**Comment by tom-tan** [comment]
You do not have to use `inputBinding` and `position` when the corresponding parameter is referred in the `arguments` fields. That is:

```cwl
cwlVersion: v1.0
class: CommandLineTool
baseCommand: myprog
inputs:
  type:
    type: string
  culture:
    type: string
  threads:
    type: int
arguments: ["--parallel", "-type", $(inputs.type), "-culture", $(inputs.culture), "-threads", $(inputs.threads)]
outputs: []
```

I hope it works for you.

**Comment by nyue** [comment]
Thanks. Confirming that your recommendation works.
