### ISSUE TITLE
Proposal: Change expression syntax to not clash with Bash variables

### ISSUE THREAD

**Issue by kaushik-work** [common-workflow-language/common-workflow-language#790]
We are so close to being able to write straight Bash driver scripts in the wrappers, but it is annoying to have to escape bash syntax. We should rather change the CWL syntax to be more distinct.

Proposed syntax: use `CXP:` as the CWL expression identifier: `CXP:(...)`  and `CXP:{...}`
Three more letters to type and a whole world of bash related pain taken away ...

**Comment by kaushik-work** [comment]
FYI @christiansbg

**Comment by christiansbg** [comment]
Another solution is to have proper literal prefix that will not look for JS snippets inside. Same idea as triple-quotes in other languages.

**Comment by kaushik-work** [comment]
This is better solved by #850
