### ISSUE TITLE
Add conformance test for outputSource referencing workflow input

### ISSUE THREAD

**Issue by bogdang989** [common-workflow-language/common-workflow-language#799]
Add conformance test for outputSource referencing workflow input

**Comment by mr-c** [comment]
From today's meeting: an "accidental feature", this works with the CWL reference runner. Should we formalize this in v1.1 or v1.0?

**Comment by bogdang989** [comment]
I'd say v1.1 is the way to go?

**Comment by portah** [comment]
It's already there :)
Just don't brake it till v1.1 or why not to formalize here in v1.0

**Comment by bogdang989** [comment]
Looks like this is already covered with test 20 https://github.com/common-workflow-language/common-workflow-language/blob/master/v1.0/v1.0/any-type-compat.cwl

**Comment by kaushik-work** [comment]
Since the conformance test already exists, what remains is to add clarification in the spec.
