### ISSUE TITLE
Wildcard/regex input example ?

### ISSUE THREAD

**Issue by nyue** [common-workflow-language/common-workflow-language#817]
Hi,

  I am looking for example *.cwl file which illustrate how to handle wildcard/regex filenames as input parameter but I can't seems to locate them.

  I have two application that takes in arguments like the following:

  cudaTransformBBox -i *.abc
  oclImageStitch *.exr

  How do I pass *.abc and *.exr as input parameter to be use in command line tool called within CWL ?

Cheers

Cheers

**Comment by mr-c** [comment]
Hello @nyue

Does `cudaTransformBBox` want a literal `*.abc` or does it expect the shell to expand `*.abc` to all the files in the current directory that end with `abc`?

If the latter (which is more likely), then here is a minimal example

``` cwl
cwlVersion: v1.0
class: CommandLineTool
inputs:
  my_files:  # should use a better name, but I don't know what `cudaTransformBBox` does
     type: File[]
     inputBinding:
       prefix: -i
baseCommand: cudaTransformBBox
outputs: []  # this needs to be filled out
```
