### ISSUE TITLE
Enable storing the standard error when running a tool

### ISSUE THREAD

**Issue by hmenager** [common-workflow-language/common-workflow-language#83]
Currently the reference implementation only allows to store the standard output when running a tool, and does not store the standard error. It may be useful to store it, esp. to track errors. Additionally, when running a workflow with multiple intermediate steps, having these all write potentially simultaneously to the standard error will make the result unreadable.

**Comment by mr-c** [comment]
Moved to the reference implementation repository: https://github.com/common-workflow-language/cwltool/issues/6
