### ISSUE TITLE
[Question] {class: Workflow} specify steps

### ISSUE THREAD

**Issue by r06942072** [common-workflow-language/common-workflow-language#839]
Link: https://github.com/r06942072/CWL_Common-Workflow-Language/blob/dev/final-workflow.cwl
I met some problems when using CWL.
I know that the steps order is decided by input/output relationship, but I wonder if there is a way to specify the order of workflow.
Take my code for example,
I want to execute ```copy2data``` before ```apollo2``` (This is why I wrote code in this order).
However, in reality it works opposite.

Thank you 

Best,
Chun-Hung

**Comment by mr-c** [comment]
Hello @r06942072  and thank you for your issue.

This repository is better for proposing changes to the CWL language itself. For assistance writing CWL I recommend making a post at https://www.biostars.org/t/cwl/ with the `cwl` tag.

Cheers,
