### ISSUE TITLE
Python class for CWL

### ISSUE THREAD

**Issue by SooLee** [common-workflow-language/common-workflow-language#851]
Hello

Is there a Python class for CWL that a python developer can use to read and parse CWL? It would be nice to have one, if we don't have one yet.

**Comment by kaushik-work** [comment]
Hi @SooLee You could try https://github.com/common-workflow-language/python-cwlgen

**Comment by SooLee** [comment]
@kaushik-work Thanks, I could try schema_salad, but I was looking for something more specific for CWL. Is there any plan for providing a CWL-specific class?

**Comment by kaushik-work** [comment]
Hi @SooLee 

I believe https://github.com/common-workflow-language/python-cwlgen provides some of this functionality too (in https://github.com/common-workflow-language/python-cwlgen/blob/master/cwlgen/import_cwl.py)

Perhaps you could use the `parse_cwl` function from that? (`pip install cwlgen`)

It's a good idea to provide a standalone CWL loader, say as it's own package, but as you can see from the readme, it's also one line to generate a CWL loader class from the schema itself. The result fits in one file which you can include in your source and import into your files.

> schema-salad-tool --codegen=python myschema.yml > myschema.py

Best
-Kaushik
