### ISSUE TITLE
Proposal: conditionals II (refinement of run_if)

### ISSUE THREAD

**Issue by kaushik-work** [common-workflow-language/common-workflow-language#854]
* This is a modification to #853 
* This author is also heavily in favor of simplifying user facing syntax
* This modification proposes to further simply the syntax in #853 and maintain congruency with existing CWL concepts

The design adds a new field `when` to a `WorkflowStep`. This field is an expression that
evaluates to `True` or `False`. Depending on this value the enclosed step is run or not.

The design also adds a new field `pickValue` which operates after `linkMerge` and serves to
filter out null values. While this can be used independently of the conditionals feature the
`first_non_null` and `only_non_null` are intended for the specific case where a list of inputs - some coming from conditional steps - converge on a scalar input.

![conditional-patterns-1](https://user-images.githubusercontent.com/6299530/69186358-6024c600-0ae6-11ea-9cc0-dcc4695d1056.png)

## Example workflow
```
class: Workflow
cwlVersion: v1.2.0-dev1
inputs:
  val: int

steps:

  step0:
    in:
      in1: val
      a_new_var: val
    run: ../tools/foo.cwl
    when: $(inputs.a_new_var > 1)
    out: [out1]


  step1:
    in:
      in1: val
      a_new_var: val
    run: ../tools/bar.cwl
    when: $(inputs.a_new_var < 1)
    out: [out1]

outputs:
  out1: 
    type: string
    outputSource:
        - step0/out1
        - step1/out1
    pickValue: first_non_null
```

Please see the [design document](https://github.com/common-workflow-language/common-workflow-language/blob/kaushik-work-patch-1/design-decisions/conditionals-2019.md) for details

References:
- https://groups.google.com/forum/m/?source=mog&gl=us#!topic/common-workflow-language/JU7PSEKr97M
- #494
- #789
- #853

Revisions:
2019.11.19: redirect readers to [design document](https://github.com/common-workflow-language/common-workflow-language/blob/kaushik-work-patch-1/design-decisions/conditionals-2019.md) for details. Add updated basic patterns image
2019.09.24: `runIf` -> `when` by popular demand
2019.05.29: Update nomenclature.
2019.05.14: Fix: `only_one` should throw error when everything is skipped
2019.05.13: Remove proposal for `default` with explanation, clarify language, update patterns
2019.05.11: Remove obsolete reference to `linkMerge`, fix `condMerge` values
2019.05.09: Change to use `condMerge`. Clarify some behaviors.
2019.04.22: Add `linkMerge:first_non_null`

**Comment by kaushik-work** [comment]
@tetron I'm hoping I understood `valueFrom`. Otherwise it will be more complicated.

**Comment by TMiguelT** [comment]
So, compared to my proposal you've removed `deps` and added some different linkMerges? I quite like these simplifications, in particular because you've removed the need for an order-matters syntax. However, in the passthrough example (#1) how does the engine know the dependencies for C if it doesn't list them as inputs? You would either have to add back the `pickFirst` option I had, or else reinstate my `deps` field. Is this wrong?

**Comment by kaushik-work** [comment]
@TMiguelT my expectation is that the scheduler/runner will see two inputs into C, wait for both A and B to finish and then use `valueFrom` to resolve the final value. If B doesn't run,  the scheduler will mark it as "skipped", furnish a null and the `valueFrom` will evaluate the output from A.

**Comment by TMiguelT** [comment]
Right, so you have two inputs with no input binding, and a third input that has no input, and only a binding? Can you mockup some CWL for how this might look?

**Comment by bogdang989** [comment]
A few observations:
- @TMiguelT in example1, inputs for C are outputs from both A and B, so the engine will have to wait for both A an B to run C. Also, B depends on A, so if B has a `run_if`, engine would process that `run_if` only after A completes. If the `run_if` in B is false, B is instantly completed and all outputs are set to `null`. This is something CWL already does with scattering over empty list. 
- The method `pickFirst` could be also added as a `linkMerge` method for example 1
- If example1 is handled with `valueFrom`, order of the connection still matters. Reason is that step input `valueFrom` will only have `self` object to work with, and `self` object would be something like `[output_from_B, output_from_A]`.
- All the proposed `linkMerge` methods can already be handled with `stepInput.valueFrom` JS magic
- For the `run_if: 'default'` behavior, I am wondering how this would work in execution. In a way you could say that, e.g in example 4, D depends on C and C depends on D(input source list)

**Comment by TMiguelT** [comment]
Oh I see, we can have the final input file be inside the `arguments`, and the two input candidates as `inputs`. That's quite neat!

> If example1 is handled with valueFrom, order of the connection still matters
Well currently `self` is set to the input value, which won't exist if we use `arguments`. But the `inputs` object should exist in the expression, and you can access them by id, can you not? So we can still avoid having order matter.

> All the proposed linkMerge methods can already be handled with stepInput.valueFrom JS magic
Good point. So really the minimal change we need is simply the addition of `run_if`, nothing else.

**Comment by kaushik-work** [comment]
@bogdang989 
1. You are correct that we don't have access to the individual input objects once they are in a list. After trying out various alternative order-free syntaxes I think that a "pick first" like that proposed by @TMiguelT is the most compact and easy to understand (it's called `first_non_null` here). I think I was more afraid of input ordering than I should be. For the visual editor we just have to worry about input ordering when the user requests `linkMerge: first_non_null`
2. I like using the proposed new  `linkMerge` values as these make the intent explicit, allow the scheduler to reason about and skip default steps as it can, and allow better validation, which would be opaque with JS expressions.

**Comment by kaushik-work** [comment]
Also, we should discuss whether we should have a new type `skipNull` distinct from the regular `null` in order to capture cases where a tool will produce a `null` output even when run, and this `null` carries information.

**Comment by tetron** [comment]
Need to consider how this interacts with step scatter.

**Comment by kaushik-work** [comment]
https://github.com/kaushik-work/cwl-conditionals

**Comment by bogdang989** [comment]
One comment before I forget, would it make sense to have `ignore_skip` be a default value for `condMerge`?

**Comment by kaushik-work** [comment]
@bogdang989 I would like to make developers users aware of their choices. Right now a skipped step's outputs get converted to regular nulls + a validation warning. A more strict enforcement would be to fail the workflow if any input getting a conditional does not have `condMerge`, forcing the developer to think about each connection from a conditional step.

If we wanted to get fancy and relieve the developer of some burden, we could do the following:
- If the conditionals go to a singleton input (e.g. `File`) `condMerge` defaults to `only_one` internally
- If the conditionals go to a list input (`File[]`) `condMerge` defaults to  `ignore_skip`

This would cover the major use cases.

**Comment by tetron** [comment]
Instead of `condMerge` I would call it something like `selector`

Suggest the default behavior without a condMerge/selector should be either `only_one` (I would rename this to `exactly_one`) or fail if any upstream is skipped.

I'm trying to think of a better way to handle "else" or "default" clauses.  Here's an idea for a selector that is only true in the negative case (everything is skipped):

![cwl-if-else](https://user-images.githubusercontent.com/1316612/57725477-3e401780-765b-11e9-9a07-a1f997848a14.png)

**Comment by tetron** [comment]
I'm thinking we also want to apply these operators to gather operations:

`gatherSelector` - apply to the list of tasks resulting from a scatter/gather operations

Does `run_if` get evaluated for the whole step or for each individual scatter step?  (probably the 2nd)

```
step1:
  in:
    abc: abc
  out: [out]
  scatter: abc
  run_if: $(inputs.abc > 3)
  run: example.cwl
  gatherSelector: ignore_skip
```

**Comment by kaushik-work** [comment]
1. `branchSelect` ? Inspired by reading up on conditionals and being reminded that these are called branches. Our DAG representation is explicitly enumerating all the code paths/branches and now we are allowing the scheduler to pick the branches
2. Yep, I agree that `run_if` should apply individually for each scatter branch. The runner can of course optimize by analyzing the expression to see if it contains any references that are being scattered on. If not, you only have to evaluate it once - but this is runner optimization.
3. Do we need a separate `gatherSelector`? It's just a bunch of inputs coming in as a list and should work fine like the non-scatter case, no? 

But this leads to this interesting case:

![scatter + run_if](https://user-images.githubusercontent.com/6299530/57729118-66337900-7663-11e9-8ac8-1a1e5ff2f581.png)

We are scattering on the value of "a" and for each value of "a" we either run B or C and in the end just collect them. I can see this being mis-used, or used in an un-expected manner, but we are giving users more power with conditionals, so they have to be more responsible.

**Comment by tetron** [comment]
We need a distinct `gatherSelector` because we gather all the results into a list, the output of the step is a list, and the next step doesn't know which elements of the list were skips.  So we have to apply the logic to decide what to do about the skips before constructing the final output list.  Although, the default behavior could just be "ignore_skip".

**Comment by kaushik-work** [comment]
@bogdang989 points out complexities involved in getting inputs from other steps.

Right now, I can do the following and getaway with a validation warning. 

```
class: Workflow
cwlVersion: v1.2
inputs:
  in1: File
  val: int

steps:
  step0:
    in:
      in1: val
    out: [out1]
    run: dummy-step.cwl

  step1:
    in:
      in1: in1
      baa: val
    out: [out1]
    run: bypass-step.cwl
    run_if: $(inputs.baa > 1)

outputs:
  out1: 
    type: File[]
    condMerge: first_non_skip  
    outputSource:
      - step1/out1
      - in1

requirements: 
  InlineJavascriptRequirement: {}
```

Which runs as expected, but with a validation warning
```
WARNING:cwltool:Workflow checker warning:
chain-bypass-wf.cwl:17:7: 'baa' is not an input parameter of
                          file:///Users/kghose/Work/code/cwl-conditionals/bypass-step.cwl, expected
                          in1
```

I want to reduce the developer burden and propose a static analysis in the validation that checks if a variable exists in a JS expression and adds that to the list of acceptable inputs in the step. Also, should warn if a non-existent variable exists in the  JS expression. This may be hard to get bullet proof - we'd raise the occasional false alarm of a `not an input parameter` variable.

Right now, I'm ok with these warnings.

**Comment by TMiguelT** [comment]
By the way, before it gets too far entrenched, surely you want to call the field `runIf` (in camel case like everything else in CWL) and not `run_if`?

**Comment by tetron** [comment]
@TMiguelT good point

**Comment by kaushik-work** [comment]
CamelCase is so 90s ...

**Comment by TMiguelT** [comment]
You're going to write CommonJavaWorkflowScript and you're going to like it

**Comment by TMiguelT** [comment]
I'm happy to help get this into the spec. Can you summarise what's left to do @kaushik-work? It seems we're still hashing out the selector syntax/behaviour. Then we'd have to get that into kaushik's implementation. Is that everything?

fwiw I prefer `branchSelect` out of these options, because as Kaushik says, it's the most technically precise. `selector` is nicer to write but it's too vague for my liking. It's not clear that it specifically applies to conditionals.

**Comment by kaushik-work** [comment]
Hi @TMiguelT I believe three things are left

1. Add exceptions to `checker.py` (validator) to allow multiple inputs to enter a single input port if they are from conditionals
2. Make `branchSelect` and optional field and implement logic so that `branchSelect` can be inferred based on the graph. There are cases when a user wants something different from what is inferred and can use `branchSelect`
3. Conformance tests (doubling as examples)

I had a few other things to do, but I plan to take this up again next week. Monday is a holiday for me.

**Comment by kaushik-work** [comment]
@TMiguelT for the code changes I've made
Please see: 

Toil: https://github.com/DataBiosphere/toil/compare/master...kaushik-work:kaushik/conditionals/runif
cwltool: https://github.com/common-workflow-language/cwltool/compare/kaushik/conditionals/runif

**Comment by mr-c** [comment]
@kaushik-work I updated one of your comments to use `cwlVersion: v1.1_conditionalsII` instead of `cwlVersion: v1.2` to make it clear that `v1.2` doesn't. Sorry to be pedantic!

**Comment by kaushik-work** [comment]
I just had a thought for `if-else` and `switch-default` use cases which could be implemented by building upon `runIf`. A new field `runAsFallbackFor` which takes a list of steps. Each listed step has to be conditional (have a `runIf`). The runner holds off on executing a step that is marked `runAsFallbackFor` until all the listed steps have either run or been skipped (so we track skips and execution condition too now). If no step in the list has run, the runner executes the step. Otherwise the runner skips this step.

**Comment by tetron** [comment]
Could that be done as `branchSelect: all_skip` ?

**Comment by kaushik-work** [comment]
Do I understand correctly: you mean not explicitly mark the steps the `else` or `default` is linked to but infer them from the connections? 

I should look at it again, but the problem I ran into when I tried to think about a back tracking driven scheme (like `branchSelect: all_skip`) was I found it hard to reason about. The logic from the runner side should be fine - you mark a step as "run only if default" and then you check if any of the inputs have non-skip values and then you go back and run this step. 

The hard part for me was as a workflow developer to now keep track of all the incident connections, especially if I now have multiple outputs from conditional steps going to different places. I could potentially create spaghetti code that becomes hard to understand.

I suspect one can also do this with the `runAsFallbackFor` and the only clean way to do this is to go back to the `Switch` proposal (i.e. create a new process object), inherit all the `runIf` behavior but make the steps special in that they can only be conditional, they can't connect to each other (only to the process I/O) and one of them gets to have a sentinel `runIf` value called `default`.

**Comment by kaushik-work** [comment]
Just a note here from a discussion on 09/17/2019:

@mr-c asked if we could fail the workflow if no `condMerge` is employed as opposed to just warning. @kaushik-work feels that this will be too annoying for the user and for the first version a warning is the way to go. However, it might possibly be wise to be harsh ...
