### ISSUE TITLE
cwltool --pack v1.0/count-lines8-wf.cwl

### ISSUE THREAD

**Issue by wgerlach** [common-workflow-language/common-workflow-language#855]
Hi,

playing with the compliance tests I noticed that the command `cwltool --pack v1.0/count-lines8-wf.cwl`  throws an error:

```
Resolved 'v1.0/count-lines8-wf.cwl' to 'file:///common-workflow-language/v1.0/v1.0/count-lines8-wf.cwl'
Tool definition failed initialization:
[Errno 2] No such file or directory: '/common-workflow-language/v1.0/wc-tool.cwl'
```

For all the other count-lines workflows the pack command works. Any idea?

**Comment by wgerlach** [comment]
Closing this issue as I am not using `--pack` anymore.

**Comment by mr-c** [comment]
Still worth fixing! Thanks for reporting it

**Comment by mr-c** [comment]
`cwltool` no longer throws an error in this case
