### ISSUE TITLE
CWL v1.1 release voting

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/common-workflow-language#861]
I propose the following commit for the next stable CWL specification, v1.1.  Please vote to accept or reject (with revisions).

https://github.com/common-workflow-language/cwl-v1.1/commit/b38414e57588f3df434755d0b51e6a3021b30441

Please add a comment with your vote, and we'll tally the votes here:

- [x] Peter Amstutz @tetron 
- [x] John Chilton @jmchilton 
- [x] Michael R. Crusoe @mr-c 
- [x] Brandi Davis Dusenbery @bdusenbery  @bdavisdusenbery 
- [ ] Jeff Gentry @geoffjentry 
- [x] Hervé Ménager @hmenager 
- [x] Stian Soiland-Reyes @stain

**Comment by tetron** [comment]
Also ping @kaushik-work

**Comment by mr-c** [comment]
Approved!

**Comment by jmchilton** [comment]
👍 - accept. Thanks all for this amazing effort and monumental achievement.

**Comment by stain** [comment]
My vote: accept

**Comment by hmenager** [comment]
approved

**Comment by bdusenbery** [comment]
accept!

**Comment by geoffjentry** [comment]
Sorry, was out of town - but looks like y'all got enough votes :) 🎉
