### ISSUE TITLE
Singularity or Docker as requirement

### ISSUE THREAD

**Issue by tamasgal** [common-workflow-language/common-workflow-language#864]
I am trying to define a `CommandLineTool` which is either available via a docker container (pulled from our private repository) or directly from a Singularity image file on the local machine or from an SFTP server but could not find out how to do it.
In the docs I found a hint that Singularity is supported but could not find a field to describe it.

What I want to do is running the tool inside a Docker container OR using a Singularity image with a given path.

Can anyone point me into the right direction?

**Comment by mr-c** [comment]
Hello @tamasgal 

CWL v1.0 and v1.1 support containers in the Docker format and being run using any container engine that can run a Docker format container such as Docker itself, Singularity, and udocker.

For the CWL reference runner `cwltool` and `toil-cwl-runner` use the `--singularity` command line flag to enable support.

Make sure your `CommandLineTool` has a `DockerRequirement` under `hints`: https://www.commonwl.org/user_guide/07-containers/index.html

**Comment by mr-c** [comment]
For example, the `cwltool`/`toil-cwl-runner` will ask Singularity to pull down the container using the equivalent of `singularity pull docker://debian:latest` as an example

**Comment by tamasgal** [comment]
Thanks Michael, but I still don't understand how to define Singularity image files there. We store our precompiled singularity image files on shared filesystems in our HPC environments and thus we simply need to prepend `singularity exec /path/to/image.simg` to the `tool_name`.

It seems that the Docker/Singularity support always requires a registry and pulls the images?

**Comment by illusional** [comment]
This is less of a CWL spec thing, but more of an engine configuration thing. You should define your container in the "DockerRequirement" (even though it's more of an OCI compliant container location). 

Re the engines: I don't know if CWLTool has a way to skip the singularity pull and override this "exec" command. Cromwell can, through writing a custom SFS configuration. Can provide more info but here probably isn't the most ideal case.

**Comment by tamasgal** [comment]
Alright I will try out to pull the images on HPC and see how it works. The problem is that many of our software packages needs quite a few env setups (scripts which needs to be sourced) but I guess it’s just a matter of getting it into a tool configuration file and forget about it forever.

I will also have a look at Cromwell, thanks!

**Comment by illusional** [comment]
If it's just calling `singularity pull`, you could probably just find out where your installation of singularity is caching and just put the resulting container there (with the correct name). 

Are you saying that you've got a few pieces of local software that you haven't dockerized yet, definitely worth doing for the portability aspect. We've been running workflows across organisations and it's been amazing to get the same results everywhere with next to no set up.

**Comment by tamasgal** [comment]
Thank you all, indeed it turned out to work like a charm by using `--singularity` ;)

**Comment by tamasgal** [comment]
Unfortunately on HPC I get `failed to create user namespace`

```
░ tgal@cca010:/sps/km3net/users/tgal/dev/pipelines  py-3.6@master ●
░ 13:34:01 > cwl-runner --singularity tools/mupage.cwl examples/mupage-job.yml
INFO /sps/km3net/users/tgal/python_envs/py-3.6/bin/cwl-runner 1.0.20190621234233
INFO Resolved 'tools/mupage.cwl' to 'file:///sps/km3net/users/tgal/dev/pipelines/tools/mupage.cwl'
INFO Using local copy of Singularity image found in /sps/km3net/users/tgal/dev/pipelines
INFO [job mupage.cwl] /scratch/users/t/tgal/mf1ja4sf$ singularity \
    --quiet \
    exec \
    --contain \
    --pid \
    --ipc \
    --bind \
    /scratch/users/t/tgal/mf1ja4sf:/jPIlTb:rw \
    --bind \
    /scratch/users/t/tgal/uh1a2cuj:/tmp:rw \
    --pwd \
    /jPIlTb \
    /sps/km3net/users/tgal/dev/pipelines/docker.km3net.de_simulation_mupage:latest.sif \
    mupage.exe \
    -p \
    inputs.par \
    -i \
    1 \
    -n \
    10 \
    -s \
    23 \
    -o \
    test.evt \
    test.evt.info
ERROR  : Failed to create user namespace
WARNING [job mupage.cwl] completed permanentFail
{
    "output": []
}
WARNING Final process status is permanentFail
```

This is maybe due to some restrictions of the HPC Singularity setup?

**Comment by mr-c** [comment]
@tamasgal Looks like `inputs.par` isn't mounted inside the container. Is it `type: File`?

**Comment by tamasgal** [comment]
Yes it’s a binding problem. It seems that the mounting of local folders is not workin on our main HPC farm. I’ll close this since it’s not related to CWL.

**Comment by mr-c** [comment]
Glad it wasn't us, but I'd like to know more so we can provide a better user experience.

Which version of Singularity?
