### ISSUE TITLE
CWL mini-conference: 2019-10-17 & 18

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#868]
We are interested to hear from

* Workflow engine developers with an emphasis on Kubernetes.
* Sysadmins, operations people, and/or devops people who are running CWL workflows in production (or who plan to)
* Users of CWL, at any scale or complexity
* Any other participant in the CWL ecosystem

Please react to this issue with a 👍🏻👍🏼👍🏽👍🏾👍🏿 if you are interested in attending
![animated example of the emoji reaction interface](https://github.blog/wp-content/uploads/2016/03/d55b8b7e-e6ba-11e5-9b31-59a8db92e456.gif)

Please respond to this issue if you would like to help us organize the mini-conference.

If you are interested in attending but lack the financial resources or face other barriers to your participation then please get in touch directly: mrc@commonwl.org

- [ ] venues
- [ ] additional content areas
- [ ] call for presentations, papers, and demos
- [ ] travel fellowships?

**Comment by swzCuroverse** [comment]
Do you need space and help with organizing?  Maybe Meredith on our end could help.  I could also see if my colleague at MIT libraries would help with a venue.

**Comment by tfmorris** [comment]
Presumably the date & location were chosen to be near the [GA4GH Plenary](https://broadinstitute.swoogo.com/GA4GH7thPlenary) but there's a 2 day gap in the middle. Would it make folks travel logistics easier if it was bookended on Oct 20 or 24 (or perhaps even in parallel like [GenoPrio](https://www.genopri.org/)?

**Comment by tnabtaf** [comment]
Has there been any progress on planning this event?

**Comment by tetron** [comment]
Not yet.

**Comment by mr-c** [comment]
Thank you all, we confirm that the event is happening on Thursday, October 17th (core contributors & workflow engine devs) and Friday, October 18th (for everyone). Please indicate your interest at https://forms.gle/AqHfBf4NTfvGyJCUA !

**Comment by mr-c** [comment]
Thanks to all the participants! The slides are at https://drive.google.com/open?id=1ZJid2p3IyjC8B4nx73iYyP07QIPxa89t

The next edition is tentatively schedule for sometime in the week of March 23rd in either NYC or Boston.

**Comment by cgreene** [comment]
> The next edition is tentatively schedule for sometime in the week of March 23rd in either NYC or Boston.

Is there an update on this?

**Comment by mr-c** [comment]
@cgreene Yes, the next edition will be May 14th & 15th in NYC!
