### ISSUE TITLE
`Dirent.entry`: `Directory` should be allowed

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#878]
The [spec of v1.1](https://www.commonwl.org/v1.1/CommandLineTool.html#Dirent) describes the `entry` field in `Dirent` object as follows:

```markdown
If the value is an expression that evaluates to a `File` object, this indicates the referenced file should be added to the designated output directory prior to executing the tool.

If the value is an expression that evaluates to a `Dirent` object, this indicates that the File or Directory in `entry` should be added to the designated output directory with the name in `entryname`.
```

It lacks the case of `Directory` object.
In the discussion with @mr-c, the former sentence should be fixed as follows:
```markdown
If the .... that evaluates to a `File` or `Directory` object, ...
```

**Comment by mr-c** [comment]
This was fixed in CWL v1.2, thank you @tom-tan for the report! https://www.commonwl.org/v1.2/CommandLineTool.html#Dirent
