### ISSUE TITLE
Clarify the description of `basename` modification in the spec

### ISSUE THREAD

**Issue by tom-tan** [common-workflow-language/common-workflow-language#881]
The [spec of `File`](https://docs.google.com/presentation/d/1XwOC18LzDvaTqw1QAGI6L7djhL5CEkQL5aiGZEdnK1Y/edit#slide=id.g60d002c0b6_5_60) says:

```markdown
The `basename` property defines the filename on disk where the file is staged. This may differ from the resource name.
...
It is legal to return a file object with an existing `location` but a different `basename`. 
```

But it is not clear what should happen when `basename` is modified by Javascript expressions.

The [Miscellaneous section in User Guide](https://www.commonwl.org/user_guide/misc/) says that it modifies the actual file name but it should be clarified in the spec.

**Comment by AfiMaameDufie** [comment]
Hi @mr-c ,

I would like to take a look at this.

Can you kindly give me clarity on how to go about this?

**Comment by tom-tan** [comment]
Now I understand what happens!
We do not have to fix the spec!

- When modifying the `basename` in `outputEval`, it just modifies the resulted `File` object in the output object but does not change the file name on disk. Modifying it in `outputEval` is valid as described in [5.1.7](https://www.commonwl.org/v1.2/CommandLineTool.html#File).
- When staging the files in the output object from temporal directory to the output directory, the file is renamed according to the spec in section 5.1.7. This operation is also valid and already in the spec.
  > The `basename` property defines the filename on disk where the file is staged.

As the result, by modifying the `basename` field in `outputEval`, an engine modifies the file name when staging it to the output directory.
I close this issue because the current description of the spec is sufficient to explain the behavior.

**Comment by tetron** [comment]
That's right, that is intended behavior, one which should be covered by conformance tests, and is used by real workflows as a way to logically rename files without having to actually rename the underlying objects.
