### ISSUE TITLE
Proposal: Fractional CPU

### ISSUE THREAD

**Issue by kaushik-work** [common-workflow-language/common-workflow-language#883]
Allow `coresMin` `coresMax` to have fractional values (`long` -> `float`).

This is very useful when packing/scheduling jobs that are I/O bound and the OS can actually fit several of these onto one CPU. Currently there is no way to indicate these types of processes.

**Comment by mr-c** [comment]
@kaushik-work Cool idea. If implemented, i suggest that `$(runtime.cores)` is still a `long`, rounded down to no less than 1.

**Comment by kaushik-work** [comment]
@mr-c ah interesting twist. What is `$(runtime.cores)` typically used for? Also, in the intended usage, I wonder if any float value greater than 1 is meaningful. I guess one could calibrate the tool's usage to say, "I can run 5 of these in parallel on 2 CPUs" ...

**Comment by mr-c** [comment]
@kaushik-work `$(runtime.cores)` is often passed to tools to set the number of threads 

https://github.com/genome/analysis-workflows/blob/0798b3933ae3e6486596294984c7ffee50b94ef5/definitions/tools/biscuit_markdup.cwl#L24

https://github.com/search?l=Common+Workflow+Language&p=2&q=%24%28runtime.cores%29&type=Code

**Comment by kaushik-work** [comment]
@mr-c yes, this should def be an integer.
