### ISSUE TITLE
Improve SecondaryFileSchema docs in the specification

### ISSUE THREAD

**Issue by bogdang989** [common-workflow-language/common-workflow-language#891]
When looking at https://www.commonwl.org/v1.1/CommandLineTool.html#SecondaryFileSchema, there seems to be no indication that a string value is allowed for a secondaryFile pattern which can (and did) confuse people reading the spec. That detail is explained in SchemaSalad spec section for secondary files DSL. This explanation (https://www.commonwl.org/v1.1/SchemaSalad.html#Domain_Specific_Language_for_secondary_files) is exactly the info I was hoping to see in the spec for `secondaryFileSchema`. Would it make sense to somehow add this to https://www.commonwl.org/v1.1/CommandLineTool.html#SecondaryFileSchema (at least a link to the SchemaSalad spec)?
Would this additional `doc` for `SecondaryFileSchema` go to v1.1 or v1.2 spec?

**Comment by mr-c** [comment]
Fixed in https://github.com/common-workflow-language/cwl-v1.2/pull/5 ; thanks @bogdang989 !
