### ISSUE TITLE
cwl-runner --dry-run does not work on example (lobSTR) workflow

### ISSUE THREAD

**Issue by jrandall** [common-workflow-language/common-workflow-language#90]
Running the lobSTR workflow is working for me. However, when I attempt to run it with `--dry-run` I get an error:
```bash
$ cwl-runner --dry-run ./lobSTR-workflow.cwl lobSTR-demo.json
Workflow error:
  Workflow cannot make any more progress.
```

**Comment by tetron** [comment]
You're right, that option hasn't been properly tested.  I'm not even sure what it should do for a workflow where it's hard to "dry run" downstream steps that rely on upstream steps.

**Comment by tetron** [comment]
I should just remove the --dry-run option, I don't think it works.

**Comment by mr-c** [comment]
:-( I think `--dry-run` is important

**Comment by tetron** [comment]
Let's move discussion over to https://github.com/common-workflow-language/cwltool/issues/11
