### ISSUE TITLE
Develop a CWL Mission Statement

### ISSUE THREAD

**Issue by swzCuroverse** [common-workflow-language/common-workflow-language#912]
Discussed with Peter and Michael,  we should develop a Mission Statement.  I said I would take a shot - and then iterate with all leadership team and community members. 

Will be working on this document:  
https://docs.google.com/document/d/1oRbvZ29ngdYXhDfNT0zlvnLghqKSiydxIwC6XxRsJus/edit?usp=sharing

Should be available to anyone with link to comment

**Comment by swzCuroverse** [comment]
Note - this will be funded through the CZI EOSS grant.

**Comment by swzCuroverse** [comment]
Example from RedHat -- "“To be the catalyst in communities of customers, contributors, and partners creating better technology the open source way. "

**Comment by swzCuroverse** [comment]
Important terms -- 
consensus-based
open
standards 
describing analysis workflows and tools.

**Comment by mr-c** [comment]
This has been accomplished; thank you @swzCuroverse !
