### ISSUE TITLE
Reading filenames from another file in the runtime and treating them as files

### ISSUE THREAD

**Issue by mr-eyes** [common-workflow-language/common-workflow-language#920]
Hi,

> this is similar to this [one](https://www.biostars.org/p/234650/) but could work out with me.

I have two CWL files running in workflow steps. The first CWL downloads a file, the second CWL uses docker and loads a YAML file with that downloaded file name as input. The downloaded file is stored at a temp location in the runtime, so it can't be found when specifying its name in another file (requires the temp full path).

How can the CWL read the filename from the YAML file in the runtime and treat it as a file?

Thanks!

**Comment by tetron** [comment]
Hello, @mr-eyes, could you please post your question on https://cwl.discourse.group/ ?

**Comment by mr-c** [comment]
Thanks @mr-eyes for posting at https://cwl.discourse.group/t/reading-filenames-from-another-file-in-the-runtime-and-treating-them-as-files/282/3 ; I'm going to close this issue now
