### ISSUE TITLE
CWL project infrastructure reliant on single individual, private infrastructure

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#94]
@tetron and I discussed this at BOSC. He agrees that the testing & release infrastructure should be transitioned to team management within six months.

Here's a partial checklist; details TBD

- [x] pypi releases (add additional users)
- [x] CI
- [ ] release pushing

**Comment by tetron** [comment]
TravisCI now supports Docker: http://docs.travis-ci.com/user/docker/

**Comment by mr-c** [comment]
Ping @tetron :-)

**Comment by tetron** [comment]
@mr-c I think we're almost done with the transition?

**Comment by mr-c** [comment]
We've switched to manual release, so we are done for now! Thanks @tetron .
